//! The pacman half of the image build: the in-image configuration, the offline install command
//! and the installed-closure read-back (M-Arch-Base T-5).
//!
//! Everything here is a **pure function of the [`BaseEntry`]**. The same lock gives the same
//! bytes on every run and on every machine, which is what makes an image identity stable; the
//! golden files under `tests/fixtures/arch/build/` are those bytes, and `tests/arch_image.rs`
//! compares them byte for byte.
//!
//! Three rules shape the generated build:
//!
//! - **No network and no repository synchronization.** The build runs with `--network=none` and
//!   installs the verified package files that are bind-mounted at [`PACKAGE_MOUNT`], with one
//!   `-U` invocation over all of them at once. The generated configuration exists so that the
//!   environment a developer enters agrees with the lock it was built from; no command of this
//!   build refreshes a database or downloads a package inside the image (design call D9).
//! - **No signature checking and no keyring** (LD-57): `SigLevel = Never`. The integrity
//!   statement is HTTPS plus the lock's hash chain, exactly as it is for the apt family, and the
//!   key-management program is never invoked anywhere in this tree.
//! - **The installed database is never touched.** The trim removes the package cache, the log,
//!   the root cache and the temporary files; `/var/lib/pacman/local` is what the read-back
//!   reads, and deleting it would make the closure comparison meaningless (design call D10).
//!
//! One thing this family's lock cannot state is what the bootstrap archive already contains: Arch
//! publishes no package list beside it, the way a Debian rootfs release does, and lock time
//! fetches metadata only. So the build **records** it: before installing anything, the first
//! command of the build writes `pacman -Qi` to [`BOOTSTRAP_RECORD`], and the read-back compares
//! the installed set against that record together with the lock's closure, the lock winning
//! wherever both name a package. A record that is missing or unreadable is itself a difference,
//! so nothing is assumed about a base that did not say what it was.
//!
//! The bootstrap archive of this family unpacks under one top-level directory, so the imported
//! image is not a root filesystem yet. The build turns it into one with a copy stage — a second
//! stage that copies `/<subdir>/` over `/` — which **runs no program inside the imported
//! image**, and so needs no shell there.

use std::collections::BTreeMap;

use crate::arch::base::Pacman;
use crate::container::IMAGE_FORMAT;
use crate::distro::{ImageOps, ReadBack};
use crate::lock::{BaseEntry, ClosureEntry};
use crate::util::sha256_hex;

/// Where the verified package files of a build are mounted, read-only.
const PACKAGE_MOUNT: &str = "/lodi-pkgs";
/// The mirror list the generated configuration includes.
const MIRRORLIST: &str = "/etc/pacman.d/mirrorlist";
/// Where the generated build records the bootstrap's own installed set, before installing. It
/// sits at the image root, beside the package mount, and not under `/var/lib/lodi`: that
/// directory is the **host scope's** state (`hostscope::safety::STATE`), and a file of the same
/// family's name in an image is a different thing in a place that already means something.
pub const BOOTSTRAP_RECORD: &str = "/lodi-base-packages";

impl ImageOps for Pacman {
    fn build_files(&self, base: &BaseEntry, has_packages: bool) -> BTreeMap<&'static str, String> {
        let mut configuration = format!(
            "# Generated by Lodi ({IMAGE_FORMAT}); every package is installed from a verified \
             file.\n\
             [options]\n\
             Architecture = {}\n\
             SigLevel = Never\n",
            base.deb_arch
        );
        let mut mirrorlist = format!(
            "# Generated by Lodi ({IMAGE_FORMAT}); these are the repositories the lock pins.\n"
        );
        for repository in &base.repositories {
            configuration.push_str(&format!(
                "\n[{}]\nServer = {}\nInclude = {MIRRORLIST}\n",
                repository.name, repository.url
            ));
            mirrorlist.push_str(&format!("Server = {}\n", repository.url));
        }
        // The archive unpacks under one directory; the copy stage makes that directory the root
        // without running anything in the imported image.
        let root = match base.rootfs.subdir.as_deref() {
            Some(subdir) => format!(
                "FROM {{BASE}} AS bootstrap\n\
                 FROM scratch\n\
                 COPY --from=bootstrap /{subdir}/ /\n"
            ),
            None => "FROM {BASE}\n".to_string(),
        };
        let install = if has_packages {
            format!(" && pacman -U --noconfirm --needed {PACKAGE_MOUNT}/*.pkg.tar.zst")
        } else {
            String::new()
        };
        // The record is written first, so it states the bootstrap alone, and under `LC_ALL=C`,
        // so the read-back's grammar is the one the record was written in. Its path is at the
        // image root, so there is no directory to create.
        let containerfile = format!(
            "# Generated by Lodi ({IMAGE_FORMAT}); the build runs without network.\n\
             {root}\
             COPY pacman.conf /etc/pacman.conf\n\
             COPY mirrorlist {MIRRORLIST}\n\
             RUN set -eu && LC_ALL=C pacman -Qi > {BOOTSTRAP_RECORD}\
             {install} \
             && rm -rf /var/cache/pacman/pkg/* /var/log/pacman.log /root/.cache /tmp/* \
             && : > /etc/machine-id\n"
        );
        let mut files = BTreeMap::new();
        files.insert("Containerfile", containerfile);
        files.insert("pacman.conf", configuration);
        files.insert("mirrorlist", mirrorlist);
        files
    }

    fn closure_query_arguments<'a>(&self, tag: &'a str) -> Vec<&'a str> {
        vec![
            "run",
            "--rm",
            "--log-driver=none",
            "--network=none",
            "--pull=never",
            "--security-opt",
            "label=disable",
            "--env",
            "LC_ALL=C",
            "--entrypoint",
            "pacman",
            tag,
            "-Qi",
        ]
    }

    fn recorded_base_arguments<'a>(&self, tag: &'a str) -> Option<Vec<&'a str>> {
        Some(vec![
            "run",
            "--rm",
            "--log-driver=none",
            "--network=none",
            "--pull=never",
            "--security-opt",
            "label=disable",
            "--entrypoint",
            "cat",
            tag,
            BOOTSTRAP_RECORD,
        ])
    }

    /// The installed set must be exactly the lock's closure together with what the build
    /// recorded of the bootstrap, the lock winning on version and architecture wherever both
    /// name a package. An absent record is a difference of its own: this family's lock cannot
    /// name the bootstrap's packages, so without the record there is nothing to compare against
    /// and assuming an empty base would turn every bootstrap package into a false drift.
    fn closure_differences(&self, read_back: &ReadBack, closure: &[ClosureEntry]) -> Vec<String> {
        let (installed, mut out) = read_installed(read_back.installed);
        // Without the record there is no expected set to compare against: every package the
        // bootstrap brought would be reported as an addition, which would bury the one
        // difference that explains the rest. It is reported alone.
        let recorded = match read_back.recorded_base {
            None => {
                out.push(format!(
                    "the image does not carry the base package set the build records at \
                     {BOOTSTRAP_RECORD}"
                ));
                return out;
            }
            // An empty record is not "the bootstrap brought nothing": a bootstrap that installed
            // no package cannot run the installer the build's next line invokes.
            Some(text) if text.trim().is_empty() => {
                out.push(format!(
                    "the base package set the build records at {BOOTSTRAP_RECORD} is empty"
                ));
                return out;
            }
            Some(text) => {
                let (packages, broken) = read_installed(text);
                out.extend(
                    broken
                        .into_iter()
                        .map(|line| format!("recorded base: {line}")),
                );
                packages
            }
        };
        let mut expected: BTreeMap<&str, (&str, Option<&str>)> = BTreeMap::new();
        for (name, (version, arch)) in &recorded {
            expected.insert(name.as_str(), (version.as_str(), Some(arch.as_str())));
        }
        // The lock wins: an installed package the lock pins must be at the pinned version even
        // when the bootstrap brought another one.
        for p in closure {
            expected.insert(p.name.as_str(), (p.version.as_str(), p.arch.as_deref()));
        }
        for (name, (version, arch)) in &expected {
            match installed.get(*name) {
                None => out.push(format!("missing: {name} {version}")),
                Some((have_version, have_arch)) => {
                    let arch_ok = arch.is_none_or(|a| a == have_arch);
                    if have_version != version || !arch_ok {
                        out.push(format!(
                            "changed: {name} expected {version} {}, installed {have_version} \
                             {have_arch}",
                            arch.unwrap_or("-")
                        ));
                    }
                }
            }
        }
        for (name, (version, _)) in &installed {
            if !expected.contains_key(name.as_str()) {
                out.push(format!("added: {name} {version}"));
            }
        }
        out
    }

    fn package_mount(&self) -> &'static str {
        PACKAGE_MOUNT
    }

    fn staged_package_name(&self, name: &str, version: &str) -> String {
        // The name only has to be unique and to carry the suffix the install command globs;
        // the installer reads the package's own metadata for its real name and version.
        format!("{name}-{}.pkg.tar.zst", sha256_hex(version.as_bytes()))
    }
}

/// The installed packages the read-back reported, by name, and one line per line of output that
/// could not be read.
///
/// The output is a sequence of `Key : Value` records separated by blank lines, with a continued
/// value indented. Every record begins with its name, so a field before one — a message, or
/// anything else that is not part of a record — is not silently taken for a field of the record
/// that follows. A line that is neither a field, a continuation nor a separator; a field that
/// repeats inside one record; and a record that does not carry a name, a version and an
/// architecture are each reported, never skipped: an unreadable read-back is a drift the caller
/// must see, not a smaller installed set.
fn read_installed(output: &str) -> (BTreeMap<String, (String, String)>, Vec<String>) {
    let mut installed: BTreeMap<String, (String, String)> = BTreeMap::new();
    let mut broken: Vec<String> = Vec::new();
    let mut record: BTreeMap<&str, &str> = BTreeMap::new();
    let mut started = false;
    let mut flush = |record: &mut BTreeMap<&str, &str>, broken: &mut Vec<String>| {
        if record.is_empty() {
            return;
        }
        match (
            record.get("Name"),
            record.get("Version"),
            record.get("Architecture"),
        ) {
            (Some(name), Some(version), Some(arch))
                if !name.is_empty() && !version.is_empty() && !arch.is_empty() =>
            {
                installed.insert(
                    (*name).to_string(),
                    ((*version).to_string(), (*arch).to_string()),
                );
            }
            _ => broken.push(format!(
                "installed package record without a name, a version and an architecture \
                 (fields: {})",
                record.keys().copied().collect::<Vec<_>>().join(", ")
            )),
        }
        record.clear();
    };
    for line in output.lines() {
        if line.trim().is_empty() {
            flush(&mut record, &mut broken);
            started = false;
            continue;
        }
        if line.starts_with(' ') || line.starts_with('\t') {
            // A value continued on the next line; the key it belongs to was read already.
            if !started {
                broken.push(format!("unreadable installed package line `{line}`"));
            }
            continue;
        }
        match line.split_once(':') {
            // A record starts with the package's name; anything else before one is not a field.
            Some((key, value))
                if !key.trim().is_empty() && !(record.is_empty() && key.trim() != "Name") =>
            {
                if record.insert(key.trim(), value.trim()).is_some() {
                    broken.push(format!("repeated installed package field `{}`", key.trim()));
                }
                started = true;
            }
            _ => broken.push(format!("unreadable installed package line `{line}`")),
        }
    }
    flush(&mut record, &mut broken);
    (installed, broken)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::distro::Family;

    fn entry(name: &str, version: &str, arch: Option<&str>) -> ClosureEntry {
        ClosureEntry {
            name: name.into(),
            version: version.into(),
            arch: arch.map(Into::into),
            origin: "base".into(),
            sha256: None,
            filename: None,
            size: None,
            repository: None,
            suite: None,
            epoch: None,
            release: None,
        }
    }

    fn record(name: &str, version: &str, arch: &str) -> String {
        format!(
            "Name            : {name}\n\
             Version         : {version}\n\
             Description     : a package: with a colon in its description\n\
             Architecture    : {arch}\n\
             Depends On      : glibc\n\
             Optional Deps   : one: for something\n                  two: for something else\n\
             \n"
        )
    }

    /// A read-back of `installed` with a bootstrap that recorded `base`.
    fn back<'a>(installed: &'a str, base: &'a str) -> ReadBack<'a> {
        ReadBack {
            installed,
            recorded_base: Some(base),
        }
    }

    #[test]
    fn this_family_answers_both_halves_of_the_seam() {
        assert!(Family::Pacman.ops().is_ok());
        assert_eq!(
            Family::Pacman.image_ops().package_mount(),
            Pacman.package_mount()
        );
        assert_eq!(Pacman.package_mount(), "/lodi-pkgs");
        assert!(
            Pacman
                .staged_package_name("acl", "2.3.2-1")
                .ends_with(".pkg.tar.zst")
        );
    }

    #[test]
    fn the_installed_set_must_equal_the_lock_and_the_recorded_base() {
        let lock = [
            entry("acl", "2.3.2-1", Some("x86_64")),
            entry("licenses", "20240728-1", None),
        ];
        let bootstrap = record("glibc", "2.40-1", "x86_64");
        let same = format!(
            "{bootstrap}{}{}",
            record("acl", "2.3.2-1", "x86_64"),
            record("licenses", "20240728-1", "any")
        );
        assert!(
            Pacman
                .closure_differences(&back(&same, &bootstrap), &lock)
                .is_empty()
        );
        // A bootstrap package the lock does not name is expected, not `added:`; one the record
        // does not name either is still reported.
        let drift = format!(
            "{bootstrap}{}{}",
            record("acl", "2.3.3-1", "x86_64"),
            record("tree", "2.1.1-2", "x86_64")
        );
        let d = Pacman.closure_differences(&back(&drift, &bootstrap), &lock);
        assert!(d.iter().any(|l| l.starts_with("changed: acl")), "{d:?}");
        assert!(d.iter().any(|l| l == "added: tree 2.1.1-2"), "{d:?}");
        assert!(
            d.iter().any(|l| l.starts_with("missing: licenses")),
            "{d:?}"
        );
        assert!(!d.iter().any(|l| l.contains("glibc")), "{d:?}");
        // The architecture is compared when the lock states one.
        let wrong = format!(
            "{bootstrap}{}{}",
            record("acl", "2.3.2-1", "i686"),
            record("licenses", "20240728-1", "any")
        );
        assert_eq!(
            Pacman
                .closure_differences(&back(&wrong, &bootstrap), &lock)
                .len(),
            1
        );
        // The lock wins where both name a package: the bootstrap's own version is not accepted.
        let older = record("acl", "2.3.1-1", "x86_64");
        let both = format!(
            "{bootstrap}{older}{}",
            record("licenses", "20240728-1", "any")
        );
        let d = Pacman.closure_differences(&back(&both, &format!("{bootstrap}{older}")), &lock);
        assert_eq!(d.len(), 1, "{d:?}");
        assert!(d[0].starts_with("changed: acl expected 2.3.2-1"), "{d:?}");
        // A bootstrap package that the install removed is reported, never ignored.
        let gone = format!(
            "{}{}",
            record("acl", "2.3.2-1", "x86_64"),
            record("licenses", "20240728-1", "any")
        );
        let d = Pacman.closure_differences(&back(&gone, &bootstrap), &lock);
        assert_eq!(d, vec!["missing: glibc 2.40-1".to_string()], "{d:?}");
    }

    #[test]
    fn an_image_without_the_recorded_base_is_itself_a_difference() {
        let lock = [entry("acl", "2.3.2-1", Some("x86_64"))];
        let installed = record("acl", "2.3.2-1", "x86_64");
        let d = Pacman.closure_differences(
            &ReadBack {
                installed: &installed,
                recorded_base: None,
            },
            &lock,
        );
        assert_eq!(d.len(), 1, "{d:?}");
        assert!(d[0].contains(BOOTSTRAP_RECORD), "{d:?}");
        // The read-back names the file the build writes, so the two cannot drift apart.
        let arguments = Pacman.recorded_base_arguments("localhost/x:y").unwrap();
        assert!(arguments.contains(&BOOTSTRAP_RECORD), "{arguments:?}");
    }

    #[test]
    fn a_line_that_does_not_parse_is_reported_and_never_skipped() {
        let lock = [entry("acl", "2.3.2-1", Some("x86_64"))];
        let output = format!(
            "error: this is not a record\n{}",
            record("acl", "2.3.2-1", "x86_64")
        );
        let bootstrap = record("glibc", "2.40-1", "x86_64");
        let d = Pacman.closure_differences(&back(&output, &bootstrap), &lock);
        assert_eq!(d.len(), 2, "{d:?}");
        assert!(d[0].contains("error: this is not a record"), "{d:?}");
        assert_eq!(d[1], "missing: glibc 2.40-1");
        // A record missing one of the three fields is a difference too, not a smaller set.
        let short = "Name            : acl\nVersion         : 2.3.2-1\n";
        let d = Pacman.closure_differences(&back(short, &bootstrap), &lock);
        assert!(d.iter().any(|l| l.contains("without a name")), "{d:?}");
        // An empty record is a difference of its own, never an empty base.
        let d = Pacman.closure_differences(&back(&record("acl", "2.3.2-1", "x86_64"), ""), &lock);
        assert_eq!(d.len(), 1, "{d:?}");
        assert!(d[0].contains("is empty"), "{d:?}");
        // An unreadable line of the recorded base is named as such.
        let d = Pacman.closure_differences(
            &back(&record("acl", "2.3.2-1", "x86_64"), "not a record\n"),
            &lock,
        );
        assert_eq!(d.len(), 1, "{d:?}");
        assert!(d[0].starts_with("recorded base: "), "{d:?}");
    }
}
