//! M-Arch-Base T-5: the offline pacman image build, driven from a hand-written lock.
//!
//! Two halves, both offline and both deterministic:
//!
//! 1. **The generated bytes.** `tests/fixtures/arch/lodi.lock` is a hand-written Arch lock; the
//!    files an image build would generate for it are committed under `tests/fixtures/arch/build/`
//!    and compared byte for byte. They are a pure function of the lock, so a change to them is a
//!    change to every Arch image identity and this test is where it shows up.
//! 2. **The build itself.** `container::realize_image` runs against a **stand-in for Podman**: a
//!    script this test writes, which records every command, hands back the context the build
//!    wrote and answers the read-back with output the test chose. That is what makes the drift
//!    path — `E_CLOSURE_DRIFT` at exit 6, naming the package, with the image removed — a checked
//!    behaviour of the real code rather than a claim. Building a real Arch image needs a real
//!    Arch rootfs and real package files; that measurement is the probe's
//!    (`sh scripts/march-local.sh --case rootfs`) and its numbers are in the package record.
//!
//! Nothing here needs the network, a real Podman or a container runtime. Since M-Arch-Base T-6
//! the manifest accepts `distro = "arch"`; the end-to-end path that writes such a lock is
//! `tests/arch_end_to_end.rs`, and this file stays what it was — the proof that the generated
//! bytes and the read-back of an already written lock are exactly what is committed here.

mod support;

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use lodi::container::{Podman, build_file_digests, image_identity, image_names, realize_image};
use lodi::diag::exit_status;
use lodi::distro::{Family, ImageOps, ReadBack};
use lodi::fetch::{FetchError, Fetcher};
use lodi::lock::{BaseEntry, closure_hash, parse_lock, validate};
use lodi::store::{Report, Store};
use lodi::util::sha256_tagged;

const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/arch");

fn fixture(name: &str) -> String {
    fs::read_to_string(Path::new(FIXTURE).join(name)).unwrap()
}

/// The hand-written Arch lock's base entry. Parsing it through `parse_lock` is deliberate: the
/// fixture is a lock this build would accept, not a struct literal that only this test believes.
fn base() -> BaseEntry {
    let lock = parse_lock(fixture("lodi.lock").as_bytes()).unwrap();
    validate(&lock).unwrap();
    lock.base.unwrap()
}

/// The pacman family's image operations, reached the way `src/container.rs` reaches them.
fn ops() -> &'static dyn ImageOps {
    Family::Pacman.image_ops()
}

// -------------------------------------------------------------------------------------------
// 1. The generated bytes.
// -------------------------------------------------------------------------------------------

#[test]
fn the_generated_files_are_the_committed_golden_files() {
    let base = base();
    let files = ops().build_files(&base, true);
    assert_eq!(
        files.keys().copied().collect::<Vec<_>>(),
        ["Containerfile", "mirrorlist", "pacman.conf"],
        "the image build generates exactly these files",
    );
    for (name, golden) in [
        ("Containerfile", "build/Containerfile"),
        ("pacman.conf", "build/pacman.conf"),
        ("mirrorlist", "build/mirrorlist"),
    ] {
        assert_eq!(
            files[name],
            fixture(golden),
            "{name} is not its golden file"
        );
    }
    // A base with nothing to install generates the same configuration and a build with no
    // install command at all.
    let empty = ops().build_files(&base, false);
    assert_eq!(empty["pacman.conf"], files["pacman.conf"]);
    assert_eq!(empty["mirrorlist"], files["mirrorlist"]);
    assert_eq!(
        empty["Containerfile"],
        fixture("build/Containerfile.no-packages")
    );
}

#[test]
fn every_generated_file_is_a_pure_function_of_the_lock() {
    let reparsed = base();
    let base = base();
    assert_eq!(
        ops().build_files(&base, true),
        ops().build_files(&base, true)
    );
    assert_eq!(image_identity(&base), image_identity(&base));
    // Nothing outside the lock reaches the bytes: the same entry parsed again is the same
    // identity, and one changed repository URL is a different one.
    assert_eq!(image_identity(&base), image_identity(&reparsed));
    let mut moved = base.clone();
    moved.repositories[0].url =
        "https://archive.archlinux.org/repos/2026/09/02/core/os/x86_64/".to_string();
    assert_ne!(image_identity(&base), image_identity(&moved));
    // The identity of an Arch lock is not the identity of any apt lock, because the generated
    // file names and digests differ.
    let digests = build_file_digests(&base, true);
    assert_eq!(
        digests.keys().cloned().collect::<Vec<_>>(),
        ["Containerfile", "mirrorlist", "pacman.conf"]
    );
    let (tag, record) = image_names(&base);
    assert!(tag.starts_with("localhost/lodi-env:"), "{tag}");
    assert!(record.starts_with("img-"), "{record}");
}

#[test]
fn the_generated_build_never_syncs_never_signs_and_never_deletes_the_installed_database() {
    let base = base();
    let files = ops().build_files(&base, true);
    let configuration = &files["pacman.conf"];
    assert!(
        configuration.contains("SigLevel = Never"),
        "{configuration}"
    );
    assert!(
        configuration.contains("Architecture = x86_64"),
        "{configuration}"
    );
    for repository in &base.repositories {
        assert!(
            configuration.contains(&format!(
                "[{}]\nServer = {}\n",
                repository.name, repository.url
            )),
            "{configuration}"
        );
        assert!(
            files["mirrorlist"].contains(&format!("Server = {}\n", repository.url)),
            "the mirror list lists the same URLs"
        );
    }
    let build = &files["Containerfile"];
    // The install is one invocation over every staged file at once, from the mount alone.
    assert_eq!(
        build.matches("--noconfirm").count(),
        1,
        "one install command: {build}"
    );
    assert!(build.contains(ops().package_mount()), "{build}");
    // The trim, and the database the read-back reads, which is never removed.
    let kept = "/var/lib/pacman/local";
    assert!(!build.contains(kept), "the build must not touch {kept}");
    for trimmed in [
        "/var/cache/pacman/pkg/*",
        "/var/log/pacman.log",
        "/root/.cache",
        "/tmp/*",
        ": > /etc/machine-id",
    ] {
        assert!(build.contains(trimmed), "{trimmed} is not trimmed: {build}");
    }
    // The archive's one top-level directory becomes the root with a copy stage, so no program
    // is run inside the imported image.
    let subdir = base.rootfs.subdir.clone().unwrap();
    assert!(
        build.contains(&format!("COPY --from=bootstrap /{subdir}/ /")),
        "{build}"
    );
    // Neither the key-management program nor a database refresh is generated anywhere.
    for forbidden in ["pacman-key", "-Sy", "pacman -S "] {
        for text in files.values() {
            assert!(!text.contains(forbidden), "`{forbidden}` in {text}");
        }
    }
}

/// The whole of `src/`, one path and one line at a time — the lines that **run**.
///
/// Doc comments and the `#[cfg(test)]` module at the foot of a file are left out. A rule about
/// what Lodi does is a rule about the code, and a backend that must document the command it
/// refuses to emit cannot do that without writing the command down. What the tests assert is
/// covered by the companion check below, which asks the backend itself rather than its text.
fn source_lines() -> Vec<(PathBuf, usize, String)> {
    let mut out = Vec::new();
    let mut queue = vec![PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/src"))];
    while let Some(directory) = queue.pop() {
        for entry in fs::read_dir(&directory).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                queue.push(path);
            } else if path.extension().is_some_and(|e| e == "rs") {
                for (number, line) in fs::read_to_string(&path).unwrap().lines().enumerate() {
                    if line.starts_with("#[cfg(test)]") {
                        break;
                    }
                    if line.trim_start().starts_with("//") {
                        continue;
                    }
                    out.push((path.clone(), number + 1, line.to_string()));
                }
            }
        }
    }
    out
}

/// A12 and A14, as a check rather than a claim: the key-management program and a bare database
/// refresh appear **nowhere** in the code, and the one string that reads like one is the
/// unrelated hint that tells a user how to install Podman on an Arch host. The one exception is
/// `hostscope/pin/keyring.rs`, the opt-in of #170, which runs `pacman-key` on a private keyring
/// below the pin stage and never on the machine's own (the fake refuses it without `--gpgdir`).
///
/// M-0.6 T-5 gave Arch a package backend, so `pacman` is now a program Lodi really runs and the
/// text of that backend has to name the commands it refuses to emit. The load-bearing check is
/// therefore no longer textual: `hostscope::pm::pacman`'s own
/// `the_backend_never_syncs_alone_collects_orphans_or_touches_a_key` builds **every** argv that
/// backend can produce, in both modes, and reads each one. This check keeps the rest of `src/`
/// honest, which is what it was for.
#[test]
fn nothing_in_the_source_tree_refreshes_a_database_or_manages_a_key() {
    let mut unexpected = Vec::new();
    for (path, number, line) in source_lines() {
        for forbidden in ["pacman-key", "pacman -Sy", "pacman -S "] {
            if !line.contains(forbidden) {
                continue;
            }
            let name = path.file_name().unwrap().to_string_lossy().to_string();
            let hint = name == "container.rs" && line.contains("sudo pacman -S podman");
            let private = name == "keyring.rs" && forbidden == "pacman-key";
            if !hint && !private {
                unexpected.push(format!("{name}:{number}: {}", line.trim()));
            }
        }
    }
    assert!(unexpected.is_empty(), "{unexpected:?}");
    // The one permitted occurrence is really there, so this test cannot pass by finding nothing.
    assert_eq!(
        source_lines()
            .iter()
            .filter(|(_, _, line)| line.contains("sudo pacman -S podman"))
            .count(),
        1
    );
}

#[test]
fn the_read_back_commands_are_the_committed_ones() {
    let tag = "localhost/lodi-env:0123456789abcdef";
    let arguments = ops().closure_query_arguments(tag);
    assert_eq!(arguments.join("\n") + "\n", fixture("build/read-back.txt"));
    let recorded = ops().recorded_base_arguments(tag).expect(
        "this family's rootfs publishes no package list, so its build records one in the image",
    );
    assert_eq!(
        recorded.join("\n") + "\n",
        fixture("build/read-back-recorded-base.txt")
    );
    for arguments in [&arguments, &recorded] {
        assert!(arguments.contains(&"--network=none"), "{arguments:?}");
        assert!(arguments.contains(&"--pull=never"), "{arguments:?}");
    }
    // The file the second command reads is the file the generated build writes.
    let path = *recorded.last().unwrap();
    assert!(
        ops().build_files(&base(), true)["Containerfile"].contains(&format!("> {path}")),
        "the build must write the file the read-back reads"
    );
    // The apt family publishes its own package list, so it records nothing and asks nothing.
    assert!(
        Family::Apt
            .image_ops()
            .recorded_base_arguments(tag)
            .is_none(),
        "a family whose lock names every package needs no recorded base"
    );
}

#[test]
fn the_staged_package_names_are_unique_and_carry_the_suffix_the_build_globs() {
    let names: Vec<String> = [
        ("jq", "1.8.1-1"),
        ("jq", "1.8.1-2"),
        ("oniguruma", "6.9.10-1"),
    ]
    .iter()
    .map(|(name, version)| ops().staged_package_name(name, version))
    .collect();
    for name in &names {
        assert!(name.ends_with(".pkg.tar.zst"), "{name}");
        assert!(!name.contains('/'), "{name}");
    }
    assert_ne!(names[0], names[1], "one version apart is one name apart");
    assert_ne!(names[0], names[2]);
}

// -------------------------------------------------------------------------------------------
// 2. The build itself, against a stand-in for Podman.
// -------------------------------------------------------------------------------------------

/// What the stand-in serves and records.
struct Fake {
    dir: PathBuf,
}

impl Fake {
    /// A stand-in whose state lives in a fresh directory of this test binary's scratch root.
    fn new(case: &str, read_back: &ReadBack) -> Fake {
        let dir = support::scratch(&format!("arch-image-{case}"));
        fs::create_dir_all(dir.join("home")).unwrap();
        fs::create_dir_all(dir.join("bin")).unwrap();
        fs::write(dir.join("read-back"), read_back.installed).unwrap();
        // No file at all when the case has no record: an image that does not carry what the
        // build writes.
        if let Some(text) = read_back.recorded_base {
            fs::write(dir.join("recorded-base"), text).unwrap();
        }
        let program = dir.join("bin/podman");
        fs::write(&program, script(&dir)).unwrap();
        fs::set_permissions(&program, fs::Permissions::from_mode(0o755)).unwrap();
        Fake { dir }
    }

    fn podman(&self) -> Podman {
        Podman::find(Some(self.dir.join("bin").as_os_str())).unwrap()
    }

    fn store(&self) -> Store {
        Store::open(&self.dir.join("home")).unwrap()
    }

    /// Every command the stand-in was given, one per line, arguments separated by spaces.
    fn calls(&self) -> Vec<String> {
        fs::read_to_string(self.dir.join("calls"))
            .unwrap_or_default()
            .lines()
            .map(str::to_string)
            .collect()
    }

    fn called(&self, needle: &str) -> bool {
        self.calls().iter().any(|line| line.contains(needle))
    }

    /// The build context as the build saw it.
    fn context(&self, name: &str) -> String {
        fs::read_to_string(self.dir.join("context").join(name)).unwrap()
    }

    /// The names of the files the package mount held during the build.
    fn staged(&self) -> Vec<String> {
        let mut names: Vec<String> = fs::read_to_string(self.dir.join("staged"))
            .unwrap_or_default()
            .lines()
            .map(str::to_string)
            .collect();
        names.sort();
        names
    }
}

/// The stand-in itself: it answers the handful of Podman commands an image build uses, records
/// every one of them, and keeps the context and the package mount of the build for the test.
fn script(dir: &Path) -> String {
    let d = dir.display();
    format!(
        r#"#!/bin/sh
d='{d}'
printf '%s\n' "$*" >> "$d/calls"
[ "$1" = --events-backend=none ] || exit 96
shift
case "$1" in
image)
	case "$2" in
	exists) [ -f "$d/built" ] || exit 1 ;;
	inspect) echo 'sha256:1111111111111111111111111111111111111111111111111111111111111111' ;;
	*) exit 96 ;;
	esac
	;;
images|ps|untag) : ;;
import) [ -f "$3" ] || [ -f "$4" ] || exit 95 ;;
build)
	for a in "$@"; do
		case "$a" in
		*/context) rm -rf "$d/context"; cp -R "$a" "$d/context" ;;
		*:/lodi-pkgs:ro) ls "${{a%%:*}}" > "$d/staged" ;;
		esac
	done
	touch "$d/built"
	;;
run)
	# The build makes two read-backs of the same image: the installed set, and the base set
	# the build recorded inside the image before installing anything. An image without that
	# record answers the way `cat` would: nothing, and a non-zero status.
	case "$*" in
	*--entrypoint\ cat*) cat "$d/recorded-base" || exit 1 ;;
	*) cat "$d/read-back" ;;
	esac
	;;
rmi) rm -f "$d/built"; touch "$d/removed" ;;
*) echo "unexpected podman command: $*" >&2; exit 96 ;;
esac
exit 0
"#
    )
}

/// The rootfs and package bytes the build fetches, and the base whose hashes name them.
struct Upstream {
    files: BTreeMap<String, Vec<u8>>,
    requests: Mutex<Vec<String>>,
}

impl Fetcher for Upstream {
    fn get(&self, url: &str) -> Result<Vec<u8>, FetchError> {
        self.requests.lock().unwrap().push(url.to_string());
        self.files
            .get(url)
            .cloned()
            .ok_or_else(|| FetchError::Status(url.to_string(), 404))
    }

    fn requests(&self) -> Vec<String> {
        self.requests.lock().unwrap().clone()
    }
}

/// The fixture base with every artifact hash naming synthetic bytes this test serves. The
/// generated files do not depend on a hash, so the golden files above still describe this build;
/// what changes is only which bytes the store verifies.
fn servable() -> (BaseEntry, Upstream) {
    let mut base = base();
    let mut files = BTreeMap::new();
    let rootfs = b"synthetic rootfs bytes; the stand-in never unpacks them".to_vec();
    base.rootfs.sha256 = sha256_tagged(&rootfs);
    base.rootfs.size = Some(rootfs.len() as u64);
    files.insert(base.rootfs.url.clone(), rootfs);
    for package in &mut base.closure.packages {
        if package.origin != "install" {
            continue;
        }
        let bytes = format!("synthetic package file for {}", package.name).into_bytes();
        package.sha256 = Some(sha256_tagged(&bytes));
        package.size = Some(bytes.len() as u64);
        let repository = package.repository.clone().unwrap();
        let url = base
            .repositories
            .iter()
            .find(|r| r.name == repository)
            .map(|r| format!("{}{}", r.url, package.filename.clone().unwrap()))
            .unwrap();
        files.insert(url, bytes);
    }
    base.closure.hash = closure_hash(&base.closure.packages);
    (
        base,
        Upstream {
            files,
            requests: Mutex::new(Vec::new()),
        },
    )
}

/// One `pacman -Qi` record.
fn record(name: &str, version: &str, arch: &str) -> String {
    format!(
        "Name            : {name}\nVersion         : {version}\n\
         Architecture    : {arch}\nDepends On      : None\n\n"
    )
}

/// The `pacman -Qi` output of an image whose installed set is exactly the lock's closure.
fn installed_of(base: &BaseEntry) -> String {
    base.closure
        .packages
        .iter()
        .map(|p| record(&p.name, &p.version, p.arch.as_deref().unwrap_or("any")))
        .collect()
}

/// A read-back of an image that installed exactly the lock's closure into a bootstrap that
/// brought `bootstrap` and nothing else. Both halves are owned by the caller because a
/// [`ReadBack`] borrows them.
fn read_back<'a>(installed: &'a str, bootstrap: &'a str) -> ReadBack<'a> {
    ReadBack {
        installed,
        recorded_base: Some(bootstrap),
    }
}

#[test]
fn a_build_installs_the_locked_files_offline_and_reads_the_closure_back() {
    let (base, upstream) = servable();
    // The bootstrap brought one package the lock does not name; the build recorded it, so it is
    // expected rather than drift.
    let bootstrap = record("filesystem", "2026.09.01-1", "x86_64");
    let installed = format!("{bootstrap}{}", installed_of(&base));
    let fake = Fake::new("built", &read_back(&installed, &bootstrap));
    let store = fake.store();
    let podman = fake.podman();
    let mut report = Report::default();
    let outcome = realize_image(&store, &podman, &upstream, &base, &mut report).unwrap();

    assert!(outcome.built);
    assert_eq!(outcome.meta.identity, image_identity(&base));
    assert_eq!(outcome.meta.closure_hash, base.closure.hash);
    assert!(outcome.meta.complete);
    // Exactly the locked artifacts were fetched: the rootfs and the two packages to install.
    assert_eq!(upstream.requests().len(), 3, "{:?}", upstream.requests());

    // The build ran the generated Containerfile, with no network and the verified package files
    // mounted read-only at the family's mount point.
    let base_image = fake
        .calls()
        .iter()
        .find(|line| line.starts_with("--events-backend=none import"))
        .map(|line| line.rsplit(' ').next().unwrap().to_string())
        .expect("the locked rootfs is imported");
    assert!(
        base_image.starts_with("localhost/lodi-tmp-base:"),
        "{base_image}"
    );
    assert_eq!(
        fake.context("Containerfile"),
        fixture("build/Containerfile").replace("{BASE}", &base_image),
        "the build file in the context is the golden file with the imported base spliced in",
    );
    assert_eq!(fake.context("pacman.conf"), fixture("build/pacman.conf"));
    assert_eq!(fake.context("mirrorlist"), fixture("build/mirrorlist"));
    assert!(fake.called("build --network=none"), "{:?}", fake.calls());
    assert!(fake.called(":/lodi-pkgs:ro"), "{:?}", fake.calls());
    assert!(fake.called("--entrypoint pacman"), "{:?}", fake.calls());
    assert!(fake.called("--entrypoint cat"), "{:?}", fake.calls());
    let staged = fake.staged();
    assert_eq!(staged.len(), 2, "{staged:?}");
    assert!(
        staged.iter().all(|n| n.ends_with(".pkg.tar.zst")),
        "{staged:?}"
    );
    assert!(!fake.dir.join("removed").exists(), "the image was kept");

    // The record is written and a second realization is warm: nothing is imported or built.
    let (_, name) = image_names(&base);
    assert!(store.meta_path(&name).exists());
    let before = fake.calls().len();
    let again = realize_image(&store, &podman, &upstream, &base, &mut report).unwrap();
    assert!(!again.built, "the second realization must be warm");
    assert_eq!(
        upstream.requests().len(),
        3,
        "a warm image downloads nothing"
    );
    let after: Vec<String> = fake.calls().split_off(before);
    assert!(
        after
            .iter()
            .all(|line| line.contains("image exists") || line.contains("image inspect")),
        "{after:?}",
    );
}

#[test]
fn a_closure_that_differs_by_one_package_is_closure_drift_and_the_image_is_removed() {
    let (base, upstream) = servable();
    let mut drifted = format!(
        "{}{}",
        record("filesystem", "2026.09.01-1", "x86_64"),
        installed_of(&base)
    );
    drifted.push_str(&record("tree", "2.2.1-1", "x86_64"));
    let bootstrap = record("filesystem", "2026.09.01-1", "x86_64");
    let fake = Fake::new("drift", &read_back(&drifted, &bootstrap));
    let store = fake.store();
    let mut report = Report::default();
    let error = realize_image(&store, &fake.podman(), &upstream, &base, &mut report).unwrap_err();

    assert_eq!(error.code, "E_CLOSURE_DRIFT");
    assert_eq!(exit_status(error.code), 6);
    let shown = format!("{error}");
    assert!(shown.contains("added: tree 2.2.1-1"), "{shown}");
    assert!(
        fake.dir.join("removed").exists(),
        "the image must be removed"
    );
    let (_, name) = image_names(&base);
    assert!(
        !store.meta_path(&name).exists(),
        "a drifted build records nothing"
    );
}

#[test]
fn a_read_back_line_that_does_not_parse_fails_the_build_naming_the_line() {
    let (base, upstream) = servable();
    let bootstrap = record("filesystem", "2026.09.01-1", "x86_64");
    let broken = format!(
        "error: database is corrupted\n{bootstrap}{}",
        installed_of(&base)
    );
    let fake = Fake::new("broken", &read_back(&broken, &bootstrap));
    let store = fake.store();
    let mut report = Report::default();
    let error = realize_image(&store, &fake.podman(), &upstream, &base, &mut report).unwrap_err();

    assert_eq!(error.code, "E_CLOSURE_DRIFT");
    let shown = format!("{error}");
    assert!(
        shown.contains("error: database is corrupted"),
        "the unreadable line is named: {shown}"
    );
    assert!(fake.dir.join("removed").exists());
}

// -------------------------------------------------------------------------------------------
// 3. Nothing became reachable, and nothing else moved.
// -------------------------------------------------------------------------------------------

/// An image that does not carry the base record the build writes is drift, not an empty base.
///
/// This is the whole reason the record exists: an Arch lock cannot name the ~138 packages the
/// bootstrap brought, so without the record every one of them would read as `added:`. Asking the
/// image and getting nothing must therefore fail the build, never be taken for "the bootstrap
/// brought nothing".
#[test]
fn an_image_without_the_recorded_base_set_is_closure_drift() {
    let (base, upstream) = servable();
    let installed = installed_of(&base);
    let fake = Fake::new(
        "no-record",
        &ReadBack {
            installed: &installed,
            recorded_base: None,
        },
    );
    let store = fake.store();
    let mut report = Report::default();
    let error = realize_image(&store, &fake.podman(), &upstream, &base, &mut report).unwrap_err();

    assert_eq!(error.code, "E_CLOSURE_DRIFT");
    let shown = format!("{error}");
    assert!(shown.contains("/lodi-base-packages"), "{shown}");
    assert!(fake.dir.join("removed").exists());
}

#[test]
fn both_families_answer_both_halves_of_the_seam() {
    // Since T-6 the manifest accepts all three distributions, and every one of them has a
    // lock-time half as well as an image half.
    for distro in ["arch", "debian", "ubuntu"] {
        let release = lodi::manifest::Distro::parse(distro).unwrap().releases()[0];
        let text = format!("[container]\ndistro = \"{distro}\"\nrelease = \"{release}\"\n");
        let manifest = lodi::manifest::parse_project_manifest(&text, "lodi.toml")
            .unwrap_or_else(|e| panic!("{distro}: {e}"));
        assert_eq!(
            manifest.container.unwrap().distro.name(),
            distro,
            "the distribution written is the distribution parsed"
        );
    }
    assert!(Family::Pacman.ops().is_ok());
    assert!(Family::Apt.ops().is_ok());
    assert_eq!(Family::Pacman.image_ops().package_mount(), "/lodi-pkgs");
    assert_eq!(Family::Apt.image_ops().package_mount(), "/lodi-debs");
}
