//! `signed_by_url`: a declared source's keyring by HTTPS URL (LD-366, S12).
//!
//! The plan never fetches; the apply fetches every keyring it needs through `src/fetch.rs`'s one
//! entry point, checks its digest (S5) and its framing (S4) — `sources::verify`, the one check a
//! keyring by path passes too — before the journal's first mutation, and writes nothing at all on
//! any failure. A keyring already at the managed path with the declared digest is never fetched
//! again.
//!
//! Every fetch here is a real HTTP exchange with a loopback server this file runs for the length
//! of one test (`Server`, stopped and joined on drop), reached through `LODI_FETCH_REWRITE` — the
//! product's own documented mirror seam — so the URL in the manifest is an `https://` one and the
//! bytes come over a socket. The `lodi` binary is run for the plan (`lodi switch --host
//! --dry-run`), the apply (`lodi switch --host`) and every failure a flag can reach, against a
//! fake machine (`tests/support/fakehost.rs`, LD-514, LD-522); the one case that needs time
//! limits shorter than `lodi`'s own (a server that never answers) drives the same apply in
//! process through `hostscope::apply_with` with a real `HttpFetcher` built with short limits.
//! Scratch roots only (`AGENTS.md` §8): every host command carries `--root`, under
//! `LODI_HOST_REQUIRE_ROOT=1`. The keyrings are generated byte strings
//! that pass or fail the S4 framing check; no real vendor key is anywhere in this file.

#[path = "support/fakehost.rs"]
mod fakehost;
#[path = "support/hostroot.rs"]
mod hostroot;
/// The suite's one wait ceiling, declared once at this binary's root (`tests/support/wait.rs`).
#[path = "support/wait.rs"]
mod wait;

mod support;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Output;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Arc, Once};
use std::thread::JoinHandle;
use std::time::{Duration, Instant};

use hostroot::{Root, journals};
use lodi::fetch::{FetchTimeouts, HttpFetcher, Retry, Rewrite, Waiter};
use lodi::hostscope::manifest::{Context, HostManifest, parse as parse_host};
use lodi::hostscope::sources::{self, Format, Refusal};
use lodi::manifest::ManifestErrors;
use lodi::util::sha256_hex;

/// The host every keyring URL in this file names; the rewrite sends it to the loopback server.
const KEYS: &str = "https://keys.example.invalid/";

// ------------------------------------------------------------------ generated keyrings ---

/// One new-format OpenPGP packet: the tag, a one-octet length, and `body`.
fn packet(tag: u8, body: &[u8]) -> Vec<u8> {
    assert!(body.len() < 192);
    let mut out = vec![0xc0 | tag, body.len() as u8];
    out.extend_from_slice(body);
    out
}

/// A binary public keyring as far as framing goes: a public-key packet (tag 6) and a user id
/// (tag 13). The key material is invented; nothing reads it.
fn public_binary() -> Vec<u8> {
    let mut out = packet(6, b"\x04invented public key material");
    out.extend(packet(13, b"invented test key"));
    out
}

fn public_armored() -> Vec<u8> {
    b"-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nbW9ja2VkIGtleQ==\n=AAAA\n-----END PGP PUBLIC KEY BLOCK-----\n"
        .to_vec()
}

fn public_then_secret() -> Vec<u8> {
    let mut out = public_binary();
    out.extend(packet(5, b"\x04invented secret key material"));
    out
}

fn armored_then_private() -> Vec<u8> {
    let mut out = public_armored();
    out.extend_from_slice(
        b"-----BEGIN PGP PRIVATE KEY BLOCK-----\n\nc2VjcmV0\n-----END PGP PRIVATE KEY BLOCK-----\n",
    );
    out
}

// ---------------------------------------------------------------- the loopback server ---

/// What the server answers for one path.
#[derive(Clone)]
enum Reply {
    Body(u16, Vec<u8>),
    Redirect(String),
    /// Read the request, then answer nothing until the server stops.
    Stall,
}

/// An HTTP/1.1 server on 127.0.0.1 for one test: it counts every connection, answers each path
/// from its table, and is stopped and joined when dropped. Its accept loop is bounded by that
/// stop flag and a test-length deadline, so nothing it starts outlives the test.
struct Server {
    port: u16,
    connections: Arc<AtomicUsize>,
    stop: Arc<AtomicBool>,
    thread: Option<JoinHandle<()>>,
}

impl Server {
    fn start(routes: &[(&str, Reply)]) -> Server {
        let listener = TcpListener::bind("127.0.0.1:0").expect("a loopback port");
        listener.set_nonblocking(true).expect("nonblocking accept");
        let port = listener.local_addr().expect("the port").port();
        let connections = Arc::new(AtomicUsize::new(0));
        let stop = Arc::new(AtomicBool::new(false));
        let routes: BTreeMap<String, Reply> = routes
            .iter()
            .map(|(path, reply)| ((*path).to_string(), reply.clone()))
            .collect();
        let thread = {
            let (connections, stop) = (connections.clone(), stop.clone());
            std::thread::spawn(move || {
                let deadline = Instant::now() + Duration::from_secs(120);
                while !stop.load(Ordering::SeqCst) && Instant::now() < deadline {
                    match listener.accept() {
                        Ok((stream, _)) => {
                            connections.fetch_add(1, Ordering::SeqCst);
                            serve(stream, &routes, &stop);
                        }
                        Err(_) => std::thread::sleep(Duration::from_millis(5)),
                    }
                }
            })
        };
        Server {
            port,
            connections,
            stop,
            thread: Some(thread),
        }
    }

    fn rewrite(&self) -> String {
        format!("{KEYS}=http://127.0.0.1:{}/", self.port)
    }

    fn connections(&self) -> usize {
        self.connections.load(Ordering::SeqCst)
    }
}

impl Drop for Server {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::SeqCst);
        if let Some(thread) = self.thread.take() {
            let _ = thread.join();
        }
    }
}

fn serve(mut stream: TcpStream, routes: &BTreeMap<String, Reply>, stop: &AtomicBool) {
    let _ = stream.set_nonblocking(false);
    let _ = stream.set_read_timeout(Some(Duration::from_secs(5)));
    let mut request = Vec::new();
    let mut buf = [0u8; 1024];
    while !request.windows(4).any(|w| w == b"\r\n\r\n") {
        match stream.read(&mut buf) {
            Ok(0) | Err(_) => return,
            Ok(n) => request.extend_from_slice(&buf[..n]),
        }
    }
    let text = String::from_utf8_lossy(&request);
    let path = text.split_whitespace().nth(1).unwrap_or("/").to_string();
    let reply = routes
        .get(&path)
        .cloned()
        .unwrap_or(Reply::Body(404, b"not here\n".to_vec()));
    let (status, headers, body) = match reply {
        Reply::Body(status, body) => (status, String::new(), body),
        Reply::Redirect(to) => (302, format!("Location: {to}\r\n"), Vec::new()),
        Reply::Stall => {
            let until = Instant::now() + Duration::from_secs(30);
            while !stop.load(Ordering::SeqCst) && Instant::now() < until {
                std::thread::sleep(Duration::from_millis(10));
            }
            return;
        }
    };
    let head = format!(
        "HTTP/1.1 {status} X\r\nContent-Length: {}\r\n{headers}Connection: close\r\n\r\n",
        body.len()
    );
    let _ = stream.write_all(head.as_bytes());
    let _ = stream.write_all(&body);
}

// ----------------------------------------------------------------------- the scratch ---

/// Shims for every program the apt backend reaches for, first on `PATH`: nothing installed, no
/// candidate, a refresh that "runs". No package manager runs here.
fn shims() -> PathBuf {
    static SETUP: Once = Once::new();
    static DIR: std::sync::OnceLock<PathBuf> = std::sync::OnceLock::new();
    let dir = DIR
        .get_or_init(|| support::scratch("sources-fetch-shims"))
        .clone();
    SETUP.call_once(|| {
        hostroot::shims();
        for (name, body) in [
            ("apt-get", "exit 0\n"),
            ("dpkg", "exit 0\n"),
            ("dpkg-query", "exit 0\n"),
            ("apt-mark", "exit 0\n"),
            // Fedora's two programs, for the one Fedora case: nothing reaches them there.
            ("dnf5", "exit 0\n"),
            ("rpm", "exit 0\n"),
            (
                "apt-cache",
                "case \"$1\" in\npolicy) shift; for n in \"$@\"; do printf '%s:\\n  Installed: (none)\\n  Candidate: (none)\\n' \"$n\"; done ;;\nesac\nexit 0\n",
            ),
        ] {
            let path = dir.join(name);
            fs::write(
                &path,
                format!(
                    "#!/bin/sh\n# A test-owned shim of tests/host_sources_fetch.rs. No package manager runs here.\n{body}"
                ),
            )
            .expect("a shim");
            fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).expect("a shim mode");
        }
        let existing = std::env::var("PATH").unwrap_or_default();
        // SAFETY: every `PATH` access in this binary happens after this `Once` completes.
        unsafe { std::env::set_var("PATH", format!("{}:{existing}", dir.display())) };
    });
    dir
}

/// `[sources.docker]` with its keyring by URL.
fn by_url(path: &str, sha: &str) -> String {
    format!(
        "[sources.docker]\n\
         uris = [\"https://download.docker.com/linux/debian\"]\n\
         suites = [\"${{host.codename}}\"]\n\
         components = [\"stable\"]\n\
         signed_by_url = \"{KEYS}{path}\"\n\
         signed_by_sha256 = \"{sha}\"\n"
    )
}

/// `[sources.other]`, a valid source with its keyring beside the manifest.
fn by_path(sha: &str) -> String {
    format!(
        "[sources.other]\n\
         uris = [\"https://packages.example.invalid/debian\"]\n\
         suites = [\"bookworm\"]\n\
         components = [\"main\"]\n\
         signed_by = \"files/other.gpg\"\n\
         signed_by_sha256 = \"{sha}\"\n"
    )
}

/// A Debian machine whose config's `host.toml` is `manifest`, with the keyring `[sources.other]`
/// names beside it and a fresh index, so that only a changing source makes a plan refresh it.
fn armed(name: &str, manifest: &str) -> fakehost::Case {
    let case = fakehost::Case::new(name, fakehost::Machine::debian());
    case.set_manifest(manifest);
    case.write_beside("files/other.gpg", public_binary());
    settled(&case, "debian", "bookworm", manifest);
    case
}

/// `case` as lodi's first switch of it leaves it, before anything below is asked: the may-manage
/// marker in place, and the config's `lodi.lock` recording each `signed_by_url` key of `manifest`
/// by its declared digest. A switch fetches a key the lock does not record to record it (#702's
/// lock); one it records is fetched only by the apply that writes it, which is what this file
/// is about.
fn settled(case: &fakehost::Case, distro: &str, release: &str, manifest: &str) {
    case.root
        .write("etc/lodi/may-manage", "")
        .chmod("etc/lodi/may-manage", 0o644);
    let mut keys = BTreeMap::new();
    let (mut source, mut by_url) = (None, false);
    for line in manifest.lines() {
        if let Some(name) = line.strip_prefix("[sources.") {
            source = Some(name.trim_end_matches(']').to_string());
            by_url = false;
        } else if line.starts_with("signed_by_url = ") {
            by_url = true;
        } else if let Some(sha) = line.strip_prefix("signed_by_sha256 = ")
            && by_url
            && let Some(name) = &source
        {
            keys.insert(name.clone(), format!("sha256:{}", sha.trim_matches('"')));
        }
    }
    let mut lock = lodi::config::lock::Lock::default();
    lock.hosts.insert(
        "host.toml".to_string(),
        lodi::config::lock::HostSection {
            distro: distro.into(),
            release: release.into(),
            arch: "x86_64".into(),
            snapshot: None,
            pins: BTreeMap::new(),
            keys,
        },
    );
    let file = case.config().join("lodi.lock");
    fs::write(&file, lock.render()).expect("lodi.lock");
    fs::set_permissions(&file, fs::Permissions::from_mode(0o644)).expect("its mode");
}

/// An armed Debian root with `manifest` in place (`etc/lodi/host.toml`) and the keyring
/// `[sources.other]` names beside it, for the one case driven in process.
fn armed_in_place(name: &str, manifest: &str) -> Root {
    shims();
    let root = Root::new(name);
    root.debian_with(manifest);
    fs::create_dir_all(root.path("etc/lodi/files")).expect("the files directory");
    fs::write(root.path("etc/lodi/files/other.gpg"), public_binary()).expect("the keyring");
    root.write("var/lib/apt/lists/recorded_Packages", "recorded index\n");
    root
}

/// Everything below `dir`, as relative paths with a digest for each file.
fn tree(dir: &Path) -> BTreeMap<String, Option<String>> {
    let mut out = BTreeMap::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(next) = stack.pop() {
        let Ok(entries) = fs::read_dir(&next) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let mut rel = path
                .strip_prefix(dir)
                .expect("below the root")
                .display()
                .to_string();
            // A journal is named by its time and a random id; its place is what is compared.
            if let Some(name) = rel.strip_prefix("var/lib/lodi/host/journal/") {
                rel = format!("var/lib/lodi/host/journal/<{}>", name.len());
            }
            // A switch logs every run, as the person, whatever it did: not a cache.
            if rel.contains("lodi/logs") || rel == "xdg-state/lodi" {
                continue;
            }
            let meta = fs::symlink_metadata(&path).expect("metadata");
            if meta.is_dir() {
                stack.push(path);
                out.insert(rel, None);
            } else {
                out.insert(rel, Some(sha256_hex(&fs::read(&path).unwrap_or_default())));
            }
        }
    }
    out
}

/// The scratch directories a `lodi` child is given for its store, its home and its temporary
/// files, so that anything it cached anywhere would show.
struct Elsewhere {
    dir: PathBuf,
}

impl Elsewhere {
    fn new(name: &str) -> Elsewhere {
        let dir = support::scratch(&format!("fetch-elsewhere-{name}"));
        for sub in ["store", "home", "tmp", "xdg-cache", "xdg-data", "xdg-state"] {
            fs::create_dir_all(dir.join(sub)).expect("a scratch directory");
        }
        Elsewhere { dir }
    }
}

impl Drop for Elsewhere {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.dir);
    }
}

/// A 1.x host verb's name, run as the 2.0 command that keeps it (`fakehost::Case::verb_env`:
/// `plan` is `switch --host --dry-run`, `apply` is `switch --host`) with `--root ROOT`, the
/// server's rewrite ahead of the fake's offline archive, one attempt, and every place a cache
/// could hide pointed into `elsewhere`.
fn lodi(verb: &str, case: &fakehost::Case, server: &Server, elsewhere: &Elsewhere) -> Output {
    lodi_with(verb, &[], case, server, elsewhere)
}

/// [`lodi`] with `extra` arguments.
fn lodi_with(
    verb: &str,
    extra: &[&str],
    case: &fakehost::Case,
    server: &Server,
    elsewhere: &Elsewhere,
) -> Output {
    let e = &elsewhere.dir;
    let rewrite = format!("{};{}", server.rewrite(), case.archive_server.rewrite());
    let path = |sub: &str| e.join(sub).display().to_string();
    case.verb_env(
        verb,
        extra,
        &[
            ("LODI_FETCH_REWRITE", &rewrite),
            ("LODI_HOME", &path("store")),
            ("TMPDIR", &path("tmp")),
            ("XDG_CACHE_HOME", &path("xdg-cache")),
            ("XDG_DATA_HOME", &path("xdg-data")),
            ("XDG_STATE_HOME", &path("xdg-state")),
        ],
    )
}

fn text(output: &Output) -> String {
    format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    )
}

// ------------------------------------------------------------------------- the manifest ---

fn context() -> Context {
    Context {
        arch: "x86_64".into(),
        os: "linux".into(),
        distro: "debian".into(),
        release: "12".into(),
        codename: "bookworm".into(),
        lodi_version: env!("CARGO_PKG_VERSION").into(),
    }
}

fn parse(text: &str) -> HostManifest {
    match parse_host(text, "host.toml", &context()) {
        Ok(manifest) => manifest,
        Err(errors) => panic!("expected a valid manifest, got:\n{errors}"),
    }
}

#[track_caller]
fn rejects(text: &str, code: &'static str) -> ManifestErrors {
    let errors = match parse_host(text, "host.toml", &context()) {
        Ok(_) => panic!("expected {code}, the manifest parsed"),
        Err(errors) => errors,
    };
    assert!(
        errors.codes().contains(&code),
        "expected {code}, got {:?}:\n{errors}",
        errors.codes()
    );
    errors
}

/// `[sources.docker]` with `line` in place of its keyring line.
fn keyed(line: &str) -> String {
    format!(
        "[vars]\nscheme = \"http\"\n\n[sources.docker]\n\
         uris = [\"https://download.docker.com/linux/debian\"]\n\
         suites = [\"bookworm\"]\n\
         components = [\"stable\"]\n\
         {line}\n\
         signed_by_sha256 = \"{}\"\n",
        "a".repeat(64)
    )
}

#[test]
fn signed_by_url_is_https_without_user_information_and_exactly_one_keyring_is_named() {
    let manifest = parse(&keyed(&format!("signed_by_url = \"{KEYS}docker.gpg\"")));
    let entry = &manifest.sources["docker"];
    assert_eq!(
        entry.signed_by_url.as_deref(),
        Some("https://keys.example.invalid/docker.gpg")
    );
    assert_eq!(entry.signed_by, "");

    for (url, code) in [
        ("http://keys.example.invalid/docker.gpg", "E_INSECURE_URL"),
        (
            "${vars.scheme}://keys.example.invalid/docker.gpg",
            "E_INSECURE_URL",
        ),
        ("ftp://keys.example.invalid/docker.gpg", "E_INSECURE_URL"),
        ("file:///etc/apt/keyrings/docker.gpg", "E_INSECURE_URL"),
        ("keys.example.invalid/docker.gpg", "E_INSECURE_URL"),
        ("https:///docker.gpg", "E_INSECURE_URL"),
        ("https://keys.example.invalid/docker.gpg?v=1", "E_TYPE"),
        ("https://keys.example.invalid/docker.gpg#key", "E_TYPE"),
        ("https://keys.example.invalid/a b", "E_TYPE"),
        ("", "E_TYPE"),
    ] {
        let errors = rejects(&keyed(&format!("signed_by_url = \"{url}\"")), code);
        let shown = errors.to_string();
        assert!(
            shown.contains("`signed_by_url` in [sources.docker]"),
            "{shown}"
        );
    }

    // Credentials are refused by name, and never repeated.
    for url in [
        "https://user@192.0.2.1/docker.gpg",
        "https://user:hunter2-password@192.0.2.1/docker.gpg",
    ] {
        let errors = rejects(
            &keyed(&format!("signed_by_url = \"{url}\"")),
            "E_INSECURE_URL",
        );
        let shown = errors.to_string();
        assert!(shown.contains("user information"), "{shown}");
        assert!(!shown.contains("hunter2"), "{shown}");
        assert!(!shown.contains("user@"), "{shown}");
    }

    // Both, or neither, is a conflict.
    let both = keyed(&format!(
        "signed_by = \"files/docker.gpg\"\nsigned_by_url = \"{KEYS}docker.gpg\""
    ));
    let shown = rejects(&both, "E_ATTR_CONFLICT").to_string();
    assert!(
        shown.contains("both of `signed_by` and `signed_by_url`"),
        "{shown}"
    );
    let shown = rejects(&keyed(""), "E_ATTR_CONFLICT").to_string();
    assert!(
        shown.contains("declares no `signed_by` and no `signed_by_url`"),
        "{shown}"
    );
}

#[test]
fn the_framing_check_names_a_public_keyring_and_refuses_everything_else() {
    assert_eq!(sources::sniff(&public_binary()), Ok(Format::Binary));
    assert_eq!(sources::sniff(&public_armored()), Ok(Format::Armored));
    // Two public keys are a keyring apt trusts every key of.
    let mut two = public_binary();
    two.extend(public_binary());
    assert_eq!(sources::sniff(&two), Ok(Format::Binary));
    // An old-format header (tag 6, two-octet length) frames a key too.
    let mut old = vec![0x99, 0x00, 0x05];
    old.extend_from_slice(b"\x04abcd");
    assert_eq!(sources::sniff(&old), Ok(Format::Binary));

    assert_eq!(sources::sniff(&public_then_secret()), Err(Refusal::Secret));
    assert_eq!(
        sources::sniff(&armored_then_private()),
        Err(Refusal::Secret)
    );
    assert_eq!(
        sources::sniff(&packet(7, b"\x04secret subkey")),
        Err(Refusal::Secret)
    );
    let mut truncated = public_binary();
    truncated.truncate(truncated.len() - 3);
    for refused in [
        Vec::new(),
        truncated,
        b"<!doctype html><html><body>404</body></html>\n".to_vec(),
        b"just some text\n".to_vec(),
        packet(13, b"a user id first"),
    ] {
        assert_eq!(sources::sniff(&refused), Err(Refusal::NotKeyring));
    }
}

// ---------------------------------------------------------------------- plan and apply ---

#[test]
fn plan_never_fetches_and_apply_fetches_once_then_never_again() {
    let key = public_binary();
    let server = Server::start(&[("/docker.gpg", Reply::Body(200, key.clone()))]);
    let elsewhere = Elsewhere::new("once");
    let manifest = format!(
        "{}[packages]\ncommon = [\"docker-ce\"]\n",
        by_url("docker.gpg", &sha256_hex(&key))
    );
    let case = armed("fetch-once", &manifest);

    // The plan: the keyring is to be fetched, the refresh is forced, and nothing is asked of
    // the network — not one connection reaches the listener.
    let before = tree(&case.root.dir);
    let plan = lodi("plan", &case, &server, &elsewhere);
    assert!(plan.status.success(), "{}", text(&plan));
    let out = text(&plan);
    let lines: Vec<&str> = out.lines().collect();
    assert_eq!(
        lines[0], "+ source docker (keyring: fetch, sources)",
        "{out}"
    );
    assert!(lines[1].starts_with("~ index (apt-get update"), "{out}");
    // Core's rule: a package the refresh may bring is deferred until after it (LD-365).
    assert_eq!(
        lines[2], "+ package docker-ce (deferred: after the source refresh)",
        "{out}"
    );
    assert_eq!(server.connections(), 0, "plan made a request");
    assert_eq!(tree(&case.root.dir), before, "plan wrote something");

    // The apply fetches it once, and writes it where its framing says. (The shims' index never
    // offers `docker-ce`, so the package half is left out of this apply.)
    case.set_manifest(&by_url("docker.gpg", &sha256_hex(&key)));
    let apply = lodi("apply", &case, &server, &elsewhere);
    assert!(apply.status.success(), "{}", text(&apply));
    assert_eq!(server.connections(), 1);
    assert_eq!(
        fs::read(case.root.path("etc/apt/keyrings/lodi-docker.gpg")).unwrap(),
        key
    );
    assert!(
        case.root
            .read("etc/apt/sources.list.d/lodi-docker.sources")
            .ends_with("Signed-By: /etc/apt/keyrings/lodi-docker.gpg\n")
    );
    let lock = case.root.read("etc/lodi/host.lock");
    assert!(lock.contains("/etc/apt/keyrings/lodi-docker.gpg"), "{lock}");

    // From now on the file at the managed path is the keyring: neither plan nor apply asks.
    let plan = lodi("plan", &case, &server, &elsewhere);
    assert!(plan.status.success(), "{}", text(&plan));
    assert!(fakehost::nothing(&plan), "{}", text(&plan));
    let settled = tree(&case.root.dir);
    let again = lodi("apply", &case, &server, &elsewhere);
    assert!(again.status.success(), "{}", text(&again));
    assert!(fakehost::nothing(&again), "{}", text(&again));
    assert_eq!(
        server.connections(),
        1,
        "a verified keyring was fetched again"
    );
    assert_eq!(
        tree(&case.root.dir),
        settled,
        "a converged apply wrote something"
    );
}

#[test]
fn an_armored_keyring_by_url_is_written_as_asc() {
    let key = public_armored();
    let server = Server::start(&[("/docker.asc", Reply::Body(200, key.clone()))]);
    let elsewhere = Elsewhere::new("armored");
    let case = armed("fetch-armored", &by_url("docker.asc", &sha256_hex(&key)));
    let apply = lodi("apply", &case, &server, &elsewhere);
    assert!(apply.status.success(), "{}", text(&apply));
    assert_eq!(
        fs::read(case.root.path("etc/apt/keyrings/lodi-docker.asc")).unwrap(),
        key
    );
    assert!(!case.root.exists("etc/apt/keyrings/lodi-docker.gpg"));
    assert!(
        case.root
            .read("etc/apt/sources.list.d/lodi-docker.sources")
            .ends_with("Signed-By: /etc/apt/keyrings/lodi-docker.asc\n")
    );
    let plan = lodi("plan", &case, &server, &elsewhere);
    assert!(fakehost::nothing(&plan), "{}", text(&plan));
    assert_eq!(server.connections(), 1);
}

/// On Fedora 44 (LD-433) the same fetch refuses a keyring URL that redirects to plain HTTP, and
/// neither the `.repo` file nor the key is written.
#[test]
fn fedora_a_keyring_url_redirected_to_http_is_refused_with_nothing_written() {
    let key = public_armored();
    let server = Server::start(&[(
        "/moved.asc",
        Reply::Redirect("http://keys.example.invalid/vendor.asc".into()),
    )]);
    let case = fakehost::Case::new("fetch-fedora-redirect", fakehost::Machine::fedora());
    let manifest = format!(
        "[host]\nversion = \"1\"\ndistro = \"fedora\"\n\n[sources.vendor]\n\
         uris = [\"https://vendor.example.invalid/f44/\"]\n\
         signed_by_url = \"{KEYS}moved.asc\"\nsigned_by_sha256 = \"{}\"\n",
        sha256_hex(&key)
    );
    case.set_manifest(&manifest);
    settled(&case, "fedora", "44", &manifest);
    let elsewhere = Elsewhere::new("fedora-redirect");
    let plan = lodi("plan", &case, &server, &elsewhere);
    assert!(
        text(&plan).starts_with("+ source vendor (key: fetch, repo)\n"),
        "{}",
        text(&plan)
    );
    let before = tree(&case.root.dir);
    let apply = lodi("apply", &case, &server, &elsewhere);
    let out = text(&apply);
    assert_eq!(apply.status.code(), Some(5), "{out}");
    assert!(
        out.contains("E_INSECURE_URL") && out.contains("[sources.vendor]"),
        "{out}"
    );
    assert_eq!(tree(&case.root.dir), before, "nothing was written");
    assert!(!case.root.exists("etc/yum.repos.d/lodi-vendor.repo"));
    assert!(!case.root.exists("etc/pki/rpm-gpg/lodi-vendor.asc"));
}

/// An HTML page where a keyring should be. It declares its own digest in the tests below, so that
/// the framing check (which follows the digest check) is what refuses it.
const PAGE: &[u8] = b"<!doctype html><title>keys</title>\n";

/// Every failure of the fetch ends the apply with its code and nothing written anywhere — also
/// when the manifest's other source is valid and was planned first.
#[test]
fn every_fetch_failure_ends_the_apply_with_nothing_written() {
    let key = public_binary();
    let sha = sha256_hex(&key);
    let big = {
        let mut big = public_binary();
        big.resize(sources::MAX_KEYRING_BYTES + 1, 0);
        big
    };
    let server = Server::start(&[
        ("/gone.gpg", Reply::Body(404, b"no such key\n".to_vec())),
        ("/big.gpg", Reply::Body(200, big.clone())),
        ("/rotated.gpg", Reply::Body(200, public_armored())),
        ("/secret.gpg", Reply::Body(200, public_then_secret())),
        ("/private.asc", Reply::Body(200, armored_then_private())),
        ("/page.gpg", Reply::Body(200, PAGE.to_vec())),
        (
            "/moved.gpg",
            Reply::Redirect("http://keys.example.invalid/docker.gpg".into()),
        ),
    ]);
    for (path, digest, code, exit, words) in [
        ("gone.gpg", sha.clone(), "E_FETCH", 5, "HTTP status 404"),
        (
            "big.gpg",
            sha256_hex(&big),
            "E_FETCH",
            5,
            "body larger than 1048576 bytes",
        ),
        (
            "rotated.gpg",
            sha.clone(),
            "E_HASH_MISMATCH",
            5,
            "rotated its signing key",
        ),
        (
            "secret.gpg",
            sha256_hex(&public_then_secret()),
            "E_TYPE",
            3,
            "secret key material",
        ),
        (
            "private.asc",
            sha256_hex(&armored_then_private()),
            "E_TYPE",
            3,
            "secret key material",
        ),
        (
            "page.gpg",
            sha256_hex(PAGE),
            "E_TYPE",
            3,
            "not an OpenPGP public keyring",
        ),
        (
            "moved.gpg",
            sha.clone(),
            "E_INSECURE_URL",
            5,
            "not an HTTPS URL",
        ),
    ] {
        let elsewhere = Elsewhere::new(&format!("fail-{path}"));
        // `other` sorts after `docker`, so a partial apply would have had something to write.
        let manifest = format!("{}\n{}", by_url(path, &digest), by_path(&sha));
        let case = armed(&format!("fetch-fail-{path}"), &manifest);
        let root_before = tree(&case.root.dir);
        let elsewhere_before = tree(&elsewhere.dir);
        let connections = server.connections();

        let apply = lodi("apply", &case, &server, &elsewhere);
        let out = text(&apply);
        assert_eq!(apply.status.code(), Some(exit), "{path}: {out}");
        assert!(out.contains(code), "{path}: expected {code}: {out}");
        assert!(out.contains(words), "{path}: expected {words:?}: {out}");
        assert!(out.contains("[sources.docker]"), "{path}: {out}");
        assert_eq!(server.connections(), connections + 1, "{path}");

        assert_eq!(
            tree(&case.root.dir),
            root_before,
            "{path}: the apply wrote below the root"
        );
        assert_eq!(
            tree(&elsewhere.dir),
            elsewhere_before,
            "{path}: the apply cached something outside the root"
        );
        assert!(journals(&case.root).is_empty(), "{path}");
        // The plan beside it is unchanged by the failure: still a fetch, still no request.
        let plan = lodi("plan", &case, &server, &elsewhere);
        assert!(plan.status.success(), "{path}: {}", text(&plan));
        assert!(
            text(&plan).contains("+ source docker (keyring: fetch, sources)"),
            "{path}: {}",
            text(&plan)
        );
        assert_eq!(
            server.connections(),
            connections + 1,
            "{path}: plan fetched"
        );
    }
}

/// A waiter that never sleeps: the one fetch this is used for is made once.
struct NoWait;

impl Waiter for NoWait {
    fn notice(&self, _line: &str) {}
    fn wait(&self, _d: Duration) {}
    fn random(&self) -> f64 {
        0.0
    }
}

#[test]
fn a_server_that_never_answers_ends_the_apply_with_e_fetch_and_nothing_written() {
    let server = Server::start(&[("/docker.gpg", Reply::Stall)]);
    let key = public_binary();
    let manifest = format!(
        "{}\n{}",
        by_url("docker.gpg", &sha256_hex(&key)),
        by_path(&sha256_hex(&key))
    );
    let root = armed_in_place("fetch-timeout", &manifest);
    let before = tree(&root.dir);
    // `lodi`'s own fetcher with only its limits shortened: 60 s for the headers is `lodi`'s
    // rule, and one second is the same rule, sooner.
    let fetcher = HttpFetcher::with_retry(
        vec![Rewrite {
            prefix: KEYS.into(),
            replacement: format!("http://127.0.0.1:{}/", server.port),
        }],
        FetchTimeouts {
            resolve: Duration::from_secs(5),
            connect: Duration::from_secs(5),
            send: Duration::from_secs(5),
            headers: Duration::from_secs(1),
            stall: Duration::from_secs(1),
            min_rate: 1,
        },
        Retry::ONCE,
        Arc::new(NoWait),
    );
    let started = Instant::now();
    let error = lodi::hostscope::apply_with(&root.options(), Some(&fetcher))
        .expect_err("the server never answers");
    assert!(started.elapsed() < Duration::from_secs(20));
    assert_eq!(error.codes(), vec!["E_FETCH"], "{error}");
    assert_eq!(error.exit_status(), 5);
    assert!(error.to_string().contains("[sources.docker]"), "{error}");
    assert_eq!(server.connections(), 1);
    assert_eq!(tree(&root.dir), before, "the apply wrote below the root");
    assert!(journals(&root).is_empty());
}

/// A passing apply leaves exactly what the same source with its keyring beside the manifest
/// leaves — the two managed files, the lock, the host state — and nothing that could be a cache.
#[test]
fn a_keyring_by_url_leaves_nothing_a_keyring_by_path_does_not() {
    let key = public_binary();
    let sha = sha256_hex(&key);
    let server = Server::start(&[("/docker.gpg", Reply::Body(200, key.clone()))]);

    let elsewhere = Elsewhere::new("shape-url");
    let url_case = armed("fetch-shape-url", &by_url("docker.gpg", &sha));
    let url_before: BTreeSet<String> = tree(&url_case.root.dir).into_keys().collect();
    let apply = lodi("apply", &url_case, &server, &elsewhere);
    assert!(apply.status.success(), "{}", text(&apply));
    let url_added: BTreeSet<String> = tree(&url_case.root.dir)
        .into_keys()
        .filter(|path| !url_before.contains(path))
        .collect();
    assert!(
        tree(&elsewhere.dir).values().all(Option::is_none),
        "a file appeared outside the root: {:?}",
        tree(&elsewhere.dir)
    );

    let path_manifest = by_url("docker.gpg", &sha).replace(
        &format!("signed_by_url = \"{KEYS}docker.gpg\""),
        "signed_by = \"files/docker.gpg\"",
    );
    let path_case = armed("fetch-shape-path", &path_manifest);
    path_case.write_beside("files/docker.gpg", &key);
    let path_before: BTreeSet<String> = tree(&path_case.root.dir).into_keys().collect();
    let apply = lodi("apply", &path_case, &server, &elsewhere);
    assert!(apply.status.success(), "{}", text(&apply));
    let path_added: BTreeSet<String> = tree(&path_case.root.dir)
        .into_keys()
        .filter(|path| !path_before.contains(path))
        .collect();

    assert_eq!(url_added, path_added);
    // Of what the apply wrote, the fetched bytes are in exactly one file: the managed keyring.
    let copies: Vec<String> = tree(&url_case.root.dir)
        .into_iter()
        .filter(|(path, digest)| {
            url_added.contains(path) && digest.as_deref() == Some(sha.as_str())
        })
        .map(|(path, _)| path)
        .collect();
    assert_eq!(copies, vec!["etc/apt/keyrings/lodi-docker.gpg".to_string()]);
    assert_eq!(server.connections(), 1);
}

// ------------------------------------------- the landed core's rules, on the URL path ---
//
// The validator repair of the landed core (PR 115) made four of its rules true for a keyring by
// path: a URI fragment is `E_TYPE` named at its place (S2), a private-key block anywhere in the
// bytes is refused before they are copied (S4), a link above either apt source path is refused
// (S7), and a hand edit of a managed keyring or stanza is `E_DRIFT` until `--overwrite-drift`
// (S10). Each is exercised here on a keyring by URL, through the binary, with the loopback
// server counting every request.

/// S2 for `signed_by_url`: a fragment is `E_TYPE`, named, at the value's file:line:column — on
/// the plan and on the apply, before any request and with nothing written.
#[test]
fn a_fragment_in_signed_by_url_is_e_type_naming_it_at_its_place_before_any_request() {
    let key = public_binary();
    let server = Server::start(&[("/docker.gpg", Reply::Body(200, key.clone()))]);
    let elsewhere = Elsewhere::new("fragment");
    let case = armed(
        "fetch-fragment",
        &by_url("docker.gpg#main", &sha256_hex(&key)),
    );
    let manifest = case.manifest();
    let line = manifest
        .lines()
        .position(|line| line.starts_with("signed_by_url = "))
        .expect("the key's line")
        + 1;
    let before = tree(&case.root.dir);
    for verb in ["plan", "apply"] {
        let output = lodi(verb, &case, &server, &elsewhere);
        let out = text(&output);
        assert_eq!(output.status.code(), Some(3), "{verb}: {out}");
        assert!(out.contains("E_TYPE"), "{verb}: {out}");
        assert!(
            out.contains("carries a fragment (`#main`)"),
            "{verb}: {out}"
        );
        // `signed_by_url = "` is 16 columns: the value starts at the 17th.
        assert!(
            out.contains(&format!("host.toml:{line}:17")),
            "{verb}: {out}"
        );
    }
    assert_eq!(server.connections(), 0, "a request was made");
    assert_eq!(tree(&case.root.dir), before, "something was written");
}

/// S10 for a keyring by URL: a hand edit of the fetched keyring, or of its stanza, is `W_DRIFT`
/// on the plan and `E_DRIFT` (exit 8) on the apply — decided from the lock and the file, before
/// any request, with nothing written — until `--overwrite-drift` puts the declared bytes back.
#[test]
fn a_hand_edit_of_a_keyring_by_url_or_its_stanza_is_e_drift_before_any_request() {
    let key = public_binary();
    let server = Server::start(&[("/docker.gpg", Reply::Body(200, key.clone()))]);
    for (index, path) in [
        "etc/apt/keyrings/lodi-docker.gpg",
        "etc/apt/sources.list.d/lodi-docker.sources",
    ]
    .into_iter()
    .enumerate()
    {
        let elsewhere = Elsewhere::new(&format!("drift-{index}"));
        let case = armed(
            &format!("fetch-drift-{index}"),
            &by_url("docker.gpg", &sha256_hex(&key)),
        );
        let apply = lodi("apply", &case, &server, &elsewhere);
        assert!(apply.status.success(), "{path}: {}", text(&apply));
        let stanza = case.root.read("etc/apt/sources.list.d/lodi-docker.sources");
        let connections = server.connections();

        case.root.write(path, "edited by hand\n");
        let plan = lodi("plan", &case, &server, &elsewhere);
        let out = text(&plan);
        assert!(plan.status.success(), "{path}: {out}");
        assert!(
            out.contains(&format!(
                "W_DRIFT: /{path} was changed since lodi last wrote it"
            )),
            "{path}: {out}"
        );
        assert!(out.contains("~ source docker ("), "{path}: {out}");
        assert_eq!(server.connections(), connections, "{path}: plan fetched");

        let lock = case.root.read("etc/lodi/host.lock");
        let before = tree(&case.root.dir);
        let apply = lodi("apply", &case, &server, &elsewhere);
        let out = text(&apply);
        assert_eq!(apply.status.code(), Some(8), "{path}: {out}");
        assert!(
            out.contains(&format!(
                "E_DRIFT: /{path} of a declared source was changed since lodi last wrote it"
            )),
            "{path}: {out}"
        );
        assert!(out.contains("--overwrite-drift"), "{path}: {out}");
        assert_eq!(
            server.connections(),
            connections,
            "{path}: the apply made a request before it refused the drift"
        );
        assert_eq!(case.root.read(path), "edited by hand\n", "{path}");
        assert_eq!(case.root.read("etc/lodi/host.lock"), lock, "{path}");
        assert_eq!(
            tree(&case.root.dir),
            before,
            "{path}: something was written"
        );

        let apply = lodi_with("apply", &["--overwrite-drift"], &case, &server, &elsewhere);
        assert!(apply.status.success(), "{path}: {}", text(&apply));
        assert_eq!(
            fs::read(case.root.path("etc/apt/keyrings/lodi-docker.gpg")).unwrap(),
            key,
            "{path}"
        );
        assert_eq!(
            case.root.read("etc/apt/sources.list.d/lodi-docker.sources"),
            stanza,
            "{path}"
        );
        // Only the edited keyring had to be fetched again; an edited stanza beside a verified
        // keyring is put back from the file at the managed path.
        let fetched = usize::from(path.ends_with(".gpg"));
        assert_eq!(server.connections(), connections + fetched, "{path}");
    }
}

/// S7 for a keyring by URL: a link above the apt source paths — `/etc/apt` itself — is the same
/// `E_SYNTAX` a keyring by path gets, before any request and with nothing written; also when the
/// fetched keyring is already there behind it.
#[test]
fn a_link_above_the_apt_source_paths_is_e_syntax_for_a_keyring_by_url_before_any_request() {
    let key = public_binary();
    let server = Server::start(&[("/docker.gpg", Reply::Body(200, key.clone()))]);
    for (index, applied_first) in [false, true].into_iter().enumerate() {
        let elsewhere = Elsewhere::new(&format!("parent-link-{index}"));
        let case = armed(
            &format!("fetch-parent-link-{index}"),
            &by_url("docker.gpg", &sha256_hex(&key)),
        );
        if applied_first {
            let apply = lodi("apply", &case, &server, &elsewhere);
            assert!(apply.status.success(), "{}", text(&apply));
        }
        let connections = server.connections();
        // `/etc/apt` becomes a link to a directory elsewhere below the root.
        let apt = case.root.path("etc/apt");
        let moved = case.root.path("elsewhere/apt");
        fs::create_dir_all(case.root.path("elsewhere")).expect("a directory");
        if apt.exists() {
            fs::rename(&apt, &moved).expect("moved aside");
        }
        fs::create_dir_all(moved.join("sources.list.d")).expect("a directory");
        std::os::unix::fs::symlink("../elsewhere/apt", &apt).expect("the link");
        let before = tree(&case.root.dir);
        for verb in ["plan", "apply"] {
            let output = lodi(verb, &case, &server, &elsewhere);
            let out = text(&output);
            assert_eq!(output.status.code(), Some(3), "{index} {verb}: {out}");
            assert!(out.contains("E_SYNTAX"), "{index} {verb}: {out}");
            assert!(
                out.contains("/etc/apt on the way to it is a symbolic link"),
                "{index} {verb}: {out}"
            );
        }
        assert_eq!(
            server.connections(),
            connections,
            "{index}: a request was made"
        );
        assert_eq!(
            tree(&case.root.dir),
            before,
            "{index}: something was written"
        );
    }
}

/// S4 for a keyring by URL: a private-key block's marker mid-line, in bytes whose digest is the
/// declared one, is `E_TYPE` `holds secret key material`; the bytes are neither written nor
/// printed.
#[test]
fn a_private_key_marker_mid_line_in_a_fetched_keyring_is_e_type_and_never_written() {
    let mut bytes = public_armored();
    bytes.extend_from_slice(
        b"comment: SECRET-MATERIAL-XYZ -----BEGIN PGP PRIVATE KEY BLOCK----- SECRET-MATERIAL-XYZ\n",
    );
    let server = Server::start(&[("/docker.asc", Reply::Body(200, bytes.clone()))]);
    let elsewhere = Elsewhere::new("midline");
    let case = armed("fetch-midline", &by_url("docker.asc", &sha256_hex(&bytes)));
    let before = tree(&case.root.dir);

    let plan = lodi("plan", &case, &server, &elsewhere);
    assert!(plan.status.success(), "{}", text(&plan));
    assert!(
        text(&plan).contains("+ source docker (keyring: fetch, sources)"),
        "{}",
        text(&plan)
    );
    assert_eq!(server.connections(), 0, "plan fetched");

    let apply = lodi("apply", &case, &server, &elsewhere);
    let out = text(&apply);
    assert_eq!(apply.status.code(), Some(3), "{out}");
    assert!(out.contains("E_TYPE"), "{out}");
    assert!(out.contains("holds secret key material"), "{out}");
    assert!(out.contains("[sources.docker]"), "{out}");
    assert!(!out.contains("SECRET-MATERIAL"), "{out}");
    assert_eq!(server.connections(), 1);
    assert_eq!(tree(&case.root.dir), before, "something was written");
    assert!(journals(&case.root).is_empty());
}
