//! `[sources.NAME]` (LD-365): a declared third-party apt repository, armed by the apply as one
//! step before the index refresh and the transaction that installs from it. Each rule of the
//! schema and of S1–S11 is a named test here, and the 1.2 compatibility goldens are walked at the
//! end.
//!
//! Offline, deterministic, over scratch roots only (`AGENTS.md` §8). No apt runs here: the
//! package manager is the fake machine of `tests/support/fakepm.py`, behind the real binary, and
//! the interruptions are real applies in a child process held by `tests/support/hostroot.rs`'s
//! [`Hold`] and killed there. Every keyring is a generated byte string that only passes the S4
//! framing sniff; no vendor's key is in this repository.

#[path = "support/compat.rs"]
mod compat;
#[path = "support/fakehost.rs"]
mod fakehost;
#[path = "support/hostroot.rs"]
mod hostroot;
/// The suite's one wait ceiling, declared once at this binary's root (`tests/support/wait.rs`).
#[path = "support/wait.rs"]
mod wait;

mod support;

use std::fs;
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};
use std::process::Command;

use fakehost::{Case, Machine, Pkg, err, out, story};
use hostroot::{Hold, backups, journals, kill};
use lodi::hostscope::journal::{self, Classification};
use lodi::hostscope::manifest::{Context, HostManifest, SourceEntry, parse};
use lodi::hostscope::sources::{self, Format, Refusal, sniff};
use lodi::hostscope::sourceset;
use lodi::util::sha256_hex;

/// The child half of every interruption below: one real apply, in its own process, over the root
/// the parent names. It does nothing at all in the parent's own run.
#[test]
fn child_apply() {
    if !hostroot::is_child() {
        return;
    }
    hostroot::child_apply();
}

// ------------------------------------------------------------------------------- keyrings ---

/// A new-format packet: tag, one-octet length, body.
fn packet(tag: u8, body: &[u8]) -> Vec<u8> {
    assert!(body.len() < 192);
    let mut out = vec![0xC0 | tag, body.len() as u8];
    out.extend_from_slice(body);
    out
}

/// An old-format packet with a two-octet length.
fn old_packet(tag: u8, body: &[u8]) -> Vec<u8> {
    let mut out = vec![0x80 | (tag << 2) | 1];
    out.extend_from_slice(&(body.len() as u16).to_be_bytes());
    out.extend_from_slice(body);
    out
}

/// A binary "public keyring": a public-key packet, a user id, a public subkey. The bodies are
/// invented bytes; only the framing is real.
fn public_key(seed: u8) -> Vec<u8> {
    let mut out = packet(6, &[4, 0, 0, 0, seed, 22, 1, 2, 3]);
    out.extend(packet(13, b"Test Signing Key (generated)"));
    out.extend(old_packet(14, &[4, 0, 0, 0, seed, 22, 9, 9]));
    out
}

const ARMORED: &str = "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\n\
                       bm90IGEga2V5OiBnZW5lcmF0ZWQgZm9yIGEgdGVzdA==\n=AAAA\n\
                       -----END PGP PUBLIC KEY BLOCK-----\n";

fn armored() -> Vec<u8> {
    ARMORED.as_bytes().to_vec()
}

/// A generated armored keyring: the given public block, then a private key block whose marker
/// stands mid-line, after other text on the same line — never a line of its own.
fn midline_private(public: &str) -> Vec<u8> {
    format!(
        "{public}comment: -----BEGIN PGP PRIVATE KEY BLOCK-----\nSECRET-MATERIAL-XYZ\n\
         -----END PGP PRIVATE KEY BLOCK-----\n"
    )
    .into_bytes()
}

fn sha(bytes: &[u8]) -> String {
    sha256_hex(bytes)
}

// ------------------------------------------------------------------------------- manifests ---

fn context() -> Context {
    Context {
        arch: "x86_64".into(),
        os: "linux".into(),
        distro: "debian".into(),
        release: "12".into(),
        codename: "bookworm".into(),
        lodi_version: "1.2.0".into(),
    }
}

fn parse_text(text: &str) -> Result<HostManifest, lodi::manifest::ManifestErrors> {
    parse(text, "host.toml", &context())
}

fn parsed(text: &str) -> HostManifest {
    parse_text(text).unwrap_or_else(|e| panic!("parses: {e}\n{text}"))
}

/// The diagnostics a manifest is refused with, as `CODE message` lines, and their locations.
fn refused(text: &str) -> Vec<(String, String)> {
    let errors = parse_text(text).expect_err("refused");
    errors
        .diagnostics
        .iter()
        .map(|d| {
            (
                d.code.to_string(),
                format!(
                    "{}{}",
                    d.message,
                    d.location
                        .as_ref()
                        .map(|at| format!(" @{}:{}:{}", at.file, at.line, at.column))
                        .unwrap_or_default()
                ),
            )
        })
        .collect()
}

fn refuses(text: &str, code: &str, contains: &str) {
    let got = refused(text);
    assert!(
        got.iter()
            .any(|(c, message)| c == code && message.contains(contains)),
        "wanted {code} containing {contains:?}, got {got:#?}\n{text}"
    );
}

const HEAD: &str = "[host]\nversion = \"1\"\ndistro = \"debian\"\npackages = \"managed\"\n\n";

/// One `[sources.NAME]` table with the given keys, over the head.
fn one(name: &str, keys: &str) -> String {
    format!("{HEAD}[sources.{name}]\n{keys}")
}

const DIGEST: &str = "0000000000000000000000000000000000000000000000000000000000000000";

fn keys(uris: &str, suites: &str, components: &str) -> String {
    format!(
        "uris = {uris}\nsuites = {suites}\n{components}signed_by = \"files/k.gpg\"\n\
         signed_by_sha256 = \"{DIGEST}\"\n"
    )
}

// ------------------------------------------------------------------------------- the schema ---

#[test]
fn schema_a_source_parses_with_its_defaults_and_substitution() {
    let manifest = parsed(&format!(
        "{HEAD}[vars]\nsuite = \"bookworm\"\nhost = \"download.docker.com\"\n\n\
         [sources.docker]\nuris = [\"https://${{vars.host}}/linux/debian\"]\n\
         suites = [\"${{vars.suite}}\"]\ncomponents = [\"stable\"]\n\
         signed_by = \"files/../files/k.gpg\"\nsigned_by_sha256 = \"{DIGEST}\"\n"
    ));
    let docker = &manifest.sources["docker"];
    assert_eq!(
        docker,
        &SourceEntry {
            name: "docker".into(),
            types: vec!["deb".into()],
            uris: vec!["https://download.docker.com/linux/debian".into()],
            suites: vec!["bookworm".into()],
            components: vec!["stable".into()],
            architectures: vec![],
            signed_by: "files/k.gpg".into(),
            signed_by_url: None,
            signed_by_sha256: DIGEST.into(),
            repo_gpgcheck: false,
        }
    );
    let flat = parsed(&one(
        "flat",
        &format!(
            "types = [\"deb\", \"deb-src\"]\narchitectures = [\"amd64\", \"arm64\"]\n{}",
            keys("[\"https://a.example/repo\"]", "[\"./\"]", "")
        ),
    ));
    assert_eq!(flat.sources["flat"].types, ["deb", "deb-src"]);
    assert_eq!(flat.sources["flat"].architectures, ["amd64", "arm64"]);
    assert!(flat.sources["flat"].components.is_empty());
}

#[test]
fn schema_a_name_outside_the_pattern_is_e_ident() {
    for bad in ["Docker", "-x", "a_b", "a.b", &"x".repeat(65)] {
        refuses(
            &one(
                &format!("\"{bad}\""),
                &keys(
                    "[\"https://a.example\"]",
                    "[\"s\"]",
                    "components = [\"c\"]\n",
                ),
            ),
            "E_IDENT",
            "is not a source name",
        );
    }
    parsed(&one(
        &"a".repeat(64),
        &keys(
            "[\"https://a.example\"]",
            "[\"s\"]",
            "components = [\"c\"]\n",
        ),
    ));
}

#[test]
fn schema_types_default_to_deb_and_accept_only_deb_and_deb_src_once() {
    let base = keys(
        "[\"https://a.example\"]",
        "[\"s\"]",
        "components = [\"c\"]\n",
    );
    refuses(
        &one("a", &format!("types = [\"rpm\"]\n{base}")),
        "E_TYPE",
        "not an apt source type",
    );
    refuses(
        &one("a", &format!("types = [\"deb\", \"deb\"]\n{base}")),
        "E_TYPE",
        "names `deb` twice",
    );
    assert_eq!(parsed(&one("a", &base)).sources["a"].types, ["deb"]);
}

#[test]
fn schema_uris_suites_and_signed_by_sha256_are_required() {
    let all = [
        "uris = [\"https://a.example\"]\n",
        "suites = [\"s\"]\n",
        "components = [\"c\"]\n",
        "signed_by = \"files/k.gpg\"\n",
        &format!("signed_by_sha256 = \"{DIGEST}\"\n"),
    ];
    for (index, missing) in ["uris", "suites", "", "signed_by", "signed_by_sha256"]
        .iter()
        .enumerate()
    {
        if missing.is_empty() {
            continue;
        }
        let text: String = all
            .iter()
            .enumerate()
            .filter(|(i, _)| *i != index)
            .map(|(_, line)| *line)
            .collect();
        refuses(
            &one("a", &text),
            "E_ATTR_CONFLICT",
            &format!("declares no `{missing}`"),
        );
    }
    refuses(
        &one("a", &keys("[]", "[\"s\"]", "components = [\"c\"]\n")),
        "E_ATTR_CONFLICT",
        "declares no `uris`",
    );
    refuses(
        &one(
            "a",
            "uris = [\"https://a.example\"]\nsuites = [\"s\"]\ncomponents = [\"c\"]\n\
             signed_by = \"files/k.gpg\"\nsigned_by_sha256 = \"ABC\"\n",
        ),
        "E_TYPE",
        "not a SHA-256 digest",
    );
}

#[test]
fn schema_components_are_required_unless_flat_forbidden_when_flat_and_flat_is_never_mixed() {
    refuses(
        &one("a", &keys("[\"https://a.example\"]", "[\"s\"]", "")),
        "E_ATTR_CONFLICT",
        "declares no `components`",
    );
    refuses(
        &one(
            "a",
            &keys(
                "[\"https://a.example\"]",
                "[\"./\"]",
                "components = [\"c\"]\n",
            ),
        ),
        "E_ATTR_CONFLICT",
        "declares `components` for a flat repository",
    );
    refuses(
        &one(
            "a",
            &keys(
                "[\"https://a.example\"]",
                "[\"./\", \"bookworm\"]",
                "components = [\"c\"]\n",
            ),
        ),
        "E_ATTR_CONFLICT",
        "mixes flat suites",
    );
    parsed(&one(
        "a",
        &keys("[\"https://a.example\"]", "[\"sub/\"]", ""),
    ));
}

#[test]
fn schema_architectures_are_optional_dpkg_names() {
    refuses(
        &one(
            "a",
            &format!(
                "architectures = [\"AMD64\"]\n{}",
                keys(
                    "[\"https://a.example\"]",
                    "[\"s\"]",
                    "components = [\"c\"]\n"
                )
            ),
        ),
        "E_TYPE",
        "not a dpkg architecture name",
    );
}

#[test]
fn schema_signed_by_resolves_below_the_manifest_directory_like_a_files_source() {
    for escape in ["../k.gpg", "/etc/apt/k.gpg", "files/../../k.gpg", "~/k.gpg"] {
        refuses(
            &one(
                "a",
                &format!(
                    "uris = [\"https://a.example\"]\nsuites = [\"s\"]\ncomponents = [\"c\"]\n\
                     signed_by = \"{escape}\"\nsigned_by_sha256 = \"{DIGEST}\"\n"
                ),
            ),
            "E_PATH_ESCAPE",
            "leaves the manifest's own directory",
        );
    }
}

#[test]
fn schema_trusted_and_any_other_key_are_unknown_attributes() {
    let base = keys(
        "[\"https://a.example\"]",
        "[\"s\"]",
        "components = [\"c\"]\n",
    );
    // `signed_by_url` is a key since LD-366 (tests/host_sources_fetch.rs).
    for key in [
        "trusted = true",
        "allow_insecure = true",
        "check_valid_until = false",
        "options = \"x\"",
    ] {
        refuses(
            &one("a", &format!("{key}\n{base}")),
            "E_UNKNOWN_ATTR",
            "unknown key",
        );
    }
}

// --------------------------------------------------------------------------------- S2, S3 ---

/// A URI with user information, built at run time so that no file of the repository holds a
/// string of the shape the sanitization check (`AGENTS.md` §1.6) reads as an address.
fn userinfo(who: &str) -> String {
    format!("https://{who}{}a.example/d", '@')
}

#[test]
fn s2_a_uri_is_https_only_with_no_user_information_query_or_fragment() {
    for (uri, code, named) in [
        (
            "http://a.example/d",
            "E_UNSUPPORTED",
            "is not an https:// URI",
        ),
        (
            "ftp://a.example/d",
            "E_UNSUPPORTED",
            "is not an https:// URI",
        ),
        ("file:/srv/repo", "E_UNSUPPORTED", "is not an https:// URI"),
        ("a.example/d", "E_UNSUPPORTED", "is not an https:// URI"),
        (
            userinfo("user").as_str(),
            "E_UNSUPPORTED",
            "user information",
        ),
        (
            userinfo("user:pass").as_str(),
            "E_UNSUPPORTED",
            "user information",
        ),
        (
            "https://a.example/d?token=1",
            "E_UNSUPPORTED",
            "carries a query",
        ),
        ("https:///d", "E_UNSUPPORTED", "names no host"),
    ] {
        refuses(
            &one(
                "a",
                &keys(&format!("[\"{uri}\"]"), "[\"s\"]", "components = [\"c\"]\n"),
            ),
            code,
            named,
        );
    }
    // A fragment is refused by name too; `#` is also the S3 character, so its code is S3's, at
    // the value's own place, and the message names the fragment the manifest carries.
    let fragment = one(
        "a",
        &keys(
            "[\"https://a.example/d#x\"]",
            "[\"s\"]",
            "components = [\"c\"]\n",
        ),
    );
    let got = refused(&fragment);
    assert_eq!(got.len(), 1, "{got:#?}");
    assert_eq!(got[0].0, "E_TYPE", "{got:#?}");
    assert!(
        got[0].1.contains("carries a fragment (`#x`)") && got[0].1.contains("`#` starts a comment"),
        "{got:#?}"
    );
    assert!(got[0].1.ends_with("@host.toml:7:9"), "{got:#?}\n{fragment}");
    // The helper names it the same way where a URI is checked on its own.
    assert_eq!(
        lodi::hostscope::manifest::uri_problem("https://a.example/d#x"),
        Some(("E_UNSUPPORTED", "carries a fragment (`#…`)"))
    );
    parsed(&one(
        "a",
        &keys(
            "[\"HTTPS://A.example:8443/d/\"]",
            "[\"s\"]",
            "components = [\"c\"]\n",
        ),
    ));
}

/// S2 through the binary: the plan, over a scratch root, of a manifest whose `[sources]` URI
/// carries a fragment is refused `E_TYPE` naming the fragment at file:line:column, before
/// anything below the root is read or written, and so is the apply.
#[test]
fn s2_the_binary_refuses_a_uri_fragment_as_e_type_naming_it_at_its_place() {
    let case = Case::new("sources-fragment", docker_machine());
    docker(&case, &public_key(1), &[]);
    let manifest = case
        .manifest()
        .replace(DOCKER_URI, &format!("{DOCKER_URI}#main"));
    case.set_manifest(&manifest);
    let line = manifest
        .lines()
        .position(|line| line.starts_with("uris = "))
        .unwrap()
        + 1;
    let before = census(&case);
    for output in [case.plan(), case.apply(&[])] {
        assert_eq!(output.status.code(), Some(3), "{}", story(&output));
        let text = err(&output);
        assert!(text.contains("E_TYPE"), "{}", story(&output));
        assert!(
            text.contains("carries a fragment (`#main`)"),
            "{}",
            story(&output)
        );
        assert!(
            text.contains(&format!("host.toml:{line}:9")),
            "{}",
            story(&output)
        );
        assert!(case.log().is_empty(), "{:?}", case.log());
    }
    assert_eq!(census(&case), before, "nothing below the root was written");
}

#[test]
fn s3_a_value_that_would_break_a_stanza_is_e_type_at_its_place_literal_or_substituted() {
    // Literally, and through a variable that expands to the same bytes.
    let literal = one(
        "a",
        &keys(
            "[\"https://a.example\"]",
            "[\"bookworm\\nTrusted: yes\"]",
            "components = [\"c\"]\n",
        ),
    );
    let got = refused(&literal);
    assert_eq!(got.len(), 1, "{got:#?}");
    assert_eq!(got[0].0, "E_TYPE");
    assert!(got[0].1.contains("control character"), "{got:#?}");
    // The file, the line and the column of the value itself.
    assert!(got[0].1.ends_with("@host.toml:8:11"), "{got:#?}\n{literal}");

    let through = format!(
        "{HEAD}[vars]\nsuite = \"bookworm\\nTrusted: yes\"\n\n[sources.a]\n{}",
        keys(
            "[\"https://a.example\"]",
            "[\"${vars.suite}\"]",
            "components = [\"c\"]\n"
        )
    );
    let got = refused(&through);
    assert_eq!(got.len(), 1, "{got:#?}");
    assert_eq!(got[0].0, "E_TYPE");
    assert!(got[0].1.contains("@host.toml:"), "{got:#?}");

    for (value, problem) in [
        ("", "is empty"),
        ("a b", "whitespace"),
        ("a\\tb", "control character"),
        ("a#b", "`#`"),
        ("a\\u0000", "control character"),
    ] {
        for field in ["suites", "components", "types", "architectures"] {
            let mut uris = "[\"https://a.example\"]".to_string();
            let mut suites = "[\"s\"]".to_string();
            let mut rest = "components = [\"c\"]\n".to_string();
            match field {
                "suites" => suites = format!("[\"{value}\"]"),
                "components" => rest = format!("components = [\"{value}\"]\n"),
                other => rest.push_str(&format!("{other} = [\"{value}\"]\n")),
            }
            if field == "uris" {
                uris = format!("[\"{value}\"]");
            }
            refuses(&one("a", &keys(&uris, &suites, &rest)), "E_TYPE", problem);
        }
    }

    // Whatever passes renders one line per field and no line anyone else wrote: no stanza can
    // hold a `Trusted` line.
    let manifest = parsed(&one(
        "a",
        &keys(
            "[\"https://a.example\"]",
            "[\"s\"]",
            "components = [\"c\"]\n",
        ),
    ));
    let text = sourceset::render(&sources::stanza(&manifest.sources["a"], Format::Binary));
    assert!(!text.to_ascii_lowercase().contains("trusted"), "{text}");
    assert_eq!(text.lines().count(), 6, "{text}");
}

// ---------------------------------------------------------------------------------- S1 ---

const GOLDEN: &str = "tests/fixtures/host/sources";

fn repo() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

/// The declarations the goldens are rendered from, by file name.
fn golden_cases() -> Vec<(&'static str, SourceEntry, Format)> {
    let entry = |name: &str,
                 types: &[&str],
                 uris: &[&str],
                 suites: &[&str],
                 components: &[&str],
                 architectures: &[&str]| SourceEntry {
        name: name.into(),
        types: types.iter().map(|s| s.to_string()).collect(),
        uris: uris.iter().map(|s| s.to_string()).collect(),
        suites: suites.iter().map(|s| s.to_string()).collect(),
        components: components.iter().map(|s| s.to_string()).collect(),
        architectures: architectures.iter().map(|s| s.to_string()).collect(),
        signed_by: "files/k".into(),
        signed_by_url: None,
        signed_by_sha256: DIGEST.into(),
        repo_gpgcheck: false,
    };
    vec![
        (
            "lodi-docker.sources",
            entry(
                "docker",
                &["deb"],
                &["https://download.docker.com/linux/debian"],
                &["bookworm"],
                &["stable"],
                &["amd64"],
            ),
            Format::Armored,
        ),
        (
            "lodi-several.sources",
            entry(
                "several",
                &["deb", "deb-src"],
                &["https://b.example/debian", "https://a.example/debian"],
                &["trixie", "bookworm"],
                &["main", "contrib"],
                &[],
            ),
            Format::Binary,
        ),
        (
            "lodi-flat.sources",
            entry(
                "flat",
                &["deb"],
                &["https://c.example/repo"],
                &["./"],
                &[],
                &["arm64", "amd64"],
            ),
            Format::Binary,
        ),
    ]
}

fn render_goldens() -> String {
    golden_cases()
        .iter()
        .map(|(file, entry, format)| {
            format!(
                "{file}\n{}",
                sourceset::render(&sources::stanza(entry, *format))
            )
        })
        .collect::<Vec<_>>()
        .join("\u{1e}")
}

#[test]
fn s1_the_stanza_is_rendered_byte_exact_as_the_goldens() {
    let dir = repo().join(GOLDEN);
    for (file, entry, format) in golden_cases() {
        let text = sourceset::render(&sources::stanza(&entry, format));
        if std::env::var_os("LODI_RECORD_EXPECTED").is_some() {
            fs::write(dir.join(file), &text).expect("a golden");
            continue;
        }
        let golden = fs::read_to_string(dir.join(file)).expect("the golden");
        assert_eq!(
            text, golden,
            "{file}: re-derive with LODI_RECORD_EXPECTED=1"
        );
        assert!(text.starts_with(&format!("{}\n", sourceset::COMMENT)));
        assert!(text.ends_with('\n') && !text.ends_with("\n\n"));
        assert!(!text.contains('\r'));
        let fields: Vec<&str> = text
            .lines()
            .skip(1)
            .map(|line| line.split(':').next().unwrap())
            .collect();
        let mut expected = vec!["Types", "URIs", "Suites"];
        if !entry.components.is_empty() {
            expected.push("Components");
        }
        if !entry.architectures.is_empty() {
            expected.push("Architectures");
        }
        expected.push("Signed-By");
        assert_eq!(fields, expected, "{file}");
        assert!(text.contains(&format!(
            "Signed-By: /etc/apt/keyrings/lodi-{}.{}\n",
            entry.name,
            format.extension()
        )));
    }
    // The comment says nothing of when, what, who or where.
    let comment = sourceset::COMMENT;
    assert!(!comment.contains("lodi 1") && !comment.chars().any(|c| c.is_ascii_digit()));
    assert!(!comment.contains("/etc") && !comment.contains("/home"));
}

#[test]
fn s1_rendering_twice_and_in_two_processes_is_byte_identical() {
    if std::env::var_os("LODI_TEST_RENDER_CHILD").is_some() {
        print!("<<{}>>", render_goldens());
        return;
    }
    let here = render_goldens();
    assert_eq!(here, render_goldens());
    let mut children = Vec::new();
    for _ in 0..2 {
        let output = Command::new(std::env::current_exe().unwrap())
            .args([
                "--exact",
                "s1_rendering_twice_and_in_two_processes_is_byte_identical",
                "--nocapture",
                "--test-threads=1",
            ])
            .env("LODI_TEST_RENDER_CHILD", "1")
            .output()
            .expect("the child runs");
        assert!(output.status.success());
        let text = String::from_utf8(output.stdout).unwrap();
        let start = text.find("<<").expect("the child's rendering") + 2;
        let end = text.rfind(">>").unwrap();
        children.push(text[start..end].to_string());
    }
    assert_eq!(children[0], here);
    assert_eq!(children[1], here);
}

// ---------------------------------------------------------------------------------- S4 ---

#[test]
fn s4_the_keyring_framing_decides_its_name_and_secret_keys_never_pass() {
    assert_eq!(sniff(&public_key(1)), Ok(Format::Binary));
    assert_eq!(sniff(&armored()), Ok(Format::Armored));
    // Two public keys in one file: accepted; Signed-By trusts every key in it (the docs say so).
    let mut two = public_key(1);
    two.extend(public_key(2));
    assert_eq!(sniff(&two), Ok(Format::Binary));
    // Public then secret: a secret-key or secret-subkey packet anywhere is refused.
    for tag in [5u8, 7] {
        let mut mixed = public_key(1);
        mixed.extend(packet(tag, &[4, 0, 0, 0, 1, 2]));
        assert_eq!(sniff(&mixed), Err(Refusal::Secret), "tag {tag}");
        let mut old = public_key(1);
        old.extend(old_packet(tag, &[4, 0, 0, 0, 1, 2]));
        assert_eq!(sniff(&old), Err(Refusal::Secret), "old tag {tag}");
    }
    assert_eq!(sniff(&packet(5, &[4, 0])), Err(Refusal::Secret));
    // An armored public block followed by a private one.
    let both = format!(
        "{ARMORED}-----BEGIN PGP PRIVATE KEY BLOCK-----\n\nAAAA\n-----END PGP PRIVATE KEY BLOCK-----\n"
    );
    assert_eq!(sniff(both.as_bytes()), Err(Refusal::Secret));
    // The private block's marker anywhere, not only as a line of its own: mid-line after other
    // text, indented, inside the public block's body, and in bytes that are not UTF-8.
    assert_eq!(sniff(&midline_private(ARMORED)), Err(Refusal::Secret));
    let body = "bm90IGEga2V5OiBnZW5lcmF0ZWQgZm9yIGEgdGVzdA==";
    for placed in [
        ARMORED.replace(
            body,
            &format!("{body}-----BEGIN PGP PRIVATE KEY BLOCK-----"),
        ),
        ARMORED.replace(
            body,
            &format!("  -----BEGIN PGP PRIVATE KEY BLOCK-----x{body}"),
        ),
        format!("{ARMORED}trailing words -----BEGIN PGP PRIVATE KEY BLOCK----- and more"),
    ] {
        assert_eq!(sniff(placed.as_bytes()), Err(Refusal::Secret), "{placed}");
    }
    let mut not_utf8 = armored();
    not_utf8.extend([0xff, 0xfe]);
    not_utf8.extend(b"-----BEGIN PGP PRIVATE KEY BLOCK-----");
    assert_eq!(sniff(&not_utf8), Err(Refusal::Secret));
    let mut after_binary = public_key(1);
    after_binary.extend(b"x-----BEGIN PGP PRIVATE KEY BLOCK-----");
    assert_eq!(sniff(&after_binary), Err(Refusal::Secret));
    // Truncated framing, trailing bytes, a first packet that is not a public key, and text.
    let whole = public_key(1);
    assert_eq!(sniff(&whole[..whole.len() - 1]), Err(Refusal::NotKeyring));
    let mut trailing = public_key(1);
    trailing.push(0x00);
    assert_eq!(sniff(&trailing), Err(Refusal::NotKeyring));
    assert_eq!(
        sniff(&packet(13, b"a user id first")),
        Err(Refusal::NotKeyring)
    );
    for text in [
        &b""[..],
        b"<!DOCTYPE html><html><body>moved</body></html>\n",
        b"just some words\n",
        b"-----BEGIN PGP SIGNATURE-----\n\nAAAA\n-----END PGP SIGNATURE-----\n",
    ] {
        assert_eq!(sniff(text), Err(Refusal::NotKeyring), "{text:?}");
    }
    assert_eq!(Refusal::Secret.text(), "holds secret key material");
    assert_eq!(
        Refusal::NotKeyring.text(),
        "is not an OpenPGP public keyring"
    );
}

// ------------------------------------------------------------------- the fake machine walks ---

const DOCKER_URI: &str = "https://download.docker.com/linux/debian";

/// A Debian machine whose index knows nothing of Docker until an update has fetched it.
fn docker_machine() -> Machine {
    Machine::debian().offering_once_fetched(Pkg::new("docker-ce").repo(Some("vendor")))
}

/// A manifest with one `[sources.NAME]` per `(name, keyring file, keyring bytes, suite)` and the
/// given packages; each keyring is written under the manifest's directory.
fn with_sources(case: &Case, sources: &[(&str, &str, &[u8], &str)], packages: &[&str]) {
    let mut text = HEAD.to_string();
    for (name, file, bytes, suite) in sources {
        case.root.write(&format!("etc/lodi/files/{file}"), "");
        fs::write(case.root.path(&format!("etc/lodi/files/{file}")), bytes).unwrap();
        text.push_str(&format!(
            "[sources.{name}]\nuris = [\"https://{name}.example/debian\"]\nsuites = [\"{suite}\"]\n\
             components = [\"stable\"]\nsigned_by = \"files/{file}\"\nsigned_by_sha256 = \"{}\"\n\n",
            sha(bytes)
        ));
    }
    if !packages.is_empty() {
        let names: Vec<String> = packages.iter().map(|p| format!("\"{p}\"")).collect();
        text.push_str(&format!("[packages]\ncommon = [{}]\n", names.join(", ")));
    }
    case.set_manifest(&text);
}

/// The Docker manifest of the brief, with the keyring given.
fn docker(case: &Case, keyring: &[u8], packages: &[&str]) {
    case.root.write("etc/lodi/files/keyrings/docker.key", "");
    fs::write(
        case.root.path("etc/lodi/files/keyrings/docker.key"),
        keyring,
    )
    .unwrap();
    let names: Vec<String> = packages.iter().map(|p| format!("\"{p}\"")).collect();
    case.set_manifest(&format!(
        "{HEAD}[vars]\nsuite = \"bookworm\"\n\n[sources.docker]\nuris = [\"{DOCKER_URI}\"]\n\
         suites = [\"${{vars.suite}}\"]\ncomponents = [\"stable\"]\narchitectures = [\"amd64\"]\n\
         signed_by = \"files/keyrings/docker.key\"\nsigned_by_sha256 = \"{}\"\n\n\
         [packages]\ncommon = [{}]\n",
        sha(keyring),
        names.join(", ")
    ));
}

/// Every regular file below the root, relative, with its bytes' digest — what "nothing was
/// written" is checked against.
fn census(case: &Case) -> Vec<(String, String)> {
    fn visit(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let meta = fs::symlink_metadata(&path).unwrap();
            if meta.is_dir() {
                visit(base, &path, out);
            } else {
                out.push((
                    path.strip_prefix(base).unwrap().display().to_string(),
                    format!(
                        "{}:{}",
                        sha(&fs::read(&path).unwrap_or_default()),
                        meta.mtime_nsec()
                    ),
                ));
            }
        }
    }
    let mut out = Vec::new();
    visit(&case.root.dir, &case.root.dir, &mut out);
    out.sort();
    out
}

const KEYRING_ASC: &str = "etc/apt/keyrings/lodi-docker.asc";
const KEYRING_GPG: &str = "etc/apt/keyrings/lodi-docker.gpg";
const STANZA: &str = "etc/apt/sources.list.d/lodi-docker.sources";

#[test]
fn s4_an_armored_keyring_is_written_as_asc_and_signed_by_names_exactly_that_path() {
    let case = Case::new("sources-armored", docker_machine());
    docker(&case, &armored(), &["docker-ce"]);
    let apply = case.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert_eq!(fs::read(case.root.path(KEYRING_ASC)).unwrap(), armored());
    assert!(!case.root.exists(KEYRING_GPG));
    let stanza = case.root.read(STANZA);
    assert!(
        stanza.contains("\nSigned-By: /etc/apt/keyrings/lodi-docker.asc\n"),
        "{stanza}"
    );
    for path in [KEYRING_ASC, STANZA] {
        let meta = fs::metadata(case.root.path(path)).unwrap();
        assert_eq!(meta.mode() & 0o7777, 0o644, "{path}");
        assert_eq!(meta.uid(), unsafe_uid(), "{path}");
    }
    // A binary keyring is .gpg (and the other way round is S10's).
    let binary = Case::new("sources-binary", docker_machine());
    docker(&binary, &public_key(1), &[]);
    let apply = binary.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert!(binary.root.exists(KEYRING_GPG) && !binary.root.exists(KEYRING_ASC));
    assert!(
        binary
            .root
            .read(STANZA)
            .contains("Signed-By: /etc/apt/keyrings/lodi-docker.gpg\n")
    );
}

/// The invoking user, as the owner a file written under a scratch root gets.
fn unsafe_uid() -> u32 {
    lodi::hostscope::safety::current_euid()
}

#[test]
fn s4_a_secret_or_broken_keyring_is_e_type_by_name_and_its_bytes_are_never_copied_or_printed() {
    let mut secret = public_key(1);
    secret.extend(packet(5, b"SECRET-MATERIAL-XYZ"));
    let both = format!("{ARMORED}-----BEGIN PGP PRIVATE KEY BLOCK-----\nSECRET-MATERIAL-XYZ\n");
    for (name, bytes, named) in [
        ("sources-secret", secret, "holds secret key material"),
        (
            "sources-private",
            both.into_bytes(),
            "holds secret key material",
        ),
        (
            "sources-private-midline",
            midline_private(ARMORED),
            "holds secret key material",
        ),
        (
            "sources-html",
            b"<html>SECRET-MATERIAL-XYZ</html>".to_vec(),
            "is not an OpenPGP public keyring",
        ),
    ] {
        let case = Case::new(name, docker_machine());
        docker(&case, &bytes, &[]);
        let before = census(&case);
        for output in [case.plan(), case.apply(&[])] {
            assert_eq!(output.status.code(), Some(3), "{}", story(&output));
            assert!(err(&output).contains("E_TYPE"), "{}", story(&output));
            assert!(err(&output).contains(named), "{}", story(&output));
            assert!(
                !story(&output).contains("SECRET-MATERIAL"),
                "{}",
                story(&output)
            );
        }
        assert_eq!(census(&case), before, "nothing below the root was written");
    }
}

// ---------------------------------------------------------------------------------- S5 ---

#[test]
fn s5_a_keyring_digest_mismatch_is_e_hash_mismatch_on_plan_and_apply_and_nothing_is_written() {
    let case = Case::new("sources-digest", docker_machine());
    // Two sources: `good` is valid, `bad`'s keyring is not the one it declares.
    with_sources(
        &case,
        &[
            ("bad", "bad.gpg", &public_key(1), "bookworm"),
            ("good", "good.gpg", &public_key(2), "bookworm"),
        ],
        &[],
    );
    fs::write(case.root.path("etc/lodi/files/bad.gpg"), public_key(3)).unwrap();
    let before = census(&case);
    for output in [case.plan(), case.apply(&[])] {
        assert_eq!(output.status.code(), Some(5), "{}", story(&output));
        let text = err(&output);
        assert!(text.contains("E_HASH_MISMATCH"), "{}", story(&output));
        assert!(text.contains("[sources.bad]"), "{}", story(&output));
        assert!(
            text.contains("rotated its signing key"),
            "{}",
            story(&output)
        );
        assert!(
            case.log().is_empty(),
            "no package manager ran: {:?}",
            case.log()
        );
    }
    assert_eq!(census(&case), before, "no journal, no lock, no file");
    assert!(journals(&case.root).is_empty());
    assert!(!case.has_lock());
}

// ---------------------------------------------------------------------------------- S6 ---

#[test]
fn s6_a_reapply_of_an_unchanged_manifest_writes_nothing_and_does_not_force_the_index() {
    let case = Case::new("sources-idempotent", docker_machine());
    docker(&case, &public_key(1), &["docker-ce"]);
    let first = case.apply(&[]);
    assert!(first.status.success(), "{}", story(&first));
    assert!(case.installed().contains("docker-ce"));
    let lock = case.root.read("etc/lodi/host.lock");
    let before = census(&case);

    let plan = case.plan();
    assert!(plan.status.success(), "{}", story(&plan));
    assert!(
        out(&plan).contains("= source docker (unchanged)\n"),
        "{}",
        story(&plan)
    );
    assert!(!out(&plan).contains("~ index"), "{}", story(&plan));
    assert!(out(&plan).ends_with("nothing to do\n"), "{}", story(&plan));

    let again = case.apply(&[]);
    assert!(again.status.success(), "{}", story(&again));
    assert_eq!(out(&again), "nothing to do\n", "{}", story(&again));
    assert!(
        !case
            .log()
            .iter()
            .any(|line| line.starts_with("apt-get update")),
        "{:?}",
        case.log()
    );
    assert_eq!(case.root.read("etc/lodi/host.lock"), lock);
    assert_eq!(census(&case), before, "no byte and no mtime moved");
}

// ---------------------------------------------------------------------------------- S7 ---

#[test]
fn s7_a_repository_a_stanza_of_the_machine_already_lists_is_e_dup_resource_naming_that_file() {
    for (file, body) in [
        (
            "etc/apt/sources.list",
            "deb http://deb.debian.org/debian bookworm main\n\
             deb [arch=amd64] HTTPS://Download.Docker.com/linux/debian/ bookworm stable\n",
        ),
        (
            "etc/apt/sources.list.d/docker.list",
            "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable\n",
        ),
        (
            "etc/apt/sources.list.d/docker.sources",
            "Types: deb\nURIs: https://download.docker.com/linux/debian\nSuites: bookworm\n\
             Components: stable\nSigned-By: /etc/apt/keyrings/docker.asc\n",
        ),
        (
            "etc/apt/sources.list.d/lodi-other.sources",
            "Types: deb\nURIs: https://download.docker.com/linux/debian/\nSuites: trixie bookworm\n\
             Components: stable\n",
        ),
    ] {
        let case = Case::new("sources-dup-machine", docker_machine());
        docker(&case, &public_key(1), &[]);
        case.root.write(file, body);
        let before = census(&case);
        let plan = case.plan();
        assert_eq!(plan.status.code(), Some(3), "{file}: {}", story(&plan));
        assert!(err(&plan).contains("E_DUP_RESOURCE"), "{}", story(&plan));
        assert!(
            err(&plan).contains(&format!("/{file} already lists")),
            "{}",
            story(&plan)
        );
        let apply = case.apply(&[]);
        assert_eq!(apply.status.code(), Some(3), "{}", story(&apply));
        assert_eq!(census(&case), before);
    }
}

#[test]
fn s7_a_commented_out_or_disabled_stanza_is_not_a_conflict_and_an_unparseable_file_is_named() {
    let case = Case::new("sources-dup-disabled", docker_machine());
    docker(&case, &public_key(1), &[]);
    case.root.write(
        "etc/apt/sources.list.d/docker.sources",
        "#Types: deb\n#URIs: https://download.docker.com/linux/debian\n#Suites: bookworm\n\n\
         Types: deb\nURIs: https://download.docker.com/linux/debian\nSuites: bookworm\n\
         Components: stable\nEnabled: no\n",
    );
    case.root.write(
        "etc/apt/sources.list",
        "# deb https://download.docker.com/linux/debian bookworm stable\n",
    );
    // A file apt would not read, with anything in it, is not read either.
    case.root
        .write("etc/apt/sources.list.d/notes.txt", "not a source file {");
    let plan = case.plan();
    assert!(plan.status.success(), "{}", story(&plan));

    case.root.write(
        "etc/apt/sources.list.d/broken.list",
        "deb https://x.example\n",
    );
    let plan = case.plan();
    assert_eq!(plan.status.code(), Some(3), "{}", story(&plan));
    assert!(err(&plan).contains("E_SYNTAX"), "{}", story(&plan));
    assert!(
        err(&plan).contains("/etc/apt/sources.list.d/broken.list"),
        "{}",
        story(&plan)
    );
    fs::remove_file(case.root.path("etc/apt/sources.list.d/broken.list")).unwrap();
    std::os::unix::fs::symlink(
        "/etc/passwd",
        case.root.path("etc/apt/sources.list.d/l.list"),
    )
    .unwrap();
    let plan = case.plan();
    assert_eq!(plan.status.code(), Some(3), "{}", story(&plan));
    assert!(err(&plan).contains("symbolic link"), "{}", story(&plan));
}

/// The files a link above `/etc/apt/sources.list` or `/etc/apt/sources.list.d` would lead to: a
/// stanza that lists the Docker repository and a line that cannot be parsed. Reading either
/// would be an `E_DUP_RESOURCE` or a parse error naming it, never the link.
fn behind_a_link(apt: &Path) {
    fs::create_dir_all(apt.join("sources.list.d")).unwrap();
    fs::write(
        apt.join("sources.list"),
        format!("deb {DOCKER_URI} bookworm stable\n"),
    )
    .unwrap();
    fs::write(
        apt.join("sources.list.d/docker.list"),
        format!("deb {DOCKER_URI} bookworm stable\ndeb https://x.example\n"),
    )
    .unwrap();
}

#[test]
fn s7_a_link_above_either_apt_source_path_is_refused_without_reading_its_target() {
    // Through the binary, over a scratch root whose `/etc/apt` is a link to a directory elsewhere
    // below it.
    let case = Case::new("sources-parent-link", docker_machine());
    docker(&case, &public_key(1), &[]);
    let apt = case.root.path("etc/apt");
    let elsewhere = case.root.path("elsewhere/apt");
    fs::create_dir_all(case.root.path("elsewhere")).unwrap();
    if apt.exists() {
        fs::rename(&apt, &elsewhere).unwrap();
    }
    behind_a_link(&elsewhere);
    std::os::unix::fs::symlink("../elsewhere/apt", &apt).unwrap();
    let before = census(&case);
    for output in [case.plan(), case.apply(&[])] {
        assert_eq!(output.status.code(), Some(3), "{}", story(&output));
        let text = err(&output);
        assert!(text.contains("E_SYNTAX"), "{}", story(&output));
        assert!(
            text.contains("/etc/apt on the way to it is a symbolic link"),
            "{}",
            story(&output)
        );
        assert!(!text.contains("already lists"), "{}", story(&output));
    }
    assert_eq!(census(&case), before, "nothing below the root was written");

    // Each path on its own, and a link at either component above it: `/etc` or `/etc/apt`.
    for (link, target) in [("etc", "elsewhere/etc"), ("etc/apt", "elsewhere/etc/apt")] {
        for path in ["/etc/apt/sources.list", "/etc/apt/sources.list.d"] {
            let root = hostroot::Root::new("sources-parent-link-lib");
            fs::create_dir_all(root.path("etc")).unwrap();
            behind_a_link(&root.path("elsewhere/etc/apt"));
            let hops = link.matches('/').count() + 1;
            let relative = format!("{}{target}", "../".repeat(hops - 1));
            fs::remove_dir(root.path(link)).ok();
            std::os::unix::fs::symlink(&relative, root.path(link)).unwrap();
            let skip = |candidate: &str| candidate == "/etc/apt/sources.list" && path != candidate;
            let refused = sourceset::read_machine(&root.dir, &skip)
                .expect_err(&format!("{link} linked, {path} read"));
            assert_eq!(refused.code, "E_SYNTAX", "{refused:?}");
            assert!(
                refused.message.starts_with(&format!("{path}: "))
                    && refused
                        .message
                        .contains(&format!("/{link} on the way to it is a symbolic link")),
                "{link}, {path}: {refused:?}"
            );
        }
    }
}

#[test]
fn s7_two_tables_sharing_a_uri_and_suite_are_e_dup_resource_naming_both() {
    let text = format!(
        "{HEAD}[sources.a]\n{}\n[sources.b]\n{}",
        keys(
            "[\"https://x.example/one\", \"https://A.example/d/\"]",
            "[\"s\", \"t\"]",
            "components = [\"c\"]\n"
        ),
        keys(
            "[\"https://a.example/d\"]",
            "[\"u\", \"t\"]",
            "components = [\"c\"]\n"
        ),
    );
    refuses(
        &text,
        "E_DUP_RESOURCE",
        "[sources.a] and [sources.b] both list https://a.example/d t",
    );
}

#[test]
fn s7_a_files_key_under_the_lodi_namespace_is_e_dup_resource_naming_both() {
    let base = keys(
        "[\"https://a.example\"]",
        "[\"s\"]",
        "components = [\"c\"]\n",
    );
    for path in [
        "/etc/apt/sources.list.d/lodi-docker.sources",
        "/etc/apt/keyrings/lodi-docker.gpg",
        "/etc/apt/keyrings/lodi-docker.asc",
    ] {
        refuses(
            &format!("{HEAD}[sources.docker]\n{base}\n[files.\"{path}\"]\ncontent = \"x\"\n"),
            "E_DUP_RESOURCE",
            &format!("`{path}` in [files] is under [sources.docker]"),
        );
    }
    refuses(
        &format!("{HEAD}[files.\"/etc/apt/keyrings/lodi-other.key\"]\ncontent = \"x\"\n"),
        "E_DUP_RESOURCE",
        "the lodi- namespace",
    );
    parsed(&format!(
        "{HEAD}[files.\"/etc/apt/keyrings/vendor.gpg\"]\ncontent = \"x\"\n"
    ));
}

// ---------------------------------------------------------------------------------- S8 ---

#[test]
fn s8_the_source_step_comes_first_forces_the_index_and_arms_the_keyring_before_the_stanza() {
    let case = Case::new("sources-order", docker_machine());
    docker(&case, &public_key(1), &["docker-ce"]);
    // The index is fresh: Case wrote it a moment ago. The changing source forces it anyway.
    let plan = case.plan();
    assert!(plan.status.success(), "{}", story(&plan));
    let text = out(&plan);
    let lines: Vec<&str> = text.lines().collect();
    assert_eq!(lines[0], "+ source docker (keyring, sources)", "{text}");
    assert!(
        lines[1].starts_with("~ index (apt-get update ") && lines[1].contains(sources::ERROR_MODE),
        "{text}"
    );
    assert_eq!(
        lines[2],
        format!("+ package docker-ce ({})", lodi::hostscope::plan::DEFERRED),
        "{text}"
    );

    let apply = case.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    let log = case.log();
    let update = log.iter().position(|l| l.starts_with("apt-get update"));
    let install = log
        .iter()
        .position(|l| l.starts_with("apt-get install") && !l.contains(" -s "));
    assert!(update.is_some() && update < install, "{log:?}");
    // The refresh saw the stanza, and the keyring it names was already there.
    assert_eq!(
        case.update_saw(),
        ["lodi-docker.sources /etc/apt/keyrings/lodi-docker.gpg present"]
    );
    // The journal announced keyring then stanza.
    let record = journal::read(&journals(&case.root)[0]).unwrap();
    let files: Vec<(&str, &str)> = record
        .header
        .actions
        .iter()
        .map(|e| (e.id.as_str(), e.summary.as_str()))
        .collect();
    assert!(
        files[0].0 == "s1.1" && files[0].1.contains("lodi-docker.gpg"),
        "{files:?}"
    );
    assert!(
        files[1].0 == "s1.2" && files[1].1.contains("lodi-docker.sources"),
        "{files:?}"
    );
    assert_eq!(files[2].0, "i1", "{files:?}");

    // On the way out: the stanza first, then the keyring, and the index forgets the source.
    case.set_manifest(HEAD);
    let plan = case.plan();
    assert!(plan.status.success(), "{}", story(&plan));
    assert!(
        out(&plan).starts_with(
            "- source docker (sources: remove /etc/apt/sources.list.d/lodi-docker.sources, \
             keyring: remove /etc/apt/keyrings/lodi-docker.gpg)\n~ index"
        ),
        "{}",
        story(&plan)
    );
    let apply = case.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert_eq!(case.update_saw(), ["nothing"]);
    assert!(!case.root.exists(STANZA) && !case.root.exists(KEYRING_GPG));
    let record = journal::read(journals(&case.root).last().unwrap()).unwrap();
    let order: Vec<&str> = record
        .header
        .actions
        .iter()
        .map(|e| e.summary.as_str())
        .collect();
    assert!(
        order[0].contains("lodi-docker.sources") && order[1].contains("lodi-docker.gpg"),
        "{order:?}"
    );
}

#[test]
fn s8_a_name_the_index_lacks_is_deferred_only_while_a_source_changes_and_settled_after_the_refresh()
{
    // No changing source: an unknown name behaves exactly as in 1.2.
    let plain = Case::new("sources-unknown-plain", docker_machine());
    plain.set_manifest(&format!("{HEAD}[packages]\ncommon = [\"docker-ce\"]\n"));
    let plan = plain.plan();
    assert_eq!(plan.status.code(), Some(3), "{}", story(&plan));
    assert!(err(&plan).contains("E_UNKNOWN_PACKAGE"), "{}", story(&plan));

    // A changing source whose refreshed index still lacks the name: the post-refresh check
    // raises E_UNKNOWN_PACKAGE before anything is installed.
    let case = Case::new("sources-unknown-after", docker_machine());
    docker(&case, &public_key(1), &["no-such-thing"]);
    let plan = case.plan();
    assert!(plan.status.success(), "{}", story(&plan));
    assert!(
        out(&plan).contains(&format!(
            "+ package no-such-thing ({})",
            lodi::hostscope::plan::DEFERRED
        )),
        "{}",
        story(&plan)
    );
    let apply = case.apply(&[]);
    assert_eq!(apply.status.code(), Some(3), "{}", story(&apply));
    assert!(
        err(&apply).contains("E_UNKNOWN_PACKAGE"),
        "{}",
        story(&apply)
    );
    assert!(
        err(&apply).contains("refreshed by this apply"),
        "{}",
        story(&apply)
    );
    assert!(
        !case
            .log()
            .iter()
            .any(|l| l.starts_with("apt-get install") && !l.contains(" -s ")),
        "{:?}",
        case.log()
    );
}

// ---------------------------------------------------------------------------------- S9 ---

fn fail_update(case: &Case, how: &str, text: &str) {
    case.edit(|m| m[how] = serde_json::json!({ "apt-get update": text }));
}

fn clear_update(case: &Case) {
    case.edit(|m| {
        m.as_object_mut().unwrap().remove("fail");
        m.as_object_mut().unwrap().remove("say");
    });
}

#[test]
fn s9_a_failed_forced_refresh_puts_the_source_back_runs_no_transaction_and_converges_later() {
    let case = Case::new("sources-refresh-fails", docker_machine());
    docker(&case, &public_key(1), &["docker-ce"]);
    fail_update(&case, "fail", "E: Could not resolve host");
    let apply = case.apply(&[]);
    assert_eq!(apply.status.code(), Some(8), "{}", story(&apply));
    let text = err(&apply);
    assert!(text.contains("E_APPLY"), "{}", story(&apply));
    assert!(
        text.contains("the index refresh [sources.docker] forced failed"),
        "{}",
        story(&apply)
    );
    assert!(text.contains("put back as it was"), "{}", story(&apply));
    assert!(!case.root.exists(STANZA) && !case.root.exists(KEYRING_GPG));
    assert!(!case.installed().contains("docker-ce"));
    assert!(!case.has_lock());
    // The journal says the refresh failed, and that each file was put back, stanza first.
    let record = journal::read(&journals(&case.root)[0]).unwrap();
    let outcomes = journal::outcomes(&record);
    assert_eq!(outcomes["i1"], "failed", "{outcomes:?}");
    assert_eq!(outcomes["s1.2.restore"], "done", "{outcomes:?}");
    assert_eq!(outcomes["s1.1.restore"], "done", "{outcomes:?}");
    assert!(!outcomes.contains_key("p1") || outcomes["p1"] == "announced");
    let ids: Vec<&str> = record
        .events
        .iter()
        .filter_map(|e| match e {
            journal::Event::Begin { action, .. } => Some(action.as_str()),
            _ => None,
        })
        .collect();
    assert_eq!(ids, ["s1.1", "s1.2", "i1", "s1.2.restore", "s1.1.restore"]);

    // Once the cause is gone, the next apply converges.
    clear_update(&case);
    let again = case.apply(&[]);
    assert!(again.status.success(), "{}", story(&again));
    assert!(case.installed().contains("docker-ce"));
    assert!(case.root.exists(STANZA) && case.root.exists(KEYRING_GPG));
    assert_eq!(case.apply(&[]).stdout, b"nothing to do\n");
}

#[test]
fn s9_a_warning_apt_prints_for_a_declared_uri_fails_the_refresh_and_restores_the_old_stanza() {
    let case = Case::new("sources-refresh-warns", docker_machine());
    docker(&case, &public_key(1), &[]);
    assert!(case.apply(&[]).status.success());
    let old = case.root.read(STANZA);
    // The source changes its suite; apt warns about exactly that repository.
    let text = case
        .manifest()
        .replace("suite = \"bookworm\"", "suite = \"trixie\"");
    case.set_manifest(&text);
    fail_update(
        &case,
        "say",
        &format!("W: Failed to fetch {DOCKER_URI}/dists/trixie/InRelease  404  Not Found"),
    );
    let apply = case.apply(&[]);
    assert_eq!(apply.status.code(), Some(8), "{}", story(&apply));
    assert!(
        err(&apply).contains("apt reported, for [sources.docker]: W: Failed to fetch"),
        "{}",
        story(&apply)
    );
    assert_eq!(case.root.read(STANZA), old, "the previous stanza is back");
    assert!(case.root.exists(KEYRING_GPG));
    // A warning about some other repository is not this source's failure.
    fail_update(
        &case,
        "say",
        "W: Failed to fetch https://elsewhere.example/InRelease",
    );
    let apply = case.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert!(case.root.read(STANZA).contains("Suites: trixie\n"));
}

/// A departed-only source still identifies its recorded URI and name after its stanza is
/// removed for the refresh. Both apt's nonzero status and its success-with-warning put it back.
#[test]
fn s9_departed_only_refresh_failure_or_uri_warning_restores_source_and_converges() {
    for (label, how, message) in [
        ("nonzero", "fail", "E: temporary index failure".to_string()),
        (
            "warning",
            "say",
            format!("W: Failed to fetch {DOCKER_URI}/dists/bookworm/InRelease"),
        ),
    ] {
        let case = Case::new(
            &format!("sources-departed-refresh-{label}"),
            docker_machine().offering(Pkg::new("sl")),
        );
        docker(&case, &public_key(1), &[]);
        assert!(case.apply(&[]).status.success());
        let stanza = case.root.read(STANZA);
        let keyring = fs::read(case.root.path(KEYRING_GPG)).unwrap();
        let lock = case.root.read("etc/lodi/host.lock");
        case.set_manifest(&format!("{HEAD}[packages]\ncommon = [\"sl\"]\n"));
        let plan = case.plan();
        assert!(plan.status.success(), "{}", story(&plan));
        assert!(out(&plan).contains("- source docker"), "{}", story(&plan));
        assert!(out(&plan).contains("~ index"), "{}", story(&plan));
        assert!(out(&plan).contains("+ package sl"), "{}", story(&plan));
        fail_update(&case, how, &message);
        let log_before = case.log().len();
        let apply = case.apply(&[]);
        assert_eq!(apply.status.code(), Some(8), "{}", story(&apply));
        let error = err(&apply);
        assert!(error.contains("E_APPLY"), "{}", story(&apply));
        assert!(
            error.contains("the index refresh [sources.docker] forced failed"),
            "{}",
            story(&apply)
        );
        if how == "say" {
            assert!(
                error.contains("apt reported, for [sources.docker]: W: Failed to fetch"),
                "{}",
                story(&apply)
            );
        }
        assert_eq!(case.root.read(STANZA), stanza, "{label}: stanza restored");
        assert_eq!(
            fs::read(case.root.path(KEYRING_GPG)).unwrap(),
            keyring,
            "{label}: keyring restored"
        );
        assert_eq!(case.root.read("etc/lodi/host.lock"), lock);
        assert!(!case.installed().contains("sl"));
        assert!(
            case.log()[log_before..]
                .iter()
                .any(|line| line.starts_with("apt-get update"))
        );
        assert!(
            !case.log()[log_before..]
                .iter()
                .any(|line| line.starts_with("apt-get install") && !line.contains(" -s "))
        );
        let record = journal::read(journals(&case.root).last().unwrap()).unwrap();
        let outcomes = journal::outcomes(&record);
        assert_eq!(outcomes["i1"], "failed");
        assert_eq!(outcomes["s1.2.restore"], "done");
        assert_eq!(outcomes["s1.1.restore"], "done");

        clear_update(&case);
        let again = case.apply(&[]);
        assert!(again.status.success(), "{}", story(&again));
        assert!(!case.root.exists(STANZA) && !case.root.exists(KEYRING_GPG));
        assert!(case.installed().contains("sl"));
        assert_eq!(case.apply(&[]).stdout, b"nothing to do\n");
    }
}

#[test]
fn s9_no_update_skips_the_refresh_says_so_and_a_deferred_name_is_unknown_before_any_install() {
    // `--no-update` is the apply's flag (1.2's CLI, unchanged): the plan the apply prints says
    // on the source line that the index is not refreshed.
    let case = Case::new("sources-no-update", docker_machine());
    docker(&case, &public_key(1), &["docker-ce"]);
    let apply = case.apply(&["--no-update"]);
    assert_eq!(apply.status.code(), Some(3), "{}", story(&apply));
    assert!(
        err(&apply).contains("E_UNKNOWN_PACKAGE"),
        "{}",
        story(&apply)
    );
    assert!(!case.root.exists(STANZA) && !case.root.exists(KEYRING_GPG));
    assert!(
        !case.log().iter().any(|l| l.starts_with("apt-get update")
            || (l.starts_with("apt-get install") && !l.contains(" -s "))),
        "{:?}",
        case.log()
    );

    docker(&case, &public_key(1), &[]);
    let apply = case.apply(&["--no-update"]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert!(
        out(&apply)
            .contains("\n+ source docker (keyring, sources, index not refreshed: --no-update)\n"),
        "{}",
        story(&apply)
    );
    assert!(!out(&apply).contains("~ index"), "{}", story(&apply));
    assert!(
        !case.log().iter().any(|l| l.starts_with("apt-get update")),
        "{:?}",
        case.log()
    );
    assert!(case.root.exists(STANZA) && case.root.exists(KEYRING_GPG));
}

/// A real apply of `case`, held at `hold`, killed there; returns the journal it left.
fn crash(case: &Case, hold: Hold) -> journal::Record {
    let path = case.fake_path();
    let mut child = hold.spawn_with(&case.root, &[("PATH", &path)]);
    hold.wait_held();
    kill(&mut child);
    let files = journals(&case.root);
    journal::read(files.last().expect("a journal")).expect("the journal reads")
}

/// Whether a stanza below the root names a keyring that is not there.
fn stanza_names_a_missing_keyring(case: &Case) -> bool {
    let text = case.root.read(STANZA);
    text.lines()
        .find_map(|line| line.strip_prefix("Signed-By: "))
        .is_some_and(|keyring| !case.root.exists(keyring))
}

#[test]
fn s9_a_crash_at_each_mutation_of_the_step_is_classified_and_never_leaves_a_stanza_naming_a_missing_keyring()
 {
    // 1. At the keyring's write: nothing of the source is there; the step is incomplete.
    let case = Case::new("sources-crash-keyring", docker_machine());
    docker(&case, &public_key(1), &[]);
    let record = crash(&case, Hold::at_write_of(&case.root, "lodi-docker.gpg"));
    assert!(matches!(
        record.classify(&case.root.dir),
        Classification::Incomplete { ref action, .. } if action == "s1.1"
    ));
    assert!(!case.root.exists(STANZA) && !stanza_names_a_missing_keyring(&case));
    assert!(case.apply(&[]).status.success());

    // 2. At the stanza's write over an original it keeps first: the copy is taken and the old
    //    stanza still stands, which is neither state — ambiguous, until a human resolves it.
    let case = Case::new("sources-crash-stanza", docker_machine());
    docker(&case, &public_key(1), &[]);
    case.root.write(
        STANZA,
        "# a hand-made file that is not a stanza lodi wrote\n",
    );
    let record = crash(&case, Hold::at_write_of(&case.root, "lodi-docker.sources"));
    assert!(case.root.exists(KEYRING_GPG));
    assert!(!stanza_names_a_missing_keyring(&case));
    match record.classify(&case.root.dir) {
        Classification::Ambiguous { action, .. } => assert_eq!(action, "s1.2"),
        other => panic!("expected ambiguous, got {other:?}"),
    }
    let refused = case.apply(&[]);
    assert_eq!(refused.status.code(), Some(8), "{}", story(&refused));
    assert!(
        err(&refused).contains("E_JOURNAL_AMBIGUOUS"),
        "{}",
        story(&refused)
    );
    // The operator looked, and the machine is as they want it: they say so by the journal's id.
    let resolved = case.apply(&["--resolved", &record.id]);
    assert!(resolved.status.success(), "{}", story(&resolved));
    assert!(!stanza_names_a_missing_keyring(&case));

    // 3. At the restore of a stanza the failed refresh puts back: held at its second write,
    //    after the first put the new bytes in. The keyring was never touched.
    let case = Case::new("sources-crash-restore", docker_machine());
    docker(&case, &public_key(1), &[]);
    assert!(case.apply(&[]).status.success());
    let text = case
        .manifest()
        .replace("suite = \"bookworm\"", "suite = \"trixie\"");
    case.set_manifest(&text);
    fail_update(&case, "fail", "E: failed");
    let record = crash(
        &case,
        Hold::at_write_of(&case.root, "lodi-docker.sources").nth(2),
    );
    assert!(matches!(
        record.classify(&case.root.dir),
        Classification::Incomplete { ref action, .. } if action == "s1.1.restore"
    ));
    assert!(!stanza_names_a_missing_keyring(&case));
    clear_update(&case);
    assert!(case.apply(&[]).status.success());

    // 4. At the restore of a created stanza, before it is removed, and at the restore of the
    //    created keyring, after the stanza was: the stanza never outlives its keyring.
    for (name, held, expect) in [
        (
            "sources-crash-remove-stanza",
            "lodi-docker.sources",
            "s1.2.restore",
        ),
        (
            "sources-crash-remove-keyring",
            "lodi-docker.gpg",
            "s1.1.restore",
        ),
    ] {
        let case = Case::new(name, docker_machine());
        docker(&case, &public_key(1), &[]);
        fail_update(&case, "fail", "E: failed");
        let record = crash(&case, Hold::at_open_of(&case.root, held));
        assert!(
            matches!(
                record.classify(&case.root.dir),
                Classification::Incomplete { ref action, .. } if action == expect
            ),
            "{:?}",
            record.classify(&case.root.dir)
        );
        assert!(!stanza_names_a_missing_keyring(&case), "{name}");
        clear_update(&case);
        let again = case.apply(&[]);
        assert!(again.status.success(), "{}", story(&again));
        assert!(case.root.exists(STANZA) && !stanza_names_a_missing_keyring(&case));
    }
}

// --------------------------------------------------------------------------------- S10 ---

#[test]
fn s10_removing_the_table_removes_or_restores_both_files_as_a_departed_files_entry_is() {
    let case = Case::new("sources-departed", docker_machine());
    // A keyring that was there before lodi: it is kept once and put back on removal.
    case.root
        .write(KEYRING_GPG, "the machine's own keyring bytes\n");
    docker(&case, &public_key(1), &[]);
    let plan = case.plan();
    assert!(
        err(&plan).contains("W_REPLACED_UNMANAGED: /etc/apt/keyrings/lodi-docker.gpg"),
        "{}",
        story(&plan)
    );
    assert!(case.apply(&[]).status.success());
    let lock = case.lock();
    for path in [
        "/etc/apt/keyrings/lodi-docker.gpg",
        "/etc/apt/sources.list.d/lodi-docker.sources",
    ] {
        let record = &lock["files"][path];
        assert_eq!(record["mode"], "0644", "{lock:#}");
        assert_eq!(record["onRemove"], "restore", "{lock:#}");
    }
    assert!(lock["files"]["/etc/apt/keyrings/lodi-docker.gpg"]["backup"].is_string());

    case.set_manifest(HEAD);
    let apply = case.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert_eq!(
        case.root.read(KEYRING_GPG),
        "the machine's own keyring bytes\n"
    );
    assert!(!case.root.exists(STANZA));
    assert!(backups(&case.root).is_empty());
    assert!(
        case.lock()["files"]
            .as_object()
            .is_none_or(|f| f.is_empty())
    );
}

#[test]
fn s10_a_hand_edit_of_either_file_is_e_drift_refused_until_overwrite_drift() {
    for path in [STANZA, KEYRING_GPG] {
        let case = Case::new("sources-drift", docker_machine());
        docker(&case, &public_key(1), &[]);
        assert!(case.apply(&[]).status.success());
        case.root.write(path, "edited by hand\n");
        let plan = case.plan();
        assert!(
            err(&plan).contains(&format!(
                "W_DRIFT: /{path} was changed since lodi last wrote it"
            )),
            "{}",
            story(&plan)
        );
        assert!(out(&plan).contains("~ source docker ("), "{}", story(&plan));
        let lock = case.root.read("etc/lodi/host.lock");
        let before = census(&case);
        let apply = case.apply(&[]);
        assert_eq!(apply.status.code(), Some(8), "{}", story(&apply));
        assert_eq!(lodi::diag::exit_status("E_DRIFT"), 8);
        assert!(
            err(&apply).contains(&format!(
                "E_DRIFT: /{path} of a declared source was changed since lodi last wrote it"
            )),
            "{}",
            story(&apply)
        );
        assert!(
            err(&apply).contains("--overwrite-drift"),
            "{}",
            story(&apply)
        );
        assert!(!err(&apply).contains("E_DECLINED"), "{}", story(&apply));
        assert_eq!(case.root.read(path), "edited by hand\n");
        assert_eq!(case.root.read("etc/lodi/host.lock"), lock);
        assert_eq!(census(&case), before, "nothing was written");
        let apply = case.apply(&["--overwrite-drift"]);
        assert!(apply.status.success(), "{}", story(&apply));
        assert_ne!(case.root.read(path), "edited by hand\n");
    }
}

/// An ordinary `[files]` entry's drift keeps 1.2's `E_DECLINED` (exit 11), alone and beside a
/// source's `E_DRIFT`, which the apply reports first; `--overwrite-drift` takes both back.
#[test]
fn s10_a_files_entrys_drift_stays_e_declined_beside_a_sources_e_drift() {
    let case = Case::new("sources-drift-files", docker_machine());
    let (uid, gid) = hostroot::ids(&case.root);
    docker(&case, &public_key(1), &[]);
    let files = format!(
        "\n[files.\"/etc/motd\"]\ncontent = \"hello\\n\"\nowner = \"{uid}\"\ngroup = \"{gid}\"\n"
    );
    case.set_manifest(&format!("{}{files}", case.manifest()));
    let first = case.apply(&[]);
    assert!(first.status.success(), "{}", story(&first));

    case.root.write("etc/motd", "edited by hand\n");
    let apply = case.apply(&[]);
    assert_eq!(apply.status.code(), Some(11), "{}", story(&apply));
    assert!(
        err(&apply).contains("E_DECLINED: /etc/motd was changed since lodi last wrote it"),
        "{}",
        story(&apply)
    );
    assert!(!err(&apply).contains("E_DRIFT"), "{}", story(&apply));

    case.root.write(STANZA, "edited by hand\n");
    let apply = case.apply(&[]);
    assert_eq!(apply.status.code(), Some(8), "{}", story(&apply));
    let text = err(&apply);
    let drift = text.find("E_DRIFT: /etc/apt/sources.list.d/lodi-docker.sources");
    let declined = text.find("E_DECLINED: /etc/motd");
    assert!(
        matches!((drift, declined), (Some(d), Some(e)) if d < e),
        "{}",
        story(&apply)
    );

    let apply = case.apply(&["--overwrite-drift"]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert_eq!(case.root.read("etc/motd"), "hello\n");
    assert_ne!(case.root.read(STANZA), "edited by hand\n");
}

#[test]
fn s10_sources_only_the_lock_records_are_removed_in_name_order() {
    let case = Case::new("sources-lock-only", docker_machine());
    with_sources(
        &case,
        &[
            ("zeta", "z.gpg", &public_key(1), "s"),
            ("alpha", "a.gpg", &armored(), "s"),
        ],
        &[],
    );
    assert!(case.apply(&[]).status.success());
    case.set_manifest(HEAD);
    let plan = case.plan();
    let text = out(&plan);
    let alpha = text.find("- source alpha").expect(&text);
    let zeta = text.find("- source zeta").expect(&text);
    assert!(
        alpha < zeta && zeta < text.find("~ index").unwrap(),
        "{text}"
    );
    assert!(case.apply(&[]).status.success());
    for name in ["alpha", "zeta"] {
        assert!(
            !case
                .root
                .exists(&format!("etc/apt/sources.list.d/lodi-{name}.sources"))
        );
    }
    assert!(!case.root.exists("etc/apt/keyrings/lodi-alpha.asc"));
}

#[test]
fn s10_a_keyring_whose_format_changes_is_one_step_new_path_stanza_then_old_path() {
    let case = Case::new("sources-format", docker_machine());
    docker(&case, &armored(), &[]);
    assert!(case.apply(&[]).status.success());
    docker(&case, &public_key(1), &[]);
    let plan = case.plan();
    assert!(
        out(&plan).starts_with(
            "~ source docker (keyring: create /etc/apt/keyrings/lodi-docker.gpg, sources: content, \
             old keyring: remove /etc/apt/keyrings/lodi-docker.asc)\n"
        ),
        "{}",
        story(&plan)
    );
    let apply = case.apply(&[]);
    assert!(apply.status.success(), "{}", story(&apply));
    assert!(case.root.exists(KEYRING_GPG) && !case.root.exists(KEYRING_ASC));
    assert!(
        case.root
            .read(STANZA)
            .contains("Signed-By: /etc/apt/keyrings/lodi-docker.gpg\n")
    );
    let files = case.lock()["files"].clone();
    assert!(
        files.get("/etc/apt/keyrings/lodi-docker.asc").is_none(),
        "{files:#}"
    );
    assert!(
        files.get("/etc/apt/keyrings/lodi-docker.gpg").is_some(),
        "{files:#}"
    );
    let record = journal::read(journals(&case.root).last().unwrap()).unwrap();
    let order: Vec<&str> = record
        .header
        .actions
        .iter()
        .map(|e| e.summary.as_str())
        .collect();
    assert!(
        order[0].contains("lodi-docker.gpg")
            && order[1].contains("lodi-docker.sources")
            && order[2].contains("lodi-docker.asc"),
        "{order:?}"
    );
    assert_eq!(
        case.update_saw(),
        ["lodi-docker.sources /etc/apt/keyrings/lodi-docker.gpg present"]
    );
}

// --------------------------------------------------------------------------------- S11 ---

#[test]
fn s11_a_non_empty_sources_table_on_arch_is_e_unsupported_before_anything_below_the_root_is_read() {
    let case = Case::new("sources-arch", Machine::arch());
    case.set_manifest(&format!(
        "[host]\nversion = \"1\"\ndistro = \"arch\"\n\n[sources.a]\n{}",
        keys(
            "[\"https://a.example\"]",
            "[\"s\"]",
            "components = [\"c\"]\n"
        )
    ));
    // A keyring that is not there and an apt file nobody could parse: neither is reached.
    case.root
        .write("etc/apt/sources.list", "not a source line\n");
    let before = census(&case);
    for output in [case.plan(), case.apply(&[])] {
        assert_eq!(output.status.code(), Some(3), "{}", story(&output));
        assert!(err(&output).contains("E_UNSUPPORTED"), "{}", story(&output));
        assert!(err(&output).contains("`[sources]`"), "{}", story(&output));
        assert!(!err(&output).contains("E_SYNTAX"), "{}", story(&output));
        assert!(case.log().is_empty(), "{:?}", case.log());
    }
    assert_eq!(census(&case), before);
    // An empty table is nothing to refuse.
    case.set_manifest("[host]\nversion = \"1\"\ndistro = \"arch\"\n\n[sources]\n");
    assert!(case.plan().status.success());
}

#[test]
fn schema_every_refusal_is_found_before_anything_below_the_root_is_read_or_written() {
    let case = Case::new("sources-refused-first", docker_machine());
    // An apt file nobody could parse and no keyring at all: a manifest refusal comes first.
    case.root
        .write("etc/apt/sources.list", "not a source line\n");
    case.set_manifest(&one(
        "a",
        &keys(
            "[\"http://a.example\"]",
            "[\"s\"]",
            "components = [\"c\"]\n",
        ),
    ));
    let before = census(&case);
    for output in [case.plan(), case.apply(&[])] {
        assert_eq!(output.status.code(), Some(3), "{}", story(&output));
        assert!(err(&output).contains("E_UNSUPPORTED"), "{}", story(&output));
        assert!(!err(&output).contains("E_SYNTAX") && !err(&output).contains("E_STORE_IO"));
        assert!(case.log().is_empty(), "{:?}", case.log());
    }
    assert_eq!(census(&case), before);
}

// ------------------------------------------------------------------------ compatibility ---
//
// §7: a 1.2 `host.toml` — every host manifest committed under `tests/fixtures/host/import/`, and
// one `[files]` walk — plans byte-identically, and its apply leaves byte-identical lock and
// journal bytes, against goldens under `tests/fixtures/host/compat-1.2/` recorded from the 1.2.0
// binary by these same walks.
//
// Recording (never a validation command): a `git worktree` of the 1.2.0 release commit outside
// the repository, built with the repository's toolchain, then `LODI_RECORD_EXPECTED=1
// LODI_COMPAT_BINARY=<that build's lodi> cargo test --locked --test host_sources compat_1_2`, and
// the worktree removed (`tests/fixtures/host/compat-1.2/README.md`). What a walk cannot hold
// still is written as a placeholder, the same way for both binaries: the scratch root `<root>`,
// the fake machine's directory `<fake>`, every UTC instant `<time>`, a journal id `<journal>`, a
// backup's stamp, the invoking user's ids, and the running binary's own version, which is written
// back as the recorded one. Every other byte is compared as recorded.

const COMPAT: &str = "tests/fixtures/host/compat-1.2";
/// The version of the binary that recorded the goldens.
const RECORDED: &str = "1.2.0";

fn compat_binary() -> std::ffi::OsString {
    std::env::var_os("LODI_COMPAT_BINARY")
        .unwrap_or_else(|| std::ffi::OsString::from(env!("CARGO_BIN_EXE_lodi")))
}

fn compat_recording() -> bool {
    std::env::var_os("LODI_RECORD_EXPECTED").is_some()
        && std::env::var_os("LODI_COMPAT_BINARY").is_some()
}

/// Every `YYYY-MM-DDTHH:MM:SSZ` and `YYYYMMDDTHHMMSSZ-<32 hex>`, masked.
fn mask_times(text: &str) -> String {
    let bytes: Vec<char> = text.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    let digit = |j: usize, from: &[char]| from.get(j).is_some_and(|c| c.is_ascii_digit());
    while i < bytes.len() {
        // 2026-09-24T16:03:42Z (and with fractional seconds)
        let iso = (0..4).all(|k| digit(i + k, &bytes))
            && bytes.get(i + 4) == Some(&'-')
            && bytes.get(i + 10) == Some(&'T')
            && bytes.get(i + 13) == Some(&':');
        if iso {
            let mut j = i + 19;
            while bytes
                .get(j)
                .is_some_and(|c| c.is_ascii_digit() || *c == '.')
            {
                j += 1;
            }
            if bytes.get(j) == Some(&'Z') {
                out.push_str("<time>");
                i = j + 1;
                continue;
            }
        }
        // 20260924T160342Z, then -<32 hex> for a journal id, or -<9 digits> for a backup
        let stamp = (0..8).all(|k| digit(i + k, &bytes))
            && bytes.get(i + 8) == Some(&'T')
            && (9..15).all(|k| digit(i + k, &bytes))
            && bytes.get(i + 15) == Some(&'Z');
        if stamp {
            let mut j = i + 16;
            if bytes.get(j) == Some(&'-') {
                let mut k = j + 1;
                while bytes.get(k).is_some_and(|c| c.is_ascii_hexdigit()) {
                    k += 1;
                }
                if k - j - 1 == 32 {
                    out.push_str("<journal>");
                    i = k;
                    continue;
                }
                if k - j - 1 == 9 {
                    j = k;
                }
            }
            out.push_str("<stamp>");
            i = j;
            continue;
        }
        out.push(bytes[i]);
        i += 1;
    }
    out
}

fn normalize(case: &Case, text: &str) -> String {
    let (uid, gid) = hostroot::ids(&case.root);
    let mut text = text
        .replace(&case.root.dir.display().to_string(), "<root>")
        .replace(&case.base().display().to_string(), "<fake>")
        .replace(
            &format!("lodi {}", lodi::schema::LODI_VERSION),
            &format!("lodi {RECORDED}"),
        )
        .replace(
            &format!("\"lodiVersion\":\"{}\"", lodi::schema::LODI_VERSION),
            &format!("\"lodiVersion\":\"{RECORDED}\""),
        );
    text = mask_times(&text);
    for (prefix, id) in [("\"uid\":", uid), ("\"gid\":", gid), ("\"euid\":", uid)] {
        text = text.replace(&format!("{prefix}{id}"), &format!("{prefix}<id>"));
    }
    text.replace(&format!("owner {uid}:{gid}"), "owner <uid>:<gid>")
        .replace(&format!("\"owner\": \"{uid}\""), "\"owner\": \"<uid>\"")
        .replace(&format!("\"group\": \"{gid}\""), "\"group\": \"<gid>\"")
        .replace(&format!("owner = \"{uid}\""), "owner = \"<uid>\"")
        .replace(&format!("group = \"{gid}\""), "group = \"<gid>\"")
}

/// One walk: plan, apply, the lock and the journal it left, and the plan after it.
fn compat_walk(case: &Case) -> String {
    let binary = compat_binary();
    // The one line an earlier release's `[files]` manifest prints now (si-1) is taken out.
    let legacy = !compat_recording() && compat::has_files_table(case);
    let run = |label: &str, verb: &str| {
        let output = case.verb_by(&binary, verb, &[]);
        format!(
            "== {label}: exit {:?}\n-- stdout\n{}-- stderr\n{}",
            output.status.code(),
            out(&output),
            compat::without_legacy_warning(&err(&output), legacy)
        )
    };
    let mut transcript = run("plan", "plan");
    transcript.push_str(&run("apply", "apply"));
    let lock = case.root.read("etc/lodi/host.lock");
    let journal = journals(&case.root)
        .first()
        .map(|path| fs::read_to_string(path).unwrap())
        .unwrap_or_default();
    transcript.push_str(&format!("== host.lock\n{lock}\n== journal\n{journal}"));
    transcript.push_str(&run("plan after", "plan"));
    normalize(case, &transcript)
}

/// The names a committed import manifest declares, each offered by the fake machine.
fn declared_names(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim();
        if line.starts_with("  \"") && trimmed.ends_with("\",") {
            let name = trimmed.trim_end_matches(',').trim_matches('"').to_string();
            if !names.contains(&name) {
                names.push(name);
            }
        }
    }
    names
}

fn compat_check(name: &str, transcript: &str) {
    let path = repo().join(COMPAT).join(format!("{name}.txt"));
    if compat_recording() {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, transcript).unwrap();
        return;
    }
    let golden = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e}; record it (README)", path.display()));
    // A committed import manifest's comments are this build's, so its digest is masked (si-1).
    assert_eq!(
        compat::mask_manifest_digest(transcript),
        compat::mask_manifest_digest(&golden),
        "{name}: this build differs from 1.2.0 ({})",
        path.display()
    );
}

#[test]
fn compat_1_2_every_committed_host_manifest_plans_and_applies_as_1_2_did() {
    let fixtures = repo().join("tests/fixtures/host/import");
    let mut walked = 0;
    let mut dirs: Vec<PathBuf> = Vec::new();
    for distro in fs::read_dir(&fixtures).unwrap().flatten() {
        if !distro.path().is_dir() {
            continue;
        }
        for scenario in fs::read_dir(distro.path()).unwrap().flatten() {
            if scenario.path().join("expected.toml").is_file() {
                dirs.push(scenario.path());
            }
        }
    }
    dirs.sort();
    for dir in dirs {
        let distro = dir
            .parent()
            .unwrap()
            .file_name()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        let scenario = dir.file_name().unwrap().to_string_lossy().into_owned();
        let label = format!("{distro}-{scenario}");
        let arch = distro == "arch";
        // Arch import now writes a different snapshot and comment. Keep the pre-change
        // input this golden measured; an unpinned walk must not silently re-record it.
        let input = if arch {
            repo()
                .join("tests/fixtures/host/compat-1.3")
                .join(format!("{label}.toml"))
        } else {
            dir.join("expected.toml")
        };
        let text = fs::read_to_string(input).unwrap();
        let mut machine = if arch {
            Machine::arch()
        } else {
            Machine::debian()
        };
        for name in declared_names(&text) {
            if !machine.installed.iter().any(|p| p.name == name) {
                machine = machine.offering(Pkg::new(&name).repo(Some(if arch {
                    "extra"
                } else {
                    "main"
                })));
            }
        }
        let case = Case::new(&format!("compat-{label}"), machine);
        if let Some(release) = distro.strip_prefix("ubuntu-") {
            let codename = text
                .lines()
                .find_map(|line| line.strip_prefix("# distribution: ubuntu ("))
                .and_then(|rest| rest.strip_suffix(')'))
                .expect("an ubuntu codename");
            case.root.write(
                "etc/os-release",
                &format!(
                    "NAME=\"Ubuntu\"\nID=ubuntu\nID_LIKE=debian\nVERSION_ID=\"{release}\"\n\
                     VERSION_CODENAME={codename}\n"
                ),
            );
        }
        // The unpinned form of the file: its `[host] snapshot` is live since M-Pin (LD-395's
        // D-A), and what this walk holds to 1.2 is a manifest with nothing pinned, with the
        // minimum the import wrote before 1.4.0 (LD-398).
        // Nor the [system] table the import writes since si-1, which 1.2 did not know.
        case.set_manifest(
            &compat::without_system(&fakehost::without_snapshot(&text)).replace(
                "min_lodi_version = \">=1.4.0\"\n",
                "min_lodi_version = \">=1.1.1\"\n",
            ),
        );
        compat_check(&label, &compat_walk(&case));
        walked += 1;
    }
    // Twelve at LD-365, five from LD-367, two ambiguous-attribution scenarios from si-1's
    // validator repair, and two extra-suite scenarios from LD-414.
    assert_eq!(walked, 23, "every committed host manifest is walked");
}

#[test]
fn compat_1_2_a_files_manifest_plans_and_applies_as_1_2_did() {
    let case = Case::new(
        "compat-files",
        Machine::debian().offering(Pkg::new("tree").repo(Some("main"))),
    );
    let (uid, gid) = hostroot::ids(&case.root);
    case.root.write("etc/app.conf", "the machine's own\n");
    case.root.write("etc/lodi/files/app.conf", "declared\n");
    case.set_manifest(&format!(
        "[host]\nversion = \"1\"\ndistro = \"debian\"\npackages = \"managed\"\n\n\
         [packages]\ncommon = [\"tree\"]\n\n\
         [files.\"/etc/motd\"]\ncontent = \"hello\\n\"\nowner = \"{uid}\"\ngroup = \"{gid}\"\n\n\
         [files.\"/etc/app.conf\"]\nsource = \"files/app.conf\"\nmode = \"0600\"\n\
         owner = \"{uid}\"\ngroup = \"{gid}\"\n"
    ));
    compat_check("files", &compat_walk(&case));
}
