//! M-Import T-3: the host scope's import is reachable, and what it reaches is bounded. Since
//! LD-522 it is 2.0's `lodi import --yes [PATH]`, on a terminal through the fake machine's stub
//! elevators (`tests/support/fakehost.rs`), landing a flat config.
//!
//! T-1 and T-2 landed the import core and the configuration capture as a **library**: no command
//! reached them, so nothing they could do was yet something a person could ask for. This file is
//! the other side of that. It drives the **real binary** as a child process against scratch roots
//! below `CARGO_TARGET_TMPDIR`, offline, guestless and with a `PATH` that holds the test's own
//! shims and the fake's stub elevators alone. No package manager runs on this machine and none could — this
//! machine has none and must never get one (`AGENTS.md` §8) — and **no `lodi host` command in this
//! file is run against `/`**, with or without a flag, which `python3 -B scripts/check-host-safety.py`
//! is a gate step to keep true.
//!
//! # The two things every case asserts
//!
//! 1. **the exit status and the code**, from a real run of the real binary;
//! 2. **that the machine did not move**, from a full census — relative path, type, mode, size
//!    and **nanosecond** mtime of every object below the root but the person's home (where the
//!    config lands) and the record of the host an import leaves (`etc/lodi/host.lock`) — taken
//!    before the command and again after. Acceptance row (h) is that census: an import reads a
//!    machine and writes nothing else to it, and a mode or an mtime is where a write that touched
//!    nothing else would still show.
//!
//! The recordings under `tests/fixtures/host/import/` are the hand-authored ones T-1 and T-2
//! committed, whose `PROVENANCE.json` says they were written from public package metadata and
//! captured from no machine. The shims replay them with shell builtins alone, so a child's `PATH`
//! can hold nothing but the shim directory and there is no way for a real program to be reached.

#[path = "support/credentials.rs"]
mod credentials;
#[path = "support/fakehost.rs"]
mod fakehost;
#[path = "support/hostroot.rs"]
mod hostroot;
/// The suite's one wait ceiling, declared once at this binary's root (`tests/support/wait.rs`,
/// LD-286): `hostroot.rs` is included by `#[path]` and takes the helper from here.
#[path = "support/wait.rs"]
mod wait;

mod support;

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::{MetadataExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::Output;

/// The names this test gives the invoking user and group inside its scratch roots. They are
/// invented: no real user name, group name or home path is ever written into a root here.
const OWNER: &str = "lodi-test-owner";
const GROUP: &str = "lodi-test-group";

/// A host name planted in every root, so that "the emitted bytes carry no host name" is asserted
/// against a machine that really has one.
const HOST_NAME: &str = "a-machine-that-was-read";

/// The first line of every manifest the emitter writes.
const GENERATED: &str = "# Generated by lodi from one machine's own package database.";

/// The emitted text with its one `[system]` hostname line taken out: since si-1 (LD-421) the
/// host name is a typed setting, written there once and nowhere else.
fn without_hostname(written: &str) -> String {
    let line = format!("hostname = \"{HOST_NAME}\"\n");
    assert_eq!(written.matches(&line).count(), 1, "{written}");
    written.replace(&line, "")
}

fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/host/import")
}

fn uid() -> u32 {
    fs::metadata(env!("CARGO_MANIFEST_DIR"))
        .expect("the checkout")
        .uid()
}

fn gid() -> u32 {
    fs::metadata(env!("CARGO_MANIFEST_DIR"))
        .expect("the checkout")
        .gid()
}

// ------------------------------------------------------------------------------ the case ---

/// One fake machine (`tests/support/fakehost.rs`), one scenario's recordings, and a shim
/// directory of this case's own in front of the fake's stub elevators.
///
/// Every case builds its own shims with the fixture directory written into them, so no state
/// travels between cases and nothing has to be serialized: two cases can run at once and neither
/// can see the other's recordings.
struct Case {
    host: fakehost::Case,
    /// The one directory of programs a child's `PATH` holds beside the stub elevators.
    bin: PathBuf,
    /// Where the shims append their argv.
    log: PathBuf,
    /// Somewhere that is not below the root.
    outside: PathBuf,
}

impl Case {
    fn new(name: &str, scenario: &str) -> Case {
        let fixtures = fixtures_root().join("debian-12").join(scenario);
        assert!(
            fixtures.is_dir(),
            "the recordings {} are not there",
            fixtures.display()
        );
        let host = fakehost::Case::new(&format!("import-cli-{name}"), fakehost::Machine::debian());
        let root = &host.root;
        root.write(
            "etc/os-release",
            &fs::read_to_string(fixtures_root().join("debian-12").join("os-release"))
                .expect("the os-release recording"),
        );
        root.write("etc/hostname", &format!("{HOST_NAME}\n"));
        // The root's own passwd and group name the invoking user, because every file this test
        // creates is owned by them and the capture refuses an owner the root does not name.
        root.write(
            "etc/passwd",
            &format!(
                "root:x:0:0:root:/root:/bin/sh\n{OWNER}:x:{}:{}::/home:/bin/sh\n",
                uid(),
                gid()
            ),
        );
        root.write("etc/group", &format!("root:x:0:\n{GROUP}:x:{}:\n", gid()));
        // The owner agreed once (#705): the marker in place before any census is taken.
        root.write("etc/lodi/may-manage", "")
            .chmod("etc/lodi/may-manage", 0o644);

        let base = host.base().join("import-cli");
        let (bin, outside) = (base.join("bin"), base.join("outside"));
        fs::create_dir_all(&bin).expect("the shim directory");
        fs::create_dir_all(&outside).expect("a directory outside the root");
        let log = base.join("argv.log");
        write_shims(&bin, &log, &fixtures);
        Case {
            host,
            bin,
            log,
            outside,
        }
    }

    /// `PATH`: the fake's stub elevators, then the shim directory and nothing else, so the only
    /// programs `lodi` can resolve are this test's.
    fn path(&self) -> String {
        format!(
            "{}:{}",
            self.host.base().join("elevators").display(),
            self.bin.display()
        )
    }

    /// `lodi import --yes EXTRA --root ROOT` on a terminal, as a person runs it.
    fn import(&self, extra: &[&str]) -> Output {
        self.run_with_path(&self.path(), "import", extra)
    }

    /// `lodi switch --host --dry-run --root ROOT`, the 1.x plan.
    fn plan(&self) -> Output {
        self.run_with_path(&self.path(), "plan", &[])
    }

    /// A 1.x host verb's name, run as its 2.0 command with a `PATH` the caller chooses: the stub
    /// elevators alone are the machine with no package manager.
    fn run_with_path(&self, path: &str, verb: &str, extra: &[&str]) -> Output {
        self.host.verb_env(verb, extra, &[("PATH", path)])
    }

    /// The config folder the import writes when no PATH is typed.
    fn config(&self) -> PathBuf {
        self.host.config()
    }

    /// A census of the machine: the root less the person's home, where the config and the run's
    /// log land, and less the record of the host an import leaves as a converged switch would
    /// (`etc/lodi/host.lock`, and so `etc/lodi`'s mtime).
    fn machine(&self) -> Census {
        census(&self.host.root.dir)
            .into_iter()
            .filter(|(path, _)| {
                path != "home"
                    && !path.starts_with("home/")
                    && path != "etc/lodi"
                    && path != "etc/lodi/host.lock"
            })
            .collect()
    }

    /// Every argv the shims saw, one line per invocation, in order.
    fn argv_log(&self) -> Vec<String> {
        let bytes = fs::read(&self.log).unwrap_or_default();
        String::from_utf8_lossy(&bytes)
            .split('\u{1e}')
            .filter(|record| !record.is_empty())
            .map(|record| record.split('\u{1f}').collect::<Vec<&str>>().join(" "))
            .collect()
    }
}

/// One shim per program either family can reach for, replaying one scenario.
///
/// The bodies use **shell builtins only** — `read`, `printf`, `case` — so a child's `PATH` can
/// hold the shim directory alone. A shim that needed `cat` would need a `PATH` with the real
/// system's `bin` directories on it, and then `lodi` could resolve a real package manager.
/// Written under [`fakehost::writing`]: a child forked while another case's shim is still open
/// for writing would hold that open file until it execs, and a shim run in that instant fails
/// with ETXTBSY ("Text file busy").
fn write_shims(bin: &Path, log: &Path, fixtures: &Path) {
    let _writing = fakehost::writing();
    let bodies = [
        // Neither of these is ever reached by an import, and that is the point: one that were
        // would be in the log, and `nothing_the_command_runs_mutates_the_machine` says which.
        ("apt-get", "exit 0\n"),
        ("dpkg", "exit 0\n"),
        (
            "dpkg-query",
            "case \"$*\" in\n\
             *Conffiles*) emit conffiles.txt ;;\n\
             *Priority*) emit dpkg-survey.txt ;;\n\
             *) emit dpkg-query.txt ;;\n\
             esac\n",
        ),
        // `apt-cache policy` answers two questions from one subcommand: with names, each one's
        // version table; with none, the release fields of every enabled source. R-2 reads both.
        (
            "apt-cache",
            "names=0; skip=0\n\
             for a in \"$@\"; do\n\
             \x20 if [ \"$skip\" = 1 ]; then skip=0; continue; fi\n\
             \x20 case \"$a\" in\n\
             \x20 policy) ;;\n\
             \x20 -o) skip=1 ;;\n\
             \x20 -*) ;;\n\
             \x20 *) names=1 ;;\n\
             \x20 esac\n\
             done\n\
             case \"$1\" in\n\
             policy)\n\
             \x20 if [ \"$names\" = 1 ]; then\n\
             \x20   emit policy.txt\n\
             \x20 else\n\
             \x20   emit policy-release.txt\n\
             \x20 fi ;;\n\
             esac\n",
        ),
        (
            "apt-mark",
            "case \"$1\" in\n\
             showauto) emit apt-mark-showauto.txt ;;\n\
             showhold) emit apt-mark-showhold.txt ;;\n\
             esac\n",
        ),
        ("pacman", "exit 0\n"),
        // The plan of an imported `[system]` keymap reads it back (si-1): the layout
        // `etc/default/keyboard` holds in `write_the_configuration`.
        (
            "localectl",
            "case \"$*\" in\n\
             *status*) printf 'System Locale: LANG=C.UTF-8\\n   X11 Layout: us\\n' ;;\n\
             *) exit 1 ;;\n\
             esac\n",
        ),
    ];
    for (name, body) in bodies {
        let script = format!(
            "#!/bin/sh\n\
             # A test-owned shim of tests/host_import_cli.rs. It logs its argv and replays a\n\
             # hand-authored recording with shell builtins alone. No package manager runs here.\n\
             fixtures='{fixtures}'\n\
             emit() {{ while IFS= read -r line; do printf '%s\\n' \"$line\"; done < \"$fixtures/$1\"; }}\n\
             {{ printf '%s' '{name}'\n\
             \x20 for a in \"$@\"; do printf '\\037%s' \"$a\"; done\n\
             \x20 printf '\\036'; }} >> '{log}'\n\
             {body}",
            fixtures = fixtures.display(),
            log = log.display(),
        );
        let path = bin.join(name);
        fs::write(&path, script).expect("a shim");
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).expect("a shim mode");
    }
}

// ----------------------------------------------------------------------------- the census ---

/// One object below a root: its type, its mode, its size and its mtime to the nanosecond.
type Census = BTreeMap<String, String>;

/// A full census of `root`, which is acceptance row (h)'s whole instrument. Symbolic links are
/// recorded, never followed, and the nanoseconds are what makes a rewrite with identical bytes
/// visible.
fn census(root: &Path) -> Census {
    fn visit(base: &Path, dir: &Path, out: &mut Census) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let Ok(meta) = path.symlink_metadata() else {
                continue;
            };
            let kind = if meta.is_dir() {
                "dir"
            } else if meta.is_symlink() {
                "link"
            } else {
                "file"
            };
            let rel = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .display()
                .to_string();
            out.insert(
                rel,
                format!(
                    "{kind} {:04o} {} {}.{:09}",
                    meta.permissions().mode() & 0o7777,
                    meta.size(),
                    meta.mtime(),
                    meta.mtime_nsec(),
                ),
            );
            if meta.is_dir() {
                visit(base, &path, out);
            }
        }
    }
    let mut out = Census::new();
    visit(root, root, &mut out);
    assert!(
        !out.is_empty(),
        "a census of {} found nothing",
        root.display()
    );
    out
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

/// The seven configuration files the capture scenario judges, written as real files with real
/// modes. One is refused for its mode, one is unmodified and so never a candidate, and the other
/// five are world-readable and on no list of `src/hostscope/import/files.rs`, so they are taken.
fn write_the_configuration(case: &Case) {
    case.host
        .root
        .write("etc/sysctl.d/99-local.conf", "vm.swappiness = 10\n")
        .chmod("etc/sysctl.d/99-local.conf", 0o644);
    case.host
        .root
        .write("etc/ca-certificates.conf", "!mozilla/Local_CA.crt\n")
        .chmod("etc/ca-certificates.conf", 0o644);
    // Refused for its mode: not readable by other, so it is never opened.
    case.host
        .root
        .write("etc/openvpn/client.conf", "remote vpn.invalid 1194\n")
        .chmod("etc/openvpn/client.conf", 0o600);
    // Not refused: none of the three is on the hard path list (`NEVER_CAPTURED`) or under a
    // directory or ending it names, so each is captured because it is world-readable.
    case.host
        .root
        .write("etc/ssh/sshd_config", "PermitRootLogin no\n")
        .chmod("etc/ssh/sshd_config", 0o644);
    case.host
        .root
        .write("etc/resolv.conf", "nameserver 192.0.2.1\n")
        .chmod("etc/resolv.conf", 0o644);
    case.host
        .root
        .write("etc/nslcd.conf", "uri ldap://ldap.invalid\n")
        .chmod("etc/nslcd.conf", 0o644);
    // Unmodified: equal to the bytes its package shipped, so not a candidate at all.
    case.host.root.write(
        "etc/default/keyboard",
        "# keyboard defaults\nXKBMODEL=\"pc105\"\nXKBLAYOUT=\"us\"\n",
    );
}

/// Every tracked file of the `refusals` recording, written as a real, world-readable, modified
/// file. Each one is a candidate the policy must turn away by name.
fn write_the_refusables(case: &Case) {
    for rel in [
        "etc/apt/auth.conf",
        "etc/apt/auth.conf.d/90local",
        "etc/crypttab",
        "etc/fstab",
        "etc/gshadow",
        "etc/krb5.keytab",
        "etc/machine-id",
        "etc/netrc",
        "etc/NetworkManager/system-connections/home.nmconnection",
        "etc/pacman.d/gnupg/pubring.conf",
        "etc/pacman.d/mirrorlist",
        "etc/pki/client.p12",
        "etc/shadow",
        "etc/ssh/ssh_host_ed25519_key",
        "etc/ssl/private/site.conf",
        "etc/subgid",
        "etc/subuid",
        "etc/sudoers.d/90-local",
        "etc/wpa_supplicant/wpa_supplicant.conf",
        "usr/local/etc/outside.conf",
    ] {
        case.host
            .root
            .write(rel, "# changed since the package shipped it\n")
            .chmod(rel, 0o644);
    }
}

// ------------------------------------------------------------- (d) no package manager ---

/// Acceptance (d): an armed root whose distribution's package manager is not on `PATH` is
/// `E_NO_RUNTIME` at exit 7. The `PATH` here is empty, so nothing on this machine is reachable.
#[test]
fn an_armed_root_with_no_package_manager_is_no_runtime() {
    let case = Case::new("no-runtime", "capture");
    let before = case.machine();
    let elevators = case.host.base().join("elevators").display().to_string();
    let out = case.run_with_path(&elevators, "import", &[]);
    assert_eq!(out.status.code(), Some(7), "{}", stderr(&out));
    assert!(stderr(&out).contains("E_NO_RUNTIME"), "{}", stderr(&out));
    assert!(stdout(&out).is_empty(), "{}", stdout(&out));
    assert_eq!(before, case.machine(), "the root moved");
    assert!(!case.host.root.exists("etc/lodi/host.lock"));
}

// ------------------------------------------------------ (e) PATH inside the scope's own ---

/// Acceptance (e): a PATH that resolves inside a folder lodi keeps for the host itself
/// (`etc/lodi`, `var/lib/lodi` below the root) is `E_STORE_IO` at exit 6 and writes nothing —
/// including through a `..` and a symbolic link, because a refusal a `..` could walk around would
/// not be one. Nothing is read: no shim and no elevator runs.
#[test]
fn out_inside_a_directory_the_scope_owns_is_store_io_and_writes_nothing() {
    let case = Case::new("out-owned", "capture");
    write_the_configuration(&case);
    let link = case.outside.join("into-the-root");
    std::os::unix::fs::symlink(case.host.root.path("etc/lodi"), &link).expect("a link");

    let spellings = [
        case.host.root.path("etc/lodi").display().to_string(),
        case.host
            .root
            .path("etc/lodi/captured")
            .display()
            .to_string(),
        case.host
            .root
            .path("var/lib/lodi/host")
            .display()
            .to_string(),
        format!("{}/etc/lodi/../lodi/deeper", case.host.root.dir.display()),
        link.display().to_string(),
    ];
    for out in spellings {
        let before = census(&case.host.root.dir);
        let output = case.import(&[&out]);
        assert_eq!(
            output.status.code(),
            Some(6),
            "{out} was not refused:\n{}",
            stderr(&output)
        );
        assert!(
            stderr(&output).contains("E_STORE_IO"),
            "{out}:\n{}",
            stderr(&output)
        );
        assert!(stdout(&output).is_empty(), "{}", stdout(&output));
        assert_eq!(before, census(&case.host.root.dir), "{out} moved the root");
    }
    // The refusal is decided before the machine is read: nothing ran at all.
    assert!(
        case.argv_log().is_empty(),
        "a refused PATH ran {:?}",
        case.argv_log()
    );
    assert!(
        case.host.elevator_calls().is_empty(),
        "a refused PATH ran {:?}",
        case.host.elevator_calls()
    );
}

// --------------------------------------------------------------- W_UNCAPTURED on stderr ---

/// Every refusal is one `W_UNCAPTURED` line on **standard error**, and none of them changes the
/// exit status: an import that refuses everything it was offered still exits 0.
///
/// The `refusals` recording is the one whose every tracked file is on the hard path list, is a
/// key, or is outside `/etc` altogether — the class of file the policy exists for.
#[test]
fn refusals_are_warnings_on_standard_error_and_change_no_exit_status() {
    let case = Case::new("refusals", "refusals");
    write_the_refusables(&case);
    let out_dir = case.config();
    let before = case.machine();

    let out = case.import(&[]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    let warnings: Vec<&str> = text
        .lines()
        .filter(|line| line.starts_with("W_UNCAPTURED"))
        .collect();
    assert!(
        warnings.len() >= 10,
        "every hard-list candidate should have spoken:\n{text}"
    );
    for refused in [
        "/etc/netrc",
        "/etc/pacman.d/mirrorlist",
        "/etc/sudoers.d/90-local",
        "/etc/shadow",
        "/etc/ssl/private/site.conf",
        "/etc/ssh/ssh_host_ed25519_key",
        "/etc/pki/client.p12",
        "/usr/local/etc/outside.conf",
    ] {
        assert!(
            warnings.iter().any(|line| line.contains(refused)),
            "{refused} was refused without saying so:\n{text}"
        );
    }
    // A warning never reaches standard output.
    assert!(!stdout(&out).contains("W_UNCAPTURED"), "{}", stdout(&out));
    // Nothing was captured, so the manifest declares no file and the bundle is not there.
    let written = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    assert!(!written.contains("[files."), "{written}");
    assert!(
        !out_dir.join("files").exists(),
        "a refused file was written out"
    );
    assert_eq!(before, case.machine(), "the root moved");
}

/// The real command copies no file from `/etc` (si-1): each file of
/// `tests/support/credentials.rs` is one `W_UNCAPTURED` line naming the file, no bundle is
/// written, and no fake value reaches standard output, standard error or the manifest.
#[test]
fn a_credential_in_any_shape_never_leaves_the_file() {
    let case = Case::new("credentials", "credentials");
    let shapes = credentials::shapes();
    for (index, shape) in shapes.iter().enumerate() {
        let rel = format!("etc/credential-shapes/{index:02}.conf");
        case.host.root.write(&rel, &shape.text).chmod(&rel, 0o644);
    }
    let benign = "etc/credential-shapes/benign.conf";
    case.host
        .root
        .write(benign, credentials::BENIGN)
        .chmod(benign, 0o644);
    let out_dir = case.config();

    let out = case.import(&[]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    // Since si-1 no file is copied from /etc: each changed file is named, and none travels.
    for index in 0..shapes.len() {
        let path = format!("/etc/credential-shapes/{index:02}.conf");
        assert!(
            text.lines().any(|line| line.starts_with("W_UNCAPTURED")
                && line.contains(&format!("{path} is not captured"))),
            "{path} was not named:\n{text}"
        );
    }
    let manifest = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    assert!(!manifest.contains("[files."), "{manifest}");
    assert!(
        !out_dir.join("files").exists(),
        "a file was copied from /etc"
    );
    for shape in &shapes {
        for text in [&stdout(&out), &text, &manifest] {
            assert!(
                !text.contains(&shape.fake),
                "{}: the fake value left the file:\n{text}",
                shape.name
            );
        }
    }
}

// ------------------------------------------------- (h) the command writes nothing, ever ---

/// Acceptance (h), taken as a whole: every shape of the invocation, against one root, with one
/// census before the first and one after the last.
///
/// It also asserts what the command **ran**: every argv the shims saw is a read. An import that
/// installed, removed, marked or refreshed anything would be in this log, and the assertion names
/// the command that was not a read.
#[test]
fn nothing_the_command_runs_mutates_the_machine() {
    let case = Case::new("census", "capture");
    write_the_configuration(&case);
    let typed = case.host.root.path("home/typed").display().to_string();
    let before = case.machine();

    // Every shape: shown, landed in the standard folder, landed where typed, and refused for
    // a folder that already has a host.
    for args in [vec!["--dry-run"], vec![], vec![typed.as_str()], vec![]] {
        let output = case.import(&args);
        assert!(
            matches!(output.status.code(), Some(0) | Some(3)),
            "`lodi {}` exited {:?}:\n{}",
            args.join(" "),
            output.status.code(),
            stderr(&output)
        );
    }
    assert_eq!(
        before,
        case.machine(),
        "an import changed the machine it read"
    );

    let log = case.argv_log();
    assert!(!log.is_empty(), "the shims saw nothing at all");
    for record in &log {
        let program = record.split(' ').next().unwrap_or_default();
        assert!(
            matches!(program, "dpkg-query" | "apt-cache" | "apt-mark"),
            "an import ran `{record}`, which is not one of its reads"
        );
        for verb in ["install", "remove", "purge", "update", "upgrade", "hold"] {
            assert!(
                !record.split(' ').any(|word| word == verb),
                "an import ran `{record}`"
            );
        }
    }
}

// ------------------------------------------------ R-2, acceptance (3): the package lines ---

/// Every package the emitted file names but does not declare is one `W_UNCAPTURED` line on
/// standard error, in the order the file names them; the file's own refusals follow; the report
/// line states both counts; and the exit status is 0.
///
/// The `off-base` recording is the machine R-2 is about: a third-party package, a PPA package
/// and a hand-installed one, none of which a fresh machine could install, beside two names it
/// could. Before R-2 all five were declared and the restore stopped at `E_UNKNOWN_PACKAGE`.
#[test]
fn every_package_left_out_is_one_warning_on_standard_error_and_the_exit_is_zero() {
    let case = Case::new("offbase", "off-base");
    let out_dir = case.config();

    let out = case.import(&[]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    let warnings: Vec<&str> = text
        .lines()
        .filter(|line| line.starts_with("W_UNCAPTURED"))
        .collect();
    assert_eq!(
        warnings,
        vec![
            "W_UNCAPTURED: docker-ce is not declared: it is installed from Docker, \
             bookworm/stable, which is not debian's own repository",
            "W_UNCAPTURED: lodi-agent is not declared: it is installed from \
             LP-PPA-lodi-testing, noble/main, which is not debian's own repository",
            "W_UNCAPTURED: lodi-hand-built is not declared: its installed version is known \
             only to this machine's own package database: a package file installed by hand, \
             or a source this machine no longer has",
        ],
        "one line per left-out package, in the emitted file's order:\n{text}"
    );

    // The report line states both counts. It is a `wrote …` line, which every command of this
    // build puts on standard output, and the warnings it counts are on standard error.
    let told = stdout(&out);
    let report: Vec<&str> = told
        .lines()
        .filter(|line| line.contains("host.toml:"))
        .collect();
    assert_eq!(report.len(), 1, "{told}");
    assert!(
        report[0].ends_with(
            "host.toml: 2 package(s) declared, 3 not captured; read NOT CAPTURED in it first"
        ),
        "{told}"
    );
    assert!(!told.contains("W_UNCAPTURED"), "{told}");

    // The declarations and the repositories part (LD-367) are in the file it wrote.
    let written = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    for shared in [
        "common = [\n  \"golang-1.22\",\n  \"ripgrep\",\n]\n",
        "#   docker-ce               Docker, bookworm/stable\n",
        "#   lodi-agent              LP-PPA-lodi-testing, noble/main\n",
        "#     unattributed: no enabled repository offers the installed version (a package \
         file, or a repository since removed)\n",
    ] {
        assert!(written.contains(shared), "{written}");
    }
}

/// The specimen of `W_UNCHECKED_ORIGIN`, from a real run of the built binary: the machine with
/// no package index at all. It is printed **once**, before any `W_UNCAPTURED` line — there are
/// none, because nothing was left out — the report line counts nothing not captured, and the
/// exit status is 0.
#[test]
fn a_machine_with_no_index_warns_once_and_leaves_nothing_out() {
    let case = Case::new("offindex", "off-index");
    let out_dir = case.config();

    let out = case.import(&[]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    let unchecked: Vec<&str> = text
        .lines()
        .filter(|line| line.starts_with("W_UNCHECKED_ORIGIN"))
        .collect();
    assert_eq!(
        unchecked,
        vec![
            "W_UNCHECKED_ORIGIN: this machine has no package index, so where the declared \
             names came from was not checked: every name is declared as read. Fetch the index \
             and import again to have the names no base repository serves named instead.",
        ],
        "once per run, about the machine and no package:\n{text}"
    );
    assert!(
        !text.contains("W_UNCAPTURED"),
        "nothing was left out, so nothing is uncaptured:\n{text}"
    );

    let told = stdout(&out);
    let report: Vec<&str> = told
        .lines()
        .filter(|line| line.contains("host.toml:"))
        .collect();
    assert_eq!(report.len(), 1, "{told}");
    assert!(
        report[0].ends_with(
            "host.toml: 5 package(s) declared, 0 not captured; read NOT CAPTURED in it first"
        ),
        "{told}"
    );

    // The emitted file says the same thing above the list, so a person reading the file alone
    // is told as much as one watching the run.
    let written = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    assert!(
        written.contains("# This machine has no package index: nothing has been fetched from any"),
        "{written}"
    );
    for name in ["docker-ce", "lodi-agent", "lodi-hand-built"] {
        assert!(written.contains(&format!("  \"{name}\",\n")), "{written}");
    }
}

// ------------------------------------------ LD-325: with no flag, the import lands in place ---

/// With no flag the manifest lands at `etc/lodi/host.toml` below the root, at 0644 and owned by
/// the invoking user, the captured bytes land under `etc/lodi/files/`, one line names both and
/// the next command, and the plan that follows resolves every `source` the manifest declares.
///
/// Before LD-325 the same invocation printed the manifest and wrote nothing, so every assertion
/// on the landed files here fails against that build.
#[test]
fn with_no_flag_the_import_lands_in_place_and_plan_resolves_every_source() {
    let case = Case::new("in-place", "capture");
    write_the_configuration(&case);
    let before = case.machine();

    let out = case.import(&[]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let manifest = case.config().join("host.toml");
    // What it wrote and what to read first, then the next command, which writes nothing.
    let told = stdout(&out);
    let lines: Vec<&str> = told.lines().collect();
    assert_eq!(lines.len(), 2, "two lines:\n{told}");
    assert!(
        lines[0].starts_with(&format!("wrote {}: ", manifest.display())),
        "{told}"
    );
    assert!(
        lines[0].ends_with("not captured; read NOT CAPTURED in it first"),
        "{told}"
    );
    assert_eq!(
        lines[1],
        format!(
            "next: review {}, commit it, then run lodi switch --dry-run",
            case.config().display()
        ),
        "{told}"
    );

    let meta = fs::symlink_metadata(&manifest).expect("the manifest landed");
    assert!(meta.file_type().is_file());
    assert_eq!(meta.permissions().mode() & 0o7777, 0o644);
    assert_eq!((meta.uid(), meta.gid()), (uid(), gid()));
    let written = fs::read_to_string(&manifest).unwrap();
    assert!(written.starts_with(GENERATED), "{written}");
    assert!(!without_hostname(&written).contains(HOST_NAME), "{written}");
    assert!(!written.contains("[files."), "{written}");
    assert!(
        written.contains("[etc.\"sysctl.d/99-local.conf\"]"),
        "{written}"
    );
    assert!(
        !case.config().join("files").exists(),
        "a file was copied from /etc"
    );
    // Below the root only the config, the run's log and the record of the host are new, and
    // nothing that was there moved.
    assert_eq!(before, case.machine(), "the import changed the machine");
    assert!(case.host.root.exists("etc/lodi/host.lock"));

    let plan = case.plan();
    assert_eq!(plan.status.code(), Some(0), "{}", stderr(&plan));
    let text = stderr(&plan);
    assert!(
        !text.contains("E_") && !text.contains("missing"),
        "the plan did not resolve every source:\n{text}\n{}",
        stderr(&plan)
    );
}

/// An import in place declares the `[system]` basics it read — the host name, the time zone and
/// the locale — and records them as a converged apply would, so the plan of the machine it came
/// from is `nothing to do`: no `= hostname` line, and no record-only update (#585).
#[test]
fn an_imported_machine_with_its_basics_plans_nothing_to_do() {
    let case = Case::new("in-place-basics", "capture");
    write_the_configuration(&case);
    case.host.root.write("usr/share/zoneinfo/UTC", "TZif2\n");
    std::os::unix::fs::symlink(
        "../usr/share/zoneinfo/UTC",
        case.host.root.path("etc/localtime"),
    )
    .expect("localtime");
    case.host.root.write("etc/locale.conf", "LANG=C.UTF-8\n");
    let out = case.import(&[]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let written = fs::read_to_string(case.config().join("host.toml")).unwrap();
    for line in ["timezone = \"UTC\"", "locale = \"C.UTF-8\""] {
        assert!(written.contains(line), "{line}: {written}");
    }

    let plan = case.plan();
    assert_eq!(plan.status.code(), Some(0), "{}", stderr(&plan));
    assert!(fakehost::nothing(&plan), "{}", stderr(&plan));
}

/// A symbolic link planted at the config's `host.toml` is `E_PATH_ESCAPE`, one planted as the
/// config folder itself `E_CONFIG`, each at exit 3; nothing is written through it, and the
/// machine is not read.
#[test]
fn a_planted_link_in_the_destination_is_refused() {
    // A linked folder is not a folder to lodi, which reads it without following it.
    for (name, planted, code) in [
        ("link-manifest", "host.toml", "E_PATH_ESCAPE"),
        ("link-dir", "", "E_CONFIG"),
    ] {
        let case = Case::new(name, "capture");
        write_the_configuration(&case);
        let target = case.outside.join("elsewhere");
        fs::create_dir_all(&target).unwrap();
        fs::write(target.join("witness"), "a file the link points beside\n").unwrap();
        let config = case.config();
        let link = if planted.is_empty() {
            config.clone()
        } else {
            config.join(planted)
        };
        fs::create_dir_all(link.parent().unwrap()).unwrap();
        std::os::unix::fs::symlink(&target, &link).expect("a link");
        let target_before = census(&target);
        let before = case.machine();

        let out = case.import(&[]);
        assert_eq!(out.status.code(), Some(3), "{planted}: {}", stderr(&out));
        assert!(stderr(&out).contains(code), "{planted}: {}", stderr(&out));
        assert!(stdout(&out).is_empty(), "{planted}: {}", stdout(&out));
        assert_eq!(
            target_before,
            census(&target),
            "{planted}: wrote through it"
        );
        assert_eq!(before, case.machine(), "{planted}: the root moved");
        assert!(!case.host.root.exists("etc/lodi/host.lock"), "{planted}");
        assert!(
            case.argv_log().is_empty(),
            "{planted}: the machine was read"
        );
    }
}

/// A symbolic link planted at the config's `files` is `E_PATH_ESCAPE` at exit 3 when the host is
/// imported again: nothing is written through it, the machine is not read, and its record
/// (`etc/lodi/host.lock`) is not written.
#[test]
fn a_planted_files_link_in_the_destination_is_refused() {
    // With nothing to write under `files/`, and with a `[sources]` keyring to write there.
    for keyring in [false, true] {
        let case = if keyring {
            sources_case("link-files-keyring").0
        } else {
            let case = Case::new("link-files", "capture");
            write_the_configuration(&case);
            case
        };
        let first = case.import(&[]);
        assert_eq!(first.status.code(), Some(0), "{}", stderr(&first));
        let files = case.config().join("files");
        let _ = fs::remove_dir_all(&files);
        let target = case.outside.join("elsewhere");
        fs::create_dir_all(&target).unwrap();
        fs::write(target.join("witness"), "a file the link points beside\n").unwrap();
        std::os::unix::fs::symlink(&target, &files).expect("a link");
        let target_before = census(&target);
        let before = census(&case.host.root.dir);
        let (ran, elevated) = (case.argv_log().len(), case.host.elevator_calls().len());

        let out = case.import(&[]);
        let err = stderr(&out);
        assert_eq!(out.status.code(), Some(3), "{keyring}: {err}");
        assert!(err.contains("E_PATH_ESCAPE"), "{keyring}: {err}");
        assert!(
            err.contains(&files.display().to_string()),
            "{keyring}: the refusal names the link: {err}"
        );
        assert!(stdout(&out).is_empty(), "{keyring}: {}", stdout(&out));
        assert_eq!(
            target_before,
            census(&target),
            "{keyring}: wrote through it"
        );
        assert_eq!(
            before,
            census(&case.host.root.dir),
            "{keyring}: the root moved"
        );
        assert_eq!(
            case.argv_log().len(),
            ran,
            "{keyring}: the machine was read"
        );
        assert_eq!(
            case.host.elevator_calls().len(),
            elevated,
            "{keyring}: an elevator ran"
        );
    }
}

/// The one `[sources]` case of the CLI: the `sources` scenario's `/etc/apt` copied into the
/// scratch root.
fn sources_case(name: &str) -> (Case, PathBuf) {
    let case = Case::new(name, "sources");
    let fixture_root = fixtures_root().join("debian-12/sources/root");
    copy_tree(&fixture_root, &case.host.root.dir);
    (case, fixture_root)
}

/// The keyring a block names travels at the path its `signed_by` names, byte for byte, beside
/// the manifest wherever the manifest lands — the standard folder's `files/host/` with no PATH,
/// `PATH/files/host/` with one — and never under the root's `etc/lodi/files/`. Nothing of the refused repositories travels: no keyring of theirs, and never a
/// credential file.
#[test]
fn the_keyring_a_sources_block_names_lands_beside_the_manifest_and_nothing_of_the_refused() {
    for in_place in [false, true] {
        let (case, fixture_root) = sources_case(if in_place {
            "sources-in-place"
        } else {
            "sources-out"
        });
        let typed = case.host.root.path("home/typed");
        let typed_arg = typed.display().to_string();
        let extra: &[&str] = if in_place { &[] } else { &[&typed_arg] };
        let output = case.import(extra);
        assert_eq!(output.status.code(), Some(0), "{}", stderr(&output));
        let dir = if in_place {
            case.config()
        } else {
            typed.clone()
        };
        let keyring = dir.join("files/host/etc/apt/keyrings/lodi-docker.asc");
        let bytes = fs::read(&keyring).expect("the keyring travels beside the manifest");
        assert_eq!(
            bytes,
            fs::read(fixture_root.join("etc/apt/keyrings/docker.asc")).unwrap()
        );
        let meta = fs::symlink_metadata(&keyring).unwrap();
        assert_eq!(meta.permissions().mode() & 0o7777, 0o644);
        let written = fs::read_to_string(dir.join("host.toml")).expect("the manifest");
        assert!(
            written.contains(&format!(
                "# signed_by = \"files/host/etc/apt/keyrings/lodi-docker.asc\"\n\
                 # signed_by_sha256 = \"{}\"\n",
                lodi::util::sha256_hex(&bytes)
            )),
            "{written}"
        );
        assert!(
            !written.contains("the keyring was not written"),
            "{written}"
        );
        // No keyring becomes a [files] entry: the block is the keyring's only declaration.
        assert!(!written.contains("[files.\"/etc/apt/keyrings"), "{written}");
        for never in [
            "files/host/etc/apt/keyrings/lodi-idle.gpg",
            "files/host/etc/apt/keyrings/idle.gpg",
            "files/host/etc/apt/keyrings/docker.asc",
            "files/host/etc/apt/auth.conf.d",
            "files/host/etc/apt/sources.list.d",
        ] {
            assert!(!dir.join(never).exists(), "{never} travelled");
        }
        assert!(
            !case.host.root.exists("etc/lodi/files"),
            "the import wrote under the root's etc/lodi/files"
        );
    }
}

/// Rebased onto the landed core, whose keyring sniff refuses a private key block's marker
/// anywhere in the bytes, mid-line included (LD-365's validator repair): the keyring of the one
/// repository the import would otherwise bundle — Docker's, with its packages attributed to it —
/// holding that marker mid-line after an armored public block, or after a binary public-key
/// packet, is refused by the real command as secret key material. No block is written, no
/// keyring lands beside the manifest, and none of its bytes reaches the manifest or either
/// stream.
#[test]
fn a_private_key_block_anywhere_in_a_keyring_the_import_would_bundle_is_never_carried() {
    // Generated framing only, never a key.
    let armored = b"-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nAAAA\n=AAAA\n\
                    comment: -----BEGIN PGP PRIVATE KEY BLOCK----- SECRET-MATERIAL-XYZ\n\
                    -----END PGP PUBLIC KEY BLOCK-----\n"
        .to_vec();
    let mut binary = vec![0xc6, 4, 1, 2, 3, 4];
    binary.extend_from_slice(b"x-----BEGIN PGP PRIVATE KEY BLOCK-----SECRET-MATERIAL-XYZ");
    for (name, bytes) in [
        ("sources-private-armored", armored),
        ("sources-private-binary", binary),
    ] {
        let (case, _) = sources_case(name);
        fs::write(case.host.root.path("etc/apt/keyrings/docker.asc"), &bytes).unwrap();
        let out = case.config();
        let output = case.import(&[]);
        assert_eq!(output.status.code(), Some(0), "{name}: {}", stderr(&output));
        let written = fs::read_to_string(out.join("host.toml")).expect("the import wrote");
        assert!(!written.contains("[sources.docker]"), "{name}: {written}");
        assert!(
            written.contains(
                "#   /etc/apt/sources.list.d/docker.sources\n\
                 #     its keyring holds secret key material, which is never carried\n\
                 #     installed from it: docker-ce, docker-ce-cli\n"
            ),
            "{name}: {written}"
        );
        assert!(
            !out.join("files/host/etc/apt/keyrings").exists(),
            "{name}: a keyring travelled"
        );
        for text in [written, stdout(&output), stderr(&output)] {
            for never in ["SECRET-MATERIAL-XYZ", "PRIVATE KEY BLOCK"] {
                assert!(!text.contains(never), "{name}: {never} reached: {text}");
            }
        }
    }
}

/// The round trip, named: import → uncomment → plan. The bundle the import writes,
/// with its `[sources.docker]` block taken the way a person takes it (every line of the block
/// without its `# `), is copied into the config of a second scratch root — the new machine,
/// which has no Docker stanza of its own — and plans there without error against the test's fake
/// backend, arming the source before the index it forces.
///
/// On the machine it was read from the same block is `E_DUP_RESOURCE` naming the stanza it came
/// from (S7), which is what the block's own comment says.
#[test]
fn round_trip_import_then_uncomment_then_plan() {
    let (case, _) = sources_case("sources-round-trip");
    let out = case.config();
    let import = case.import(&[]);
    assert_eq!(import.status.code(), Some(0), "{}", stderr(&import));
    let written = fs::read_to_string(out.join("host.toml")).expect("the import wrote");
    let mut taken = String::new();
    let mut inside = false;
    for line in written.lines() {
        if line.starts_with("# [sources.") {
            inside = true;
        } else if line.is_empty() {
            inside = false;
        }
        taken.push_str(if inside {
            line.strip_prefix("# ").unwrap_or(line)
        } else {
            line
        });
        taken.push('\n');
    }
    assert!(taken.contains("\n[sources.docker]\n"), "{taken}");
    fs::write(out.join("host.toml"), &taken).unwrap();

    // The new machine: the same recordings, none of the old machine's /etc/apt.
    let fresh = Case::new("sources-round-trip-new", "sources");
    copy_tree(&out, &fresh.config());
    let plan = fresh.plan();
    assert_eq!(
        plan.status.code(),
        Some(0),
        "{}\n{}",
        stdout(&plan),
        stderr(&plan)
    );
    let text = stderr(&plan);
    assert!(!text.contains("E_"), "{text}");
    let source = text
        .find("+ source docker")
        .unwrap_or_else(|| panic!("no source step:\n{text}"));
    let index = text
        .find("~ index")
        .unwrap_or_else(|| panic!("the changing source forced no index:\n{text}"));
    assert!(source < index, "{text}");

    // On the machine it was read from, the stanza it came from lists the same repository.
    let same = case.plan();
    assert_eq!(same.status.code(), Some(3), "{}", stderr(&same));
    assert!(
        stderr(&same).contains("E_DUP_RESOURCE")
            && stderr(&same).contains("/etc/apt/sources.list.d/docker.sources"),
        "{}",
        stderr(&same)
    );
}

/// Copy a fixture subtree into the scratch root, files and directories, nothing else.
fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir_all(to).expect("the target directory");
    for entry in fs::read_dir(from).expect("the fixture subtree").flatten() {
        let target = to.join(entry.file_name());
        if entry.path().is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            fs::copy(entry.path(), &target).expect("a fixture file");
        }
    }
}
