//! M-Import T-3: the host scope's import verb is reachable, and what it reaches is bounded.
//!
//! T-1 and T-2 landed the import core and the configuration capture as a **library**: no command
//! reached them, so nothing they could do was yet something a person could ask for. This file is
//! the other side of that. It drives the **real binary** as a child process against scratch roots
//! below `CARGO_TARGET_TMPDIR`, offline, guestless and with a `PATH` that holds exactly one
//! directory: the test's own shims. No package manager runs on this machine and none could — this
//! machine has none and must never get one (`AGENTS.md` §8) — and **no `lodi host` command in this
//! file is run against `/`**, with or without a flag, which `python3 -B scripts/check-host-safety.py`
//! is a gate step to keep true.
//!
//! # The two things every case asserts
//!
//! 1. **the exit status and the code**, from a real run of the real binary;
//! 2. **that the root did not move**, from a full census — relative path, type, mode, size and
//!    **nanosecond** mtime of every object below it — taken before the command and again after.
//!    Acceptance row (h) is that census: an import reads a machine and writes nothing to it, and a
//!    mode or an mtime is where a write that touched nothing else would still show. The cases of
//!    LD-325, where the no-flag import lands in place, assert instead that every object that
//!    moved is below `etc/lodi/` and that nothing outside it moved.
//!
//! The recordings under `tests/fixtures/host/import/` are the hand-authored ones T-1 and T-2
//! committed, whose `PROVENANCE.json` says they were written from public package metadata and
//! captured from no machine. The shims replay them with shell builtins alone, so a child's `PATH`
//! can hold nothing but the shim directory and there is no way for a real program to be reached.

#[path = "support/credentials.rs"]
mod credentials;
#[path = "support/hostroot.rs"]
mod hostroot;
/// The suite's one wait ceiling, declared once at this binary's root (`tests/support/wait.rs`,
/// LD-286): `hostroot.rs` is included by `#[path]` and takes the helper from here.
#[path = "support/wait.rs"]
mod wait;

mod support;

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::{MetadataExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::RwLock;

use hostroot::Root;

/// The names this test gives the invoking user and group inside its scratch roots. They are
/// invented: no real user name, group name or home path is ever written into a root here.
const OWNER: &str = "lodi-test-owner";
const GROUP: &str = "lodi-test-group";

/// A host name planted in every root, so that "the emitted bytes carry no host name" is asserted
/// against a machine that really has one.
const HOST_NAME: &str = "a-machine-that-was-read";

/// The first line of every manifest the emitter writes.
const GENERATED: &str = "# Generated by lodi from one machine's own package database.";

/// The emitted text with its one `[system]` hostname line taken out: since si-1 (LD-421) the
/// host name is a typed setting, written there once and nowhere else.
fn without_hostname(written: &str) -> String {
    let line = format!("hostname = \"{HOST_NAME}\"\n");
    assert_eq!(written.matches(&line).count(), 1, "{written}");
    written.replace(&line, "")
}

fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/host/import")
}

fn uid() -> u32 {
    fs::metadata(env!("CARGO_MANIFEST_DIR"))
        .expect("the checkout")
        .uid()
}

fn gid() -> u32 {
    fs::metadata(env!("CARGO_MANIFEST_DIR"))
        .expect("the checkout")
        .gid()
}

// ------------------------------------------------------------------------------ the case ---

/// One scratch root, one scenario's recordings, and a shim directory of this case's own.
///
/// Every case builds its own shims with the fixture directory written into them, so no state
/// travels between cases and nothing has to be serialized: two cases can run at once and neither
/// can see the other's recordings.
struct Case {
    root: Root,
    /// The one directory a child's `PATH` holds.
    bin: PathBuf,
    /// Where the shims append their argv.
    log: PathBuf,
    /// Somewhere to put `--out` and `HOME` that is not below the root.
    outside: PathBuf,
}

impl Case {
    fn new(name: &str, scenario: &str) -> Case {
        let fixtures = fixtures_root().join("debian-12").join(scenario);
        assert!(
            fixtures.is_dir(),
            "the recordings {} are not there",
            fixtures.display()
        );
        let root = Root::new(&format!("import-cli-{name}"));
        root.arm();
        root.write(
            "etc/os-release",
            &fs::read_to_string(fixtures_root().join("debian-12").join("os-release"))
                .expect("the os-release recording"),
        );
        root.write("etc/hostname", &format!("{HOST_NAME}\n"));
        // The root's own passwd and group name the invoking user, because every file this test
        // creates is owned by them and the capture refuses an owner the root does not name.
        root.write(
            "etc/passwd",
            &format!(
                "root:x:0:0:root:/root:/bin/sh\n{OWNER}:x:{}:{}::/nonexistent:/bin/sh\n",
                uid(),
                gid()
            ),
        );
        root.write("etc/group", &format!("root:x:0:\n{GROUP}:x:{}:\n", gid()));

        let base = support::scratch(&format!("import-cli-{name}"));
        let (bin, outside) = (base.join("bin"), base.join("outside"));
        fs::create_dir_all(&bin).expect("the shim directory");
        fs::create_dir_all(outside.join("home")).expect("a directory outside the root");
        let log = base.join("argv.log");
        write_shims(&bin, &log, &fixtures);
        Case {
            root,
            bin,
            log,
            outside,
        }
    }

    /// Run the real binary. `PATH` holds the shim directory and nothing else, so the only
    /// programs `lodi` can resolve are this test's.
    fn lodi(&self, args: &[&str]) -> Output {
        self.run_with_path(&self.bin.display().to_string(), args)
    }

    /// The same, with a `PATH` the caller chooses — `""` is the machine with no package manager.
    fn run_with_path(&self, path: &str, args: &[&str]) -> Output {
        let home = self.outside.join("home");
        fs::create_dir_all(&home).expect("a scratch home");
        let _spawning = SHIMS.read().unwrap_or_else(|e| e.into_inner());
        Command::new(env!("CARGO_BIN_EXE_lodi"))
            .args(args)
            .current_dir(&self.outside)
            .env_clear()
            .env("PATH", path)
            .env("HOME", &home)
            .output()
            .expect("the lodi binary runs")
    }

    fn root_arg(&self) -> String {
        self.root.dir.display().to_string()
    }

    fn out_dir(&self) -> PathBuf {
        self.outside.join("captured")
    }

    /// Every argv the shims saw, one line per invocation, in order.
    fn argv_log(&self) -> Vec<String> {
        let bytes = fs::read(&self.log).unwrap_or_default();
        String::from_utf8_lossy(&bytes)
            .split('\u{1e}')
            .filter(|record| !record.is_empty())
            .map(|record| record.split('\u{1f}').collect::<Vec<&str>>().join(" "))
            .collect()
    }
}

/// One shim per program either family can reach for, replaying one scenario.
///
/// The bodies use **shell builtins only** — `read`, `printf`, `case` — so a child's `PATH` can
/// hold the shim directory alone. A shim that needed `cat` would need a `PATH` with the real
/// system's `bin` directories on it, and then `lodi` could resolve a real package manager.
/// Held for writing while a case writes its shims and for reading while a case spawns a child.
/// A child forked while another case's shim is still open for writing would hold that open file
/// until it execs, and a shim run in that instant fails with ETXTBSY ("Text file busy").
static SHIMS: RwLock<()> = RwLock::new(());

fn write_shims(bin: &Path, log: &Path, fixtures: &Path) {
    let _writing = SHIMS.write().unwrap_or_else(|e| e.into_inner());
    let bodies = [
        // Neither of these is ever reached by an import, and that is the point: one that were
        // would be in the log, and `nothing_the_command_runs_mutates_the_machine` says which.
        ("apt-get", "exit 0\n"),
        ("dpkg", "exit 0\n"),
        (
            "dpkg-query",
            "case \"$*\" in\n\
             *Conffiles*) emit conffiles.txt ;;\n\
             *Priority*) emit dpkg-survey.txt ;;\n\
             *) emit dpkg-query.txt ;;\n\
             esac\n",
        ),
        // `apt-cache policy` answers two questions from one subcommand: with names, each one's
        // version table; with none, the release fields of every enabled source. R-2 reads both.
        (
            "apt-cache",
            "names=0; skip=0\n\
             for a in \"$@\"; do\n\
             \x20 if [ \"$skip\" = 1 ]; then skip=0; continue; fi\n\
             \x20 case \"$a\" in\n\
             \x20 policy) ;;\n\
             \x20 -o) skip=1 ;;\n\
             \x20 -*) ;;\n\
             \x20 *) names=1 ;;\n\
             \x20 esac\n\
             done\n\
             case \"$1\" in\n\
             policy)\n\
             \x20 if [ \"$names\" = 1 ]; then\n\
             \x20   emit policy.txt\n\
             \x20 else\n\
             \x20   emit policy-release.txt\n\
             \x20 fi ;;\n\
             esac\n",
        ),
        (
            "apt-mark",
            "case \"$1\" in\n\
             showauto) emit apt-mark-showauto.txt ;;\n\
             showhold) emit apt-mark-showhold.txt ;;\n\
             esac\n",
        ),
        ("pacman", "exit 0\n"),
        // The plan of an imported `[system]` keymap reads it back (si-1): the layout
        // `etc/default/keyboard` holds in `write_the_configuration`.
        (
            "localectl",
            "case \"$*\" in\n\
             *status*) printf 'System Locale: LANG=C.UTF-8\\n   X11 Layout: us\\n' ;;\n\
             *) exit 1 ;;\n\
             esac\n",
        ),
    ];
    for (name, body) in bodies {
        let script = format!(
            "#!/bin/sh\n\
             # A test-owned shim of tests/host_import_cli.rs. It logs its argv and replays a\n\
             # hand-authored recording with shell builtins alone. No package manager runs here.\n\
             fixtures='{fixtures}'\n\
             emit() {{ while IFS= read -r line; do printf '%s\\n' \"$line\"; done < \"$fixtures/$1\"; }}\n\
             {{ printf '%s' '{name}'\n\
             \x20 for a in \"$@\"; do printf '\\037%s' \"$a\"; done\n\
             \x20 printf '\\036'; }} >> '{log}'\n\
             {body}",
            fixtures = fixtures.display(),
            log = log.display(),
        );
        let path = bin.join(name);
        fs::write(&path, script).expect("a shim");
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).expect("a shim mode");
    }
}

// ----------------------------------------------------------------------------- the census ---

/// One object below a root: its type, its mode, its size and its mtime to the nanosecond.
type Census = BTreeMap<String, String>;

/// A full census of `root`, which is acceptance row (h)'s whole instrument. Symbolic links are
/// recorded, never followed, and the nanoseconds are what makes a rewrite with identical bytes
/// visible.
fn census(root: &Path) -> Census {
    fn visit(base: &Path, dir: &Path, out: &mut Census) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let Ok(meta) = path.symlink_metadata() else {
                continue;
            };
            let kind = if meta.is_dir() {
                "dir"
            } else if meta.is_symlink() {
                "link"
            } else {
                "file"
            };
            let rel = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .display()
                .to_string();
            out.insert(
                rel,
                format!(
                    "{kind} {:04o} {} {}.{:09}",
                    meta.permissions().mode() & 0o7777,
                    meta.size(),
                    meta.mtime(),
                    meta.mtime_nsec(),
                ),
            );
            if meta.is_dir() {
                visit(base, &path, out);
            }
        }
    }
    let mut out = Census::new();
    visit(root, root, &mut out);
    assert!(
        !out.is_empty(),
        "a census of {} found nothing",
        root.display()
    );
    out
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

/// The seven configuration files the capture scenario judges, written as real files with real
/// modes. One is refused for its mode, one is unmodified and so never a candidate, and the other
/// five are world-readable and on no list of `src/hostscope/import/files.rs`, so they are taken.
fn write_the_configuration(case: &Case) {
    case.root
        .write("etc/sysctl.d/99-local.conf", "vm.swappiness = 10\n")
        .chmod("etc/sysctl.d/99-local.conf", 0o644);
    case.root
        .write("etc/ca-certificates.conf", "!mozilla/Local_CA.crt\n")
        .chmod("etc/ca-certificates.conf", 0o644);
    // Refused for its mode: not readable by other, so it is never opened.
    case.root
        .write("etc/openvpn/client.conf", "remote vpn.invalid 1194\n")
        .chmod("etc/openvpn/client.conf", 0o600);
    // Not refused: none of the three is on the hard path list (`NEVER_CAPTURED`) or under a
    // directory or ending it names, so each is captured because it is world-readable.
    case.root
        .write("etc/ssh/sshd_config", "PermitRootLogin no\n")
        .chmod("etc/ssh/sshd_config", 0o644);
    case.root
        .write("etc/resolv.conf", "nameserver 192.0.2.1\n")
        .chmod("etc/resolv.conf", 0o644);
    case.root
        .write("etc/nslcd.conf", "uri ldap://ldap.invalid\n")
        .chmod("etc/nslcd.conf", 0o644);
    // Unmodified: equal to the bytes its package shipped, so not a candidate at all.
    case.root.write(
        "etc/default/keyboard",
        "# keyboard defaults\nXKBMODEL=\"pc105\"\nXKBLAYOUT=\"us\"\n",
    );
}

/// Every tracked file of the `refusals` recording, written as a real, world-readable, modified
/// file. Each one is a candidate the policy must turn away by name.
fn write_the_refusables(case: &Case) {
    for rel in [
        "etc/apt/auth.conf",
        "etc/apt/auth.conf.d/90local",
        "etc/crypttab",
        "etc/fstab",
        "etc/gshadow",
        "etc/krb5.keytab",
        "etc/machine-id",
        "etc/netrc",
        "etc/NetworkManager/system-connections/home.nmconnection",
        "etc/pacman.d/gnupg/pubring.conf",
        "etc/pacman.d/mirrorlist",
        "etc/pki/client.p12",
        "etc/shadow",
        "etc/ssh/ssh_host_ed25519_key",
        "etc/ssl/private/site.conf",
        "etc/subgid",
        "etc/subuid",
        "etc/sudoers.d/90-local",
        "etc/wpa_supplicant/wpa_supplicant.conf",
        "usr/local/etc/outside.conf",
    ] {
        case.root
            .write(rel, "# changed since the package shipped it\n")
            .chmod(rel, 0o644);
    }
}

// ------------------------------------------------------------------- (c) the arming gate ---

/// Acceptance (c): an unarmed root is `E_HOST_NOT_ARMED` at exit 9 **before the manifest
/// directory is opened**.
///
/// The proof is the manifest itself: `etc/lodi/host.toml` is there and is unreadable. A gate that
/// opened it — or the directory holding it — before checking the marker would fail with a read
/// error, not with the arming refusal, and this test would say so.
#[test]
fn an_unarmed_root_is_refused_before_anything_below_it_is_opened() {
    let case = Case::new("unarmed", "capture");
    fs::remove_file(case.root.path("etc/lodi/host-allowed")).expect("the marker comes off");
    case.root.write("etc/lodi/host.toml", "unreadable\n");
    case.root.chmod("etc/lodi/host.toml", 0o000);
    let before = census(&case.root.dir);
    // The manifest and the directory holding it are both unreadable, so a gate that opened
    // either one before checking the marker would fail with a read error instead.
    case.root.chmod("etc/lodi", 0o000);
    // check-host-safety: refusal — a scratch root this test owns and never armed.
    let out = case.lodi(&["host", "import", "--root", &case.root_arg()]);
    assert_eq!(out.status.code(), Some(9), "{}", stderr(&out));
    assert!(
        stderr(&out).contains("E_HOST_NOT_ARMED"),
        "{}",
        stderr(&out)
    );
    assert!(stdout(&out).is_empty(), "{}", stdout(&out));
    assert!(
        case.argv_log().is_empty(),
        "an unarmed root ran {:?}",
        case.argv_log()
    );
    case.root.chmod("etc/lodi", 0o755);
    assert_eq!(before, census(&case.root.dir), "the root moved");
}

// ------------------------------------------------------------- (d) no package manager ---

/// Acceptance (d): an armed root whose distribution's package manager is not on `PATH` is
/// `E_NO_RUNTIME` at exit 7. The `PATH` here is empty, so nothing on this machine is reachable.
#[test]
fn an_armed_root_with_no_package_manager_is_no_runtime() {
    let case = Case::new("no-runtime", "capture");
    let before = census(&case.root.dir);
    // check-host-safety: refusal — the same scratch root, with an empty PATH.
    let out = case.run_with_path("", &["host", "import", "--root", &case.root_arg()]);
    assert_eq!(out.status.code(), Some(7), "{}", stderr(&out));
    assert!(stderr(&out).contains("E_NO_RUNTIME"), "{}", stderr(&out));
    assert!(stdout(&out).is_empty(), "{}", stdout(&out));
    assert_eq!(before, census(&case.root.dir), "the root moved");
}

// ----------------------------------------------------- (e) --out inside the scope's own ---

/// Acceptance (e): an `--out` that resolves inside a directory the host scope owns is
/// `E_STORE_IO` at exit 6 and writes nothing — including through a relative path and a symbolic
/// link, because a refusal a `..` could walk around would not be one.
#[test]
fn out_inside_a_directory_the_scope_owns_is_store_io_and_writes_nothing() {
    let case = Case::new("out-owned", "capture");
    write_the_configuration(&case);
    let root = case.root_arg();
    let link = case.outside.join("into-the-root");
    std::os::unix::fs::symlink(case.root.path("etc/lodi"), &link).expect("a link");

    let spellings = [
        case.root.path("etc/lodi").display().to_string(),
        case.root.path("etc/lodi/captured").display().to_string(),
        case.root.path("var/lib/lodi/host").display().to_string(),
        format!("{}/etc/lodi/../lodi/deeper", case.root.dir.display()),
        link.display().to_string(),
    ];
    for out in spellings {
        let before = census(&case.root.dir);
        // check-host-safety: refusal — the same scratch root.
        let output = case.lodi(&["host", "import", "--root", &root, "--out", &out]);
        assert_eq!(
            output.status.code(),
            Some(6),
            "--out {out} was not refused:\n{}",
            stderr(&output)
        );
        assert!(
            stderr(&output).contains("E_STORE_IO"),
            "--out {out}:\n{}",
            stderr(&output)
        );
        assert!(stdout(&output).is_empty(), "{}", stdout(&output));
        assert_eq!(before, census(&case.root.dir), "--out {out} moved the root");
    }
    // The refusal is decided before the machine is read: nothing ran at all.
    assert!(
        case.argv_log().is_empty(),
        "a refused --out ran {:?}",
        case.argv_log()
    );
}

// --------------------------------------------------------- (f) E_EXISTS and --force ---

/// Acceptance (f): an existing `DIR/host.toml` is `E_EXISTS` at exit 3 and is left exactly as it
/// was; with `--force` it is replaced by the generated manifest, at 0644, with the bundle beside
/// it. The root does not move in either case.
#[test]
fn an_existing_manifest_is_reconciled_not_refused_until_force_replaces_it() {
    let case = Case::new("exists", "capture");
    write_the_configuration(&case);
    let root = case.root_arg();
    let out = case.out_dir();
    fs::create_dir_all(&out).expect("the out directory");
    fs::write(
        out.join("host.toml"),
        "# a file the operator wrote\n[host]\nversion = \"1\"\n",
    )
    .expect("the existing file");
    let existing = census(&out);
    let before = census(&case.root.dir);

    // An existing manifest is no longer E_EXISTS (LD-378): it is reconciled. Lodi has no record
    // of a sync of this directory, so the reconcile is a report and writes nothing.
    // check-host-safety: refusal — the same scratch root.
    let reported = case.lodi(&[
        "host",
        "import",
        "--root",
        &root,
        "--out",
        &out.display().to_string(),
    ]);
    assert_eq!(reported.status.code(), Some(0), "{}", stderr(&reported));
    assert!(
        !stderr(&reported).contains("E_EXISTS"),
        "{}",
        stderr(&reported)
    );
    let said = String::from_utf8_lossy(&reported.stdout).into_owned();
    assert!(said.contains("not reconciled"), "{said}");
    assert!(said.contains("--force"), "{said}");
    assert_eq!(existing, census(&out), "the report wrote something");
    assert_eq!(before, census(&case.root.dir), "the root moved");

    // check-host-safety: refusal — the same scratch root.
    let forced = case.lodi(&[
        "host",
        "import",
        "--root",
        &root,
        "--out",
        &out.display().to_string(),
        "--force",
    ]);
    assert_eq!(forced.status.code(), Some(0), "{}", stderr(&forced));
    let written = fs::read_to_string(out.join("host.toml")).expect("the manifest");
    assert!(written.starts_with(GENERATED), "{written}");
    assert_eq!(
        fs::metadata(out.join("host.toml"))
            .expect("the manifest's metadata")
            .permissions()
            .mode()
            & 0o7777,
        0o644,
        "the manifest is written 0644"
    );
    // No file is copied from /etc (si-1): the changed one is named with the table that
    // declares it, and nothing travels beside the manifest.
    assert!(!out.join("files").exists(), "a file was copied from /etc");
    assert!(!written.contains("[files."), "{written}");
    assert!(
        written.contains("#   /etc/sysctl.d/99-local.conf\n"),
        "{written}"
    );
    assert!(
        written.contains("[etc.\"sysctl.d/99-local.conf\"]"),
        "{written}"
    );
    // Nothing of this machine's identity leaves with it but its [system] host name.
    assert!(!without_hostname(&written).contains(HOST_NAME), "{written}");
    assert_eq!(before, census(&case.root.dir), "the root moved");
}

/// An `--out` directory the import creates itself is one it then trusts: under a umask that
/// leaves the group write bit (Ubuntu's default 002), every directory it makes on the way is
/// 0755, and the bundle is written. A group-writable directory that was already there is still
/// refused (LD-333); only what the import makes is its to shape (LD-343).
#[test]
fn an_out_directory_the_import_makes_is_trusted_under_a_group_writable_umask() {
    let case = Case::new("out-umask", "capture");
    write_the_configuration(&case);
    let root = case.root_arg();
    let out = case.out_dir().join("nested");
    let home = case.outside.join("home");
    let spawning = SHIMS.read().unwrap_or_else(|e| e.into_inner());
    // check-host-safety: refusal — the same scratch root.
    let made = Command::new("/bin/sh")
        .arg("-c")
        .arg("umask 002 && exec \"$0\" \"$@\"")
        .arg(env!("CARGO_BIN_EXE_lodi"))
        .args(["host", "import", "--root", &root, "--out"])
        .arg(&out)
        .current_dir(&case.outside)
        .env_clear()
        .env("PATH", &case.bin)
        .env("HOME", &home)
        .output()
        .expect("the lodi binary runs");
    drop(spawning);
    assert_eq!(made.status.code(), Some(0), "{}", stderr(&made));
    for dir in [case.out_dir(), out.clone()] {
        let mode = fs::metadata(&dir)
            .expect("the made directory")
            .permissions()
            .mode()
            & 0o7777;
        assert_eq!(mode, 0o755, "{} is {mode:04o}", dir.display());
    }
    assert!(out.join("host.toml").is_file(), "no manifest was written");

    let loose = case.outside.join("loose");
    fs::create_dir_all(&loose).expect("an operator's directory");
    fs::set_permissions(&loose, fs::Permissions::from_mode(0o775)).expect("its mode");
    // check-host-safety: refusal — the same scratch root.
    let refused = case.lodi(&[
        "host",
        "import",
        "--root",
        &root,
        "--out",
        &loose.display().to_string(),
    ]);
    assert_eq!(refused.status.code(), Some(3), "{}", stderr(&refused));
    assert!(
        stderr(&refused).contains("E_PATH_ESCAPE"),
        "{}",
        stderr(&refused)
    );
    assert!(
        !loose.join("host.toml").exists(),
        "the refused import wrote a manifest"
    );
}

// ---------------------------------------------- --stdout: standard output, no capture ---

/// With `--stdout` the manifest goes to standard output, no configuration file is captured, and
/// nothing is written anywhere — not under the root, and not in the working directory either.
/// These are the bytes the no-flag form printed before LD-325 moved them behind the flag.
#[test]
fn with_stdout_the_manifest_goes_to_standard_output_and_nothing_is_captured() {
    let case = Case::new("stdout", "capture");
    write_the_configuration(&case);
    let before = census(&case.root.dir);
    let outside_before = census(&case.outside);

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&["host", "import", "--root", &case.root_arg(), "--stdout"]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stdout(&out);
    assert!(text.starts_with(GENERATED), "{text}");
    assert!(text.contains("[packages]"), "{text}");
    assert!(
        !text.contains("[files."),
        "an import with --stdout declared a file whose bytes nobody wrote:\n{text}"
    );
    assert!(
        !stderr(&out).contains("is not captured:"),
        "nothing was offered to the policy, so no file can be refused:\n{}",
        stderr(&out)
    );
    assert_eq!(before, census(&case.root.dir), "the root moved");
    assert_eq!(
        outside_before,
        census(&case.outside),
        "the working directory moved"
    );
}

// --------------------------------------------------------------- W_UNCAPTURED on stderr ---

/// Every refusal is one `W_UNCAPTURED` line on **standard error**, and none of them changes the
/// exit status: an import that refuses everything it was offered still exits 0.
///
/// The `refusals` recording is the one whose every tracked file is on the hard path list, is a
/// key, or is outside `/etc` altogether — the class of file the policy exists for.
#[test]
fn refusals_are_warnings_on_standard_error_and_change_no_exit_status() {
    let case = Case::new("refusals", "refusals");
    write_the_refusables(&case);
    let out_dir = case.out_dir();
    let before = census(&case.root.dir);

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&[
        "host",
        "import",
        "--root",
        &case.root_arg(),
        "--out",
        &out_dir.display().to_string(),
    ]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    let warnings: Vec<&str> = text
        .lines()
        .filter(|line| line.starts_with("W_UNCAPTURED"))
        .collect();
    assert!(
        warnings.len() >= 10,
        "every hard-list candidate should have spoken:\n{text}"
    );
    for refused in [
        "/etc/netrc",
        "/etc/pacman.d/mirrorlist",
        "/etc/sudoers.d/90-local",
        "/etc/shadow",
        "/etc/ssl/private/site.conf",
        "/etc/ssh/ssh_host_ed25519_key",
        "/etc/pki/client.p12",
        "/usr/local/etc/outside.conf",
    ] {
        assert!(
            warnings.iter().any(|line| line.contains(refused)),
            "{refused} was refused without saying so:\n{text}"
        );
    }
    // A warning never reaches standard output.
    assert!(!stdout(&out).contains("W_UNCAPTURED"), "{}", stdout(&out));
    // Nothing was captured, so the manifest declares no file and the bundle is not there.
    let written = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    assert!(!written.contains("[files."), "{written}");
    assert!(
        !out_dir.join("files").exists(),
        "a refused file was written out"
    );
    assert_eq!(before, census(&case.root.dir), "the root moved");
}

/// The real command copies no file from `/etc` (si-1): each file of
/// `tests/support/credentials.rs` is one `W_UNCAPTURED` line naming the file, no bundle is
/// written, and no fake value reaches standard output, standard error or the manifest.
#[test]
fn a_credential_in_any_shape_never_leaves_the_file() {
    let case = Case::new("credentials", "credentials");
    let shapes = credentials::shapes();
    for (index, shape) in shapes.iter().enumerate() {
        let rel = format!("etc/credential-shapes/{index:02}.conf");
        case.root.write(&rel, &shape.text).chmod(&rel, 0o644);
    }
    let benign = "etc/credential-shapes/benign.conf";
    case.root
        .write(benign, credentials::BENIGN)
        .chmod(benign, 0o644);
    let out_dir = case.out_dir();

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&[
        "host",
        "import",
        "--root",
        &case.root_arg(),
        "--out",
        &out_dir.display().to_string(),
    ]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    // Since si-1 no file is copied from /etc: each changed file is named, and none travels.
    for index in 0..shapes.len() {
        let path = format!("/etc/credential-shapes/{index:02}.conf");
        assert!(
            text.lines().any(|line| line.starts_with("W_UNCAPTURED")
                && line.contains(&format!("{path} is not captured"))),
            "{path} was not named:\n{text}"
        );
    }
    let manifest = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    assert!(!manifest.contains("[files."), "{manifest}");
    assert!(
        !out_dir.join("files").exists(),
        "a file was copied from /etc"
    );
    for shape in &shapes {
        for text in [&stdout(&out), &text, &manifest] {
            assert!(
                !text.contains(&shape.fake),
                "{}: the fake value left the file:\n{text}",
                shape.name
            );
        }
    }
}

// ------------------------------------------------- (h) the command writes nothing, ever ---

/// Acceptance (h), taken as a whole: every shape of the invocation, against one root, with one
/// census before the first and one after the last.
///
/// It also asserts what the command **ran**: every argv the shims saw is a read. An import that
/// installed, removed, marked or refreshed anything would be in this log, and the assertion names
/// the command that was not a read.
#[test]
fn nothing_the_command_runs_mutates_the_machine() {
    let case = Case::new("census", "capture");
    write_the_configuration(&case);
    let root = case.root_arg();
    let out = case.out_dir().display().to_string();
    let before = census(&case.root.dir);

    for args in [
        // check-host-safety: refusal — the same scratch root, in every shape.
        vec!["host", "import", "--root", &root, "--stdout"],
        vec!["host", "import", "--root", &root, "--out", &out],
        vec!["host", "import", "--root", &root, "--out", &out, "--force"],
    ] {
        let output = case.lodi(&args);
        assert!(
            matches!(output.status.code(), Some(0) | Some(3)),
            "`lodi {}` exited {:?}:\n{}",
            args.join(" "),
            output.status.code(),
            stderr(&output)
        );
    }
    assert_eq!(
        before,
        census(&case.root.dir),
        "an import changed the machine it read"
    );

    let log = case.argv_log();
    assert!(!log.is_empty(), "the shims saw nothing at all");
    for record in &log {
        let program = record.split(' ').next().unwrap_or_default();
        assert!(
            matches!(program, "dpkg-query" | "apt-cache" | "apt-mark"),
            "an import ran `{record}`, which is not one of its reads"
        );
        for verb in ["install", "remove", "purge", "update", "upgrade", "hold"] {
            assert!(
                !record.split(' ').any(|word| word == verb),
                "an import ran `{record}`"
            );
        }
    }
}

// ------------------------------------------------ R-2, acceptance (3): the package lines ---

/// Every package the emitted file names but does not declare is one `W_UNCAPTURED` line on
/// standard error, in the order the file names them; the file's own refusals follow; the report
/// line states both counts; and the exit status is 0.
///
/// The `off-base` recording is the machine R-2 is about: a third-party package, a PPA package
/// and a hand-installed one, none of which a fresh machine could install, beside two names it
/// could. Before R-2 all five were declared and the restore stopped at `E_UNKNOWN_PACKAGE`.
#[test]
fn every_package_left_out_is_one_warning_on_standard_error_and_the_exit_is_zero() {
    let case = Case::new("offbase", "off-base");
    let out_dir = case.out_dir();

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&[
        "host",
        "import",
        "--root",
        &case.root_arg(),
        "--out",
        &out_dir.display().to_string(),
    ]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    let warnings: Vec<&str> = text
        .lines()
        .filter(|line| line.starts_with("W_UNCAPTURED"))
        .collect();
    assert_eq!(
        warnings,
        vec![
            "W_UNCAPTURED: docker-ce is not declared: it is installed from Docker, \
             bookworm/stable, which is not debian's own repository",
            "W_UNCAPTURED: lodi-agent is not declared: it is installed from \
             LP-PPA-lodi-testing, noble/main, which is not debian's own repository",
            "W_UNCAPTURED: lodi-hand-built is not declared: its installed version is known \
             only to this machine's own package database: a package file installed by hand, \
             or a source this machine no longer has",
        ],
        "one line per left-out package, in the emitted file's order:\n{text}"
    );

    // The report line states both counts. It is a `wrote …` line, which every command of this
    // build puts on standard output, and the warnings it counts are on standard error.
    let told = stdout(&out);
    let report: Vec<&str> = told
        .lines()
        .filter(|line| line.contains("host.toml:"))
        .collect();
    assert_eq!(report.len(), 1, "{told}");
    assert!(
        report[0].ends_with(
            "host.toml: 2 package(s) declared, 3 not captured; no file copied from /etc"
        ),
        "{told}"
    );
    assert!(!told.contains("W_UNCAPTURED"), "{told}");

    // With --stdout the same lines are on standard error and the manifest alone is on standard
    // output, so that `lodi host import --root … --stdout > host.toml` is one usable file.
    // check-host-safety: refusal — the same scratch root.
    let piped = case.lodi(&["host", "import", "--root", &case.root_arg(), "--stdout"]);
    assert_eq!(piped.status.code(), Some(0), "{}", stderr(&piped));
    let piped_warnings: Vec<&str> = stderr(&piped)
        .lines()
        .filter(|line| line.starts_with("W_UNCAPTURED"))
        .map(|line| line.to_string().leak() as &str)
        .collect();
    assert_eq!(piped_warnings, warnings, "{}", stderr(&piped));
    // Standard output is the manifest and nothing else: it opens with the generated header,
    // closes with the last line of the comment block, and carries no warning and no report.
    let text = stdout(&piped);
    assert!(text.starts_with(GENERATED), "{text}");
    assert!(!text.contains("W_UNCAPTURED"), "{text}");
    assert!(!text.contains("package(s) declared"), "{text}");
    // The last line is the repositories part's (LD-367): the hand-built name, attributed to no
    // `[sources]` block.
    assert_eq!(
        text.trim_end().lines().next_back(),
        Some(
            "#     unattributed: no enabled repository offers the installed version (a package \
             file, or a repository since removed)"
        ),
        "{text}"
    );
    // The declarations are the ones the file on disk carries. No capture is taken with
    // `--stdout`, so the file's configuration paragraphs are the only difference between them.
    let written = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    for shared in [
        "common = [\n  \"golang-1.22\",\n  \"ripgrep\",\n]\n",
        "#   docker-ce               Docker, bookworm/stable\n",
        "#   lodi-agent              LP-PPA-lodi-testing, noble/main\n",
    ] {
        assert!(text.contains(shared) && written.contains(shared), "{text}");
    }
}

/// The specimen of `W_UNCHECKED_ORIGIN`, from a real run of the built binary: the machine with
/// no package index at all. It is printed **once**, before any `W_UNCAPTURED` line — there are
/// none, because nothing was left out — the report line counts nothing not captured, and the
/// exit status is 0.
#[test]
fn a_machine_with_no_index_warns_once_and_leaves_nothing_out() {
    let case = Case::new("offindex", "off-index");
    let out_dir = case.out_dir();

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&[
        "host",
        "import",
        "--root",
        &case.root_arg(),
        "--out",
        &out_dir.display().to_string(),
    ]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let text = stderr(&out);
    let unchecked: Vec<&str> = text
        .lines()
        .filter(|line| line.starts_with("W_UNCHECKED_ORIGIN"))
        .collect();
    assert_eq!(
        unchecked,
        vec![
            "W_UNCHECKED_ORIGIN: this machine has no package index, so where the declared \
             names came from was not checked: every name is declared as read. Fetch the index \
             and import again to have the names no base repository serves named instead.",
        ],
        "once per run, about the machine and no package:\n{text}"
    );
    assert!(
        !text.contains("W_UNCAPTURED"),
        "nothing was left out, so nothing is uncaptured:\n{text}"
    );

    let told = stdout(&out);
    let report: Vec<&str> = told
        .lines()
        .filter(|line| line.contains("host.toml:"))
        .collect();
    assert_eq!(report.len(), 1, "{told}");
    assert!(
        report[0].ends_with(
            "host.toml: 5 package(s) declared, 0 not captured; no file copied from /etc"
        ),
        "{told}"
    );

    // The emitted file says the same thing above the list, so a person reading the file alone
    // is told as much as one watching the run.
    let written = fs::read_to_string(out_dir.join("host.toml")).expect("the manifest");
    assert!(
        written.contains("# This machine has no package index: nothing has been fetched from any"),
        "{written}"
    );
    for name in ["docker-ce", "lodi-agent", "lodi-hand-built"] {
        assert!(written.contains(&format!("  \"{name}\",\n")), "{written}");
    }
}

// ------------------------------------------ LD-325: with no flag, the import lands in place ---

/// With no flag the manifest lands at `etc/lodi/host.toml` below the root, at 0644 and owned by
/// the invoking user, the captured bytes land under `etc/lodi/files/`, one line names both and
/// the next command, and the plan that follows resolves every `source` the manifest declares.
///
/// Before LD-325 the same invocation printed the manifest and wrote nothing, so every assertion
/// on the landed files here fails against that build.
#[test]
fn with_no_flag_the_import_lands_in_place_and_plan_resolves_every_source() {
    let case = Case::new("in-place", "capture");
    write_the_configuration(&case);
    let root = case.root_arg();
    let before = census(&case.root.dir);

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&["host", "import", "--root", &root]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let manifest = case.root.path("etc/lodi/host.toml");
    // What it wrote and that nothing else changed, what to read first, and the next command,
    // which writes nothing (u-1, LD-380): three lines, the first of them the one line it was.
    let told = stdout(&out);
    let lines: Vec<&str> = told.lines().collect();
    assert_eq!(lines.len(), 3, "three lines:\n{told}");
    assert!(
        lines[0].starts_with(&format!("wrote {}: ", manifest.display())),
        "{told}"
    );
    assert!(
        lines[0].ends_with(&format!(
            "not captured, no file copied from /etc; no package and no file outside {} changed",
            case.root.path("etc/lodi").display()
        )),
        "{told}"
    );
    assert_eq!(
        lines[1], "read it first: NOT CAPTURED lists what was left out and how to declare it",
        "{told}"
    );
    assert_eq!(
        lines[2],
        format!("next: lodi host plan --root {root} (writes nothing)"),
        "{told}"
    );

    let meta = fs::symlink_metadata(&manifest).expect("the manifest landed");
    assert!(meta.file_type().is_file());
    assert_eq!(meta.permissions().mode() & 0o7777, 0o644);
    assert_eq!((meta.uid(), meta.gid()), (uid(), gid()));
    let written = fs::read_to_string(&manifest).unwrap();
    assert!(written.starts_with(GENERATED), "{written}");
    assert!(!without_hostname(&written).contains(HOST_NAME), "{written}");
    assert!(!written.contains("[files."), "{written}");
    assert!(
        written.contains("[etc.\"sysctl.d/99-local.conf\"]"),
        "{written}"
    );
    assert!(
        !case.root.path("etc/lodi/files").exists(),
        "a file was copied from /etc"
    );
    // Every object new below the root is below etc/lodi, and nothing that was there moved.
    let after = census(&case.root.dir);
    for (path, what) in &before {
        if path != "etc/lodi" {
            assert_eq!(after.get(path), Some(what), "{path} moved");
        }
    }
    for path in after.keys().filter(|k| !before.contains_key(*k)) {
        assert!(path.starts_with("etc/lodi/"), "the import wrote {path}");
    }

    // check-host-safety: refusal — the same scratch root.
    let plan = case.lodi(&["host", "plan", "--root", &root]);
    assert_eq!(plan.status.code(), Some(0), "{}", stderr(&plan));
    let text = stdout(&plan);
    assert!(
        !stderr(&plan).contains("E_") && !text.contains("missing"),
        "the plan did not resolve every source:\n{text}\n{}",
        stderr(&plan)
    );
}

/// An import in place declares the `[system]` basics it read — the host name, the time zone and
/// the locale — and records them as a converged apply would, so the plan of the machine it came
/// from is `nothing to do`: no `= hostname` line, and no record-only update (#585).
#[test]
fn an_imported_machine_with_its_basics_plans_nothing_to_do() {
    let case = Case::new("in-place-basics", "capture");
    write_the_configuration(&case);
    case.root.write("usr/share/zoneinfo/UTC", "TZif2\n");
    std::os::unix::fs::symlink("../usr/share/zoneinfo/UTC", case.root.path("etc/localtime"))
        .expect("localtime");
    case.root.write("etc/locale.conf", "LANG=C.UTF-8\n");
    let root = case.root_arg();

    // check-host-safety: refusal — the same scratch root.
    let out = case.lodi(&["host", "import", "--root", &root]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let written = fs::read_to_string(case.root.path("etc/lodi/host.toml")).unwrap();
    for line in ["timezone = \"UTC\"", "locale = \"C.UTF-8\""] {
        assert!(written.contains(line), "{line}: {written}");
    }

    // check-host-safety: refusal — the same scratch root.
    let plan = case.lodi(&["host", "plan", "--root", &root]);
    assert_eq!(plan.status.code(), Some(0), "{}", stderr(&plan));
    let text = stdout(&plan);
    let kept: Vec<&str> = text
        .lines()
        .filter(|line| !line.starts_with("= file ") && !line.starts_with("~ index ("))
        .collect();
    assert_eq!(kept, ["nothing to do"], "{text}");
}

/// An existing `etc/lodi/host.toml` below the root is no longer `E_EXISTS` (LD-378): it is
/// reconciled, and with no record of the last sync that is a report naming the apply and
/// `--force`, with nothing written. `--force` replaces the manifest and the bundle, and a file the
/// new manifest no longer declares is gone from `files/`, so what lands is exactly its sources —
/// and a plan of it resolves every one.
#[test]
fn an_existing_manifest_in_place_is_reconciled_until_force_replaces_it_and_its_files() {
    let case = Case::new("in-place-exists", "capture");
    write_the_configuration(&case);
    let root = case.root_arg();
    case.root.write(
        "etc/lodi/host.toml",
        "# a file the operator wrote\n[host]\nversion = \"1\"\n",
    );
    case.root.write(
        "etc/lodi/files/etc/stale.conf",
        "a source no manifest names\n",
    );
    let before = census(&case.root.dir);

    // check-host-safety: refusal — the same scratch root.
    let reported = case.lodi(&["host", "import", "--root", &root]);
    assert_eq!(reported.status.code(), Some(0), "{}", stderr(&reported));
    let text = String::from_utf8_lossy(&reported.stdout).into_owned();
    assert!(
        !stderr(&reported).contains("E_EXISTS"),
        "{}",
        stderr(&reported)
    );
    assert!(
        text.contains("not reconciled: there is no host.lock"),
        "{text}"
    );
    assert!(text.contains("lodi host apply --root"), "{text}");
    assert!(text.contains("--force"), "{text}");
    assert_eq!(before, census(&case.root.dir), "the report wrote");

    // check-host-safety: refusal — the same scratch root.
    let forced = case.lodi(&["host", "import", "--root", &root, "--force"]);
    assert_eq!(forced.status.code(), Some(0), "{}", stderr(&forced));
    assert!(
        case.root.read("etc/lodi/host.toml").starts_with(GENERATED),
        "--force did not replace the manifest"
    );
    assert!(
        !case.root.exists("etc/lodi/files/etc/stale.conf"),
        "--force left a file the new manifest does not name"
    );
    assert!(
        !case.root.read("etc/lodi/host.toml").contains("[files."),
        "--force copied a file from /etc"
    );
    // check-host-safety: refusal — the same scratch root.
    let plan = case.lodi(&["host", "plan", "--root", &root]);
    assert_eq!(plan.status.code(), Some(0), "{}", stderr(&plan));
}

/// A symbolic link planted at `etc/lodi/host.toml` or `etc/lodi/files` — or at `etc/lodi` itself —
/// is `E_PATH_ESCAPE` at exit 3, nothing is written through it, and the machine is not read.
#[test]
fn a_planted_link_in_the_destination_is_refused() {
    for (name, planted) in [
        ("link-manifest", "etc/lodi/host.toml"),
        ("link-files", "etc/lodi/files"),
        ("link-dir", "etc/lodi"),
    ] {
        let case = Case::new(name, "capture");
        write_the_configuration(&case);
        let target = case.outside.join("elsewhere");
        fs::create_dir_all(&target).unwrap();
        fs::write(target.join("witness"), "a file the link points beside\n").unwrap();
        if planted == "etc/lodi" {
            // The marker travels with the directory, so the root is still armed through it.
            fs::copy(
                case.root.path("etc/lodi/host-allowed"),
                target.join("host-allowed"),
            )
            .unwrap();
            fs::remove_dir_all(case.root.path("etc/lodi")).unwrap();
        }
        std::os::unix::fs::symlink(&target, case.root.path(planted)).expect("a link");
        let target_before = census(&target);
        let before = census(&case.root.dir);

        // check-host-safety: refusal — the same scratch root.
        let out = case.lodi(&["host", "import", "--root", &case.root_arg(), "--force"]);
        assert_eq!(out.status.code(), Some(3), "{planted}: {}", stderr(&out));
        assert!(
            stderr(&out).contains("E_PATH_ESCAPE"),
            "{planted}: {}",
            stderr(&out)
        );
        assert!(stdout(&out).is_empty(), "{planted}: {}", stdout(&out));
        assert_eq!(
            target_before,
            census(&target),
            "{planted}: wrote through it"
        );
        assert_eq!(before, census(&case.root.dir), "{planted}: the root moved");
        assert!(
            case.argv_log().is_empty(),
            "{planted}: the machine was read"
        );
    }
}

/// `--stdout` and `--out` name two destinations and `--stdout --force` has nothing to replace:
/// each is a usage error at exit 2, decided before the gate, and nothing moves.
#[test]
fn stdout_with_out_or_force_is_a_usage_error() {
    let case = Case::new("stdout-usage", "capture");
    let root = case.root_arg();
    let out = case.out_dir().display().to_string();
    let before = census(&case.root.dir);
    for args in [
        vec!["host", "import", "--root", &root, "--stdout", "--out", &out],
        vec!["host", "import", "--root", &root, "--out", &out, "--stdout"],
        vec!["host", "import", "--root", &root, "--stdout", "--force"],
    ] {
        // check-host-safety: refusal — the same scratch root.
        let output = case.lodi(&args);
        assert_eq!(output.status.code(), Some(2), "{}", args.join(" "));
        assert!(stdout(&output).is_empty(), "{}", stdout(&output));
    }
    assert!(!case.out_dir().exists(), "a usage error wrote --out");
    assert_eq!(before, census(&case.root.dir), "the root moved");
    assert!(case.argv_log().is_empty(), "a usage error read the machine");
}

/// Landing on the running system's own `/` needs euid 0: the decision is a pure function of the
/// root and the effective uid, proved here with injected uids and never by pointing a host verb
/// at `/`. Under a `--root` the invoking user lands in a tree of their own.
#[test]
fn only_root_lands_an_import_on_the_system_root() {
    use lodi::hostscope::landing::may_land_in_place;
    let refused = may_land_in_place(true, 1000).expect_err("a user on / is refused");
    assert_eq!(refused.code, "E_NEED_ROOT");
    assert_eq!(lodi::diag::exit_status(refused.code), 9);
    assert!(refused.to_string().contains("--stdout"), "{refused}");
    assert!(may_land_in_place(true, 0).is_ok());
    assert!(may_land_in_place(false, 1000).is_ok());
    assert!(may_land_in_place(false, 0).is_ok());
}

/// The one `[sources]` case of the CLI: the `sources` scenario's `/etc/apt` copied into the
/// scratch root.
fn sources_case(name: &str) -> (Case, PathBuf) {
    let case = Case::new(name, "sources");
    let fixture_root = fixtures_root().join("debian-12/sources/root");
    copy_tree(&fixture_root, &case.root.dir);
    (case, fixture_root)
}

/// The keyring a block names travels at the path its `signed_by` names, byte for byte, beside
/// the manifest wherever the manifest lands — `etc/lodi/files/` below the root with no flag
/// (LD-325), `DIR/files/` with `--out DIR` — and never under the root's `etc/lodi/files/` for
/// `--out`. Nothing of the refused repositories travels: no keyring of theirs, and never a
/// credential file.
#[test]
fn the_keyring_a_sources_block_names_lands_beside_the_manifest_and_nothing_of_the_refused() {
    for in_place in [false, true] {
        let (case, fixture_root) = sources_case(if in_place {
            "sources-in-place"
        } else {
            "sources-out"
        });
        let root = case.root_arg();
        let out = case.out_dir();
        let out_arg = out.display().to_string();
        let mut args = vec!["host", "import", "--root", root.as_str()];
        if !in_place {
            args.extend(["--out", out_arg.as_str()]);
        }
        // check-host-safety: refusal — the same scratch root.
        let output = case.lodi(&args);
        assert_eq!(output.status.code(), Some(0), "{}", stderr(&output));
        let dir = if in_place {
            case.root.path("etc/lodi")
        } else {
            out.clone()
        };
        let keyring = dir.join("files/etc/apt/keyrings/lodi-docker.asc");
        let bytes = fs::read(&keyring).expect("the keyring travels beside the manifest");
        assert_eq!(
            bytes,
            fs::read(fixture_root.join("etc/apt/keyrings/docker.asc")).unwrap()
        );
        let meta = fs::symlink_metadata(&keyring).unwrap();
        assert_eq!(meta.permissions().mode() & 0o7777, 0o644);
        let written = fs::read_to_string(dir.join("host.toml")).expect("the manifest");
        assert!(
            written.contains(&format!(
                "# signed_by = \"files/etc/apt/keyrings/lodi-docker.asc\"\n\
                 # signed_by_sha256 = \"{}\"\n",
                lodi::util::sha256_hex(&bytes)
            )),
            "{written}"
        );
        assert!(
            !written.contains("the keyring was not written"),
            "{written}"
        );
        // No keyring becomes a [files] entry: the block is the keyring's only declaration.
        assert!(!written.contains("[files.\"/etc/apt/keyrings"), "{written}");
        for never in [
            "files/etc/apt/keyrings/lodi-idle.gpg",
            "files/etc/apt/keyrings/idle.gpg",
            "files/etc/apt/keyrings/docker.asc",
            "files/etc/apt/auth.conf.d",
            "files/etc/apt/sources.list.d",
        ] {
            assert!(!dir.join(never).exists(), "{never} travelled");
        }
        if !in_place {
            assert!(
                !case.root.exists("etc/lodi/files"),
                "--out wrote under the root's etc/lodi/files"
            );
        }
    }
}

/// Rebased onto the landed core, whose keyring sniff refuses a private key block's marker
/// anywhere in the bytes, mid-line included (LD-365's validator repair): the keyring of the one
/// repository the import would otherwise bundle — Docker's, with its packages attributed to it —
/// holding that marker mid-line after an armored public block, or after a binary public-key
/// packet, is refused by the real command as secret key material. No block is written, no
/// keyring lands beside the manifest, and none of its bytes reaches the manifest or either
/// stream.
#[test]
fn a_private_key_block_anywhere_in_a_keyring_the_import_would_bundle_is_never_carried() {
    // Generated framing only, never a key.
    let armored = b"-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nAAAA\n=AAAA\n\
                    comment: -----BEGIN PGP PRIVATE KEY BLOCK----- SECRET-MATERIAL-XYZ\n\
                    -----END PGP PUBLIC KEY BLOCK-----\n"
        .to_vec();
    let mut binary = vec![0xc6, 4, 1, 2, 3, 4];
    binary.extend_from_slice(b"x-----BEGIN PGP PRIVATE KEY BLOCK-----SECRET-MATERIAL-XYZ");
    for (name, bytes) in [
        ("sources-private-armored", armored),
        ("sources-private-binary", binary),
    ] {
        let (case, _) = sources_case(name);
        fs::write(case.root.path("etc/apt/keyrings/docker.asc"), &bytes).unwrap();
        let out = case.out_dir();
        // check-host-safety: refusal — the same scratch root.
        let output = case.lodi(&[
            "host",
            "import",
            "--root",
            &case.root_arg(),
            "--out",
            &out.display().to_string(),
        ]);
        assert_eq!(output.status.code(), Some(0), "{name}: {}", stderr(&output));
        let written = fs::read_to_string(out.join("host.toml")).expect("the import wrote");
        assert!(!written.contains("[sources.docker]"), "{name}: {written}");
        assert!(
            written.contains(
                "#   /etc/apt/sources.list.d/docker.sources\n\
                 #     its keyring holds secret key material, which is never carried\n\
                 #     installed from it: docker-ce, docker-ce-cli\n"
            ),
            "{name}: {written}"
        );
        assert!(
            !out.join("files/etc/apt/keyrings").exists(),
            "{name}: a keyring travelled"
        );
        for text in [written, stdout(&output), stderr(&output)] {
            for never in ["SECRET-MATERIAL-XYZ", "PRIVATE KEY BLOCK"] {
                assert!(!text.contains(never), "{name}: {never} reached: {text}");
            }
        }
    }
}

/// `--stdout` prints the block, says in it that the keyring was not written and where to put
/// it, and writes nothing anywhere.
#[test]
fn with_stdout_the_block_is_printed_and_says_the_keyring_was_not_written() {
    let (case, _) = sources_case("sources-stdout");
    let before = census(&case.root.dir);
    // check-host-safety: refusal — the same scratch root.
    let output = case.lodi(&["host", "import", "--root", &case.root_arg(), "--stdout"]);
    assert_eq!(output.status.code(), Some(0), "{}", stderr(&output));
    let text = stdout(&output);
    assert!(text.contains("# [sources.docker]\n"), "{text}");
    assert!(
        text.contains(
            "# # the keyring was not written (--stdout): copy /etc/apt/keyrings/docker.asc\n\
             # # to files/etc/apt/keyrings/lodi-docker.asc beside this file\n"
        ),
        "{text}"
    );
    assert_eq!(
        before,
        census(&case.root.dir),
        "--stdout wrote below the root"
    );
    assert!(!case.out_dir().exists());
}

/// The round trip, named: import → uncomment → plan. The bundle the import writes with `--out`,
/// with its `[sources.docker]` block taken the way a person takes it (every line of the block
/// without its `# `), is copied into `etc/lodi/` below a second scratch root — the new machine,
/// which has no Docker stanza of its own — and plans there without error against the test's fake
/// backend, arming the source before the index it forces.
///
/// On the machine it was read from the same block is `E_DUP_RESOURCE` naming the stanza it came
/// from (S7), which is what the block's own comment says.
#[test]
fn round_trip_import_then_uncomment_then_plan() {
    let (case, _) = sources_case("sources-round-trip");
    let out = case.out_dir();
    // check-host-safety: refusal — the same scratch root.
    let import = case.lodi(&[
        "host",
        "import",
        "--root",
        &case.root_arg(),
        "--out",
        &out.display().to_string(),
    ]);
    assert_eq!(import.status.code(), Some(0), "{}", stderr(&import));
    let written = fs::read_to_string(out.join("host.toml")).expect("the import wrote");
    let mut taken = String::new();
    let mut inside = false;
    for line in written.lines() {
        if line.starts_with("# [sources.") {
            inside = true;
        } else if line.is_empty() {
            inside = false;
        }
        taken.push_str(if inside {
            line.strip_prefix("# ").unwrap_or(line)
        } else {
            line
        });
        taken.push('\n');
    }
    assert!(taken.contains("\n[sources.docker]\n"), "{taken}");
    fs::write(out.join("host.toml"), &taken).unwrap();

    // The new machine: the same recordings, none of the old machine's /etc/apt.
    let fresh = Case::new("sources-round-trip-new", "sources");
    copy_tree(&out, &fresh.root.path("etc/lodi"));
    // check-host-safety: refusal — the second scratch root.
    let plan = fresh.lodi(&["host", "plan", "--root", &fresh.root_arg()]);
    assert_eq!(
        plan.status.code(),
        Some(0),
        "{}\n{}",
        stdout(&plan),
        stderr(&plan)
    );
    let text = stdout(&plan);
    assert!(!stderr(&plan).contains("E_"), "{}", stderr(&plan));
    let source = text
        .find("+ source docker")
        .unwrap_or_else(|| panic!("no source step:\n{text}"));
    let index = text
        .find("~ index")
        .unwrap_or_else(|| panic!("the changing source forced no index:\n{text}"));
    assert!(source < index, "{text}");

    // On the machine it was read from, the stanza it came from lists the same repository.
    copy_tree(&out, &case.root.path("etc/lodi"));
    // check-host-safety: refusal — the same scratch root.
    let same = case.lodi(&["host", "plan", "--root", &case.root_arg()]);
    assert_eq!(same.status.code(), Some(3), "{}", stderr(&same));
    assert!(
        stderr(&same).contains("E_DUP_RESOURCE")
            && stderr(&same).contains("/etc/apt/sources.list.d/docker.sources"),
        "{}",
        stderr(&same)
    );
}

/// Copy a fixture subtree into the scratch root, files and directories, nothing else.
fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir_all(to).expect("the target directory");
    for entry in fs::read_dir(from).expect("the fixture subtree").flatten() {
        let target = to.join(entry.file_name());
        if entry.path().is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            fs::copy(entry.path(), &target).expect("a fixture file");
        }
    }
}
